language: cpp
os: linux
dist: bionic
compiler: gcc

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    update: true
    packages:
      - libgsl-dev
      - libomp-dev
      - libxpm-dev
      - libreadline-dev
      - qt4-dev-tools
      - lcov

before_install:
  # Getting root binaries
  - cd ${TRAVIS_BUILD_DIR}/..
  - wget --quiet https://root.cern/download/root_v6.20.04.Linux-ubuntu18-x86_64-gcc7.5.tar.gz
  - tar -xzf root_v6.20.04.Linux-ubuntu18-x86_64-gcc7.5.tar.gz
  - source root/bin/thisroot.sh
  - sudo pip install codecov

install:
  # build the project
  - cd ${TRAVIS_BUILD_DIR}
  - bash build.sh

script:
  # run the project
  - ./build/AZURE2 || echo "Couldn't run AZURE2"

after_success:
  - lcov -d . -c -o coverage.info
  - codecov