package:
  name: azure2
  version: 1.0

source:
  git_rev: main
  git_url: https://github.com/skowrons94/pyazr

requirements:
  build:
    - root
    - qt
    - qwt
    - mesalib
    - llvm-openmp
    - clang
    - cmake
    - make

  run:
    - root
    - qt
    - qwt
    - mesalib
    - llvm-openmp

about:
  home: https://github.com/skowrons94/pyazr
  license: MIT
  license_family: MIT
  summary: AZURE2