package:
  name: azure2
  version: 1.0

source:
  path: ./

requirements:
  build:
    - minuit2
    - qt
    - qwt
    - gsl
    - mesalib
    - llvm-openmp
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make

  run:
    - minuit2
    - qt
    - qwt
    - gsl
    - mesalib
    - llvm-openmp

about:
  home: https://github.com/rdeboer1/AZURE2
  license: MIT
  license_family: MIT
  summary: AZURE2