package:
  name: azure2
  version: 1.0

source:
  git_rev: api
  git_url: https://github.com/rdeboer1/AZURE2

requirements:
  build:
    - root
    - qt
    - qwt
    - mesalib
    - llvm-openmp
    - clang
    - cmake
    - make

  run:
    - root
    - qt
    - qwt
    - mesalib
    - llvm-openmp

about:
  home: https://github.com/rdeboer1/AZURE2
  license: MIT
  license_family: MIT
  summary: AZURE2