.TH "/Users/kuba/Desktop/R-Matrix/AZURE2/src Directory Reference" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kuba/Desktop/R-Matrix/AZURE2/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAChannel\&.cpp\fP"
.br
.ti -1c
.RI "file \fBALevel\&.cpp\fP"
.br
.ti -1c
.RI "file \fBAMatrixFunc\&.cpp\fP"
.br
.ti -1c
.RI "file \fBAngCoeff\&.cpp\fP"
.br
.ti -1c
.RI "file \fBAZURE2\&.cpp\fP"
.br
.ti -1c
.RI "file \fBAZURECalc\&.cpp\fP"
.br
.ti -1c
.RI "file \fBAZUREMain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBAZUREOutput\&.cpp\fP"
.br
.ti -1c
.RI "file \fBAZUREParams\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCNuc\&.cpp\fP"
.br
.ti -1c
.RI "file \fBConfig\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCoulFunc\&.cpp\fP"
.br
.ti -1c
.RI "file \fBDecay\&.cpp\fP"
.br
.ti -1c
.RI "file \fBDoubleFactorial\&.cpp\fP"
.br
.ti -1c
.RI "file \fBECIntegral\&.cpp\fP"
.br
.ti -1c
.RI "file \fBECMGroup\&.cpp\fP"
.br
.ti -1c
.RI "file \fBEData\&.cpp\fP"
.br
.ti -1c
.RI "file \fBEDataIterator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBEffectiveCharge\&.cpp\fP"
.br
.ti -1c
.RI "file \fBEigenFunc\&.cpp\fP"
.br
.ti -1c
.RI "file \fBEPoint\&.cpp\fP"
.br
.ti -1c
.RI "file \fBEquation\&.cpp\fP"
.br
.ti -1c
.RI "file \fBESegment\&.cpp\fP"
.br
.ti -1c
.RI "file \fBGenMatrixFunc\&.cpp\fP"
.br
.ti -1c
.RI "file \fBGSLException\&.cpp\fP"
.br
.ti -1c
.RI "file \fBIntegratedFermiFunc\&.cpp\fP"
.br
.ti -1c
.RI "file \fBInterference\&.cpp\fP"
.br
.ti -1c
.RI "file \fBJGroup\&.cpp\fP"
.br
.ti -1c
.RI "file \fBKGroup\&.cpp\fP"
.br
.ti -1c
.RI "file \fBKLGroup\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMatrixInv\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMGroup\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNFIntegral\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPPair\&.cpp\fP"
.br
.ti -1c
.RI "file \fBReactionRate\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRMatrixFunc\&.cpp\fP"
.br
.ti -1c
.RI "file \fBShftFunc\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTargetEffect\&.cpp\fP"
.br
.in -1c
