.TH "AboutAZURE2Dialog" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AboutAZURE2Dialog
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AboutAZURE2Dialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAboutAZURE2Dialog\fP (QWidget *parent=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBAboutAZURE2Dialog\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AboutAZURE2Dialog::AboutAZURE2Dialog (QWidget * parent = \fC0\fP)"

.PP
Definition at line \fB7\fP of file \fBAboutAZURE2Dialog\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
