.TH "AChannel" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AChannel \- An AZURE channel object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AChannel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAChannel\fP (\fBNucLine\fP, int)"
.br
.ti -1c
.RI "\fBAChannel\fP (int, double, int, char)"
.br
.ti -1c
.RI "int \fBGetPairNum\fP () const"
.br
.ti -1c
.RI "int \fBGetL\fP () const"
.br
.ti -1c
.RI "double \fBGetS\fP () const"
.br
.ti -1c
.RI "double \fBGetBoundaryCondition\fP () const"
.br
.ti -1c
.RI "char \fBGetRadType\fP () const"
.br
.ti -1c
.RI "void \fBSetBoundaryCondition\fP (double)"
.br
.in -1c
.SH "Detailed Description"
.PP 
An AZURE channel object\&. 

An R-Matrix channel for a given $J^\pi$ group represents a specfic combination of $ \alpha,s,l $ couplings\&. 
.PP
Definition at line \fB12\fP of file \fBAChannel\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AChannel::AChannel (\fBNucLine\fP nucLine, int pairNum)"
This constructor can be used if a channel is to be created from a specific line of the nuclear input file\&. 
.PP
Definition at line \fB11\fP of file \fBAChannel\&.cpp\fP\&.
.SS "AChannel::AChannel (int lValue, double sValue, int pairNum, char radType)"
This constructor can be used if a channel is to be created directly using specified channel couplings\&. 
.PP
Definition at line \fB30\fP of file \fBAChannel\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "double AChannel::GetBoundaryCondition () const"
Returns the boundary condition for the channel\&. The energy of the boundary condition is fixed at the first level given in the nuclear input file for a given $ J^\pi $ group\&. 
.PP
Definition at line \fB65\fP of file \fBAChannel\&.cpp\fP\&.
.SS "int AChannel::GetL () const"
Returns the orbital angular momentum for the channel\&. 
.PP
Definition at line \fB49\fP of file \fBAChannel\&.cpp\fP\&.
.SS "int AChannel::GetPairNum () const"
Returns the pair number, or position of the corresponding particle pair in the \fBPPair\fP vector, for the channel\&. 
.PP
Definition at line \fB41\fP of file \fBAChannel\&.cpp\fP\&.
.SS "char AChannel::GetRadType () const"
Returns the radiation type for the channel\&. Radiation types are:
.IP "\(bu" 2
P: Particle Radiation
.IP "\(bu" 2
E: EL Electromagnetic Radiation
.IP "\(bu" 2
M: ML Electromagnetic Radiation 
.PP

.PP
Definition at line \fB76\fP of file \fBAChannel\&.cpp\fP\&.
.SS "double AChannel::GetS () const"
Returns the coupled channel spin for the channel\&. 
.PP
Definition at line \fB57\fP of file \fBAChannel\&.cpp\fP\&.
.SS "void AChannel::SetBoundaryCondition (double boundaryCondition)"
This function is used to set the boundary condition for the channel\&. 
.PP
Definition at line \fB83\fP of file \fBAChannel\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
