.TH "/Users/kuba/Desktop/R-Matrix/AZURE2/include/AChannel.h" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kuba/Desktop/R-Matrix/AZURE2/include/AChannel.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAChannel\fP"
.br
.RI "An AZURE channel object\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
