.TH "AddPairDialog" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddPairDialog
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AddPairDialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBupdateLightParticle\fP (int index)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddPairDialog\fP (QWidget *parent=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QLineEdit * \fBlightJText\fP"
.br
.ti -1c
.RI "QComboBox * \fBlightPiCombo\fP"
.br
.ti -1c
.RI "QLineEdit * \fBlightZText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBlightMText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBheavyJText\fP"
.br
.ti -1c
.RI "QComboBox * \fBheavyPiCombo\fP"
.br
.ti -1c
.RI "QLineEdit * \fBheavyZText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBheavyMText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBexcitationEnergyText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBseperationEnergyText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBchannelRadiusText\fP"
.br
.ti -1c
.RI "QComboBox * \fBpairTypeCombo\fP"
.br
.ti -1c
.RI "QCheckBox * \fBe1Check\fP"
.br
.ti -1c
.RI "QCheckBox * \fBe2Check\fP"
.br
.ti -1c
.RI "QGroupBox * \fBmultBox\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBAddPairDialog\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AddPairDialog::AddPairDialog (QWidget * parent = \fC0\fP)"

.PP
Definition at line \fB13\fP of file \fBAddPairDialog\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void AddPairDialog::updateLightParticle (int index)\fC [slot]\fP"

.PP
Definition at line \fB151\fP of file \fBAddPairDialog\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "QLineEdit* AddPairDialog::channelRadiusText"

.PP
Definition at line \fB34\fP of file \fBAddPairDialog\&.h\fP\&.
.SS "QCheckBox* AddPairDialog::e1Check"

.PP
Definition at line \fB36\fP of file \fBAddPairDialog\&.h\fP\&.
.SS "QCheckBox* AddPairDialog::e2Check"

.PP
Definition at line \fB38\fP of file \fBAddPairDialog\&.h\fP\&.
.SS "QLineEdit* AddPairDialog::excitationEnergyText"

.PP
Definition at line \fB32\fP of file \fBAddPairDialog\&.h\fP\&.
.SS "QLineEdit* AddPairDialog::heavyJText"

.PP
Definition at line \fB27\fP of file \fBAddPairDialog\&.h\fP\&.
.SS "QLineEdit* AddPairDialog::heavyMText"

.PP
Definition at line \fB30\fP of file \fBAddPairDialog\&.h\fP\&.
.SS "QComboBox* AddPairDialog::heavyPiCombo"

.PP
Definition at line \fB28\fP of file \fBAddPairDialog\&.h\fP\&.
.SS "QLineEdit* AddPairDialog::heavyZText"

.PP
Definition at line \fB29\fP of file \fBAddPairDialog\&.h\fP\&.
.SS "QLineEdit* AddPairDialog::lightJText"

.PP
Definition at line \fB22\fP of file \fBAddPairDialog\&.h\fP\&.
.SS "QLineEdit* AddPairDialog::lightMText"

.PP
Definition at line \fB25\fP of file \fBAddPairDialog\&.h\fP\&.
.SS "QComboBox* AddPairDialog::lightPiCombo"

.PP
Definition at line \fB23\fP of file \fBAddPairDialog\&.h\fP\&.
.SS "QLineEdit* AddPairDialog::lightZText"

.PP
Definition at line \fB24\fP of file \fBAddPairDialog\&.h\fP\&.
.SS "QGroupBox* AddPairDialog::multBox"

.PP
Definition at line \fB39\fP of file \fBAddPairDialog\&.h\fP\&.
.SS "QComboBox* AddPairDialog::pairTypeCombo"

.PP
Definition at line \fB35\fP of file \fBAddPairDialog\&.h\fP\&.
.SS "QLineEdit* AddPairDialog::seperationEnergyText"

.PP
Definition at line \fB33\fP of file \fBAddPairDialog\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
