.TH "AddSegTestDialog" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddSegTestDialog
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AddSegTestDialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBdataTypeChanged\fP (int)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddSegTestDialog\fP (QWidget *parent=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QSpinBox * \fBentrancePairIndexSpin\fP"
.br
.ti -1c
.RI "QSpinBox * \fBexitPairIndexSpin\fP"
.br
.ti -1c
.RI "QLineEdit * \fBlowEnergyText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBhighEnergyText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBenergyStepText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBlowAngleText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBhighAngleText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBangleStepText\fP"
.br
.ti -1c
.RI "QComboBox * \fBdataTypeCombo\fP"
.br
.ti -1c
.RI "QLineEdit * \fBphaseJValueText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBphaseLValueText\fP"
.br
.ti -1c
.RI "QLabel * \fBphaseJValueLabel\fP"
.br
.ti -1c
.RI "QLabel * \fBphaseLValueLabel\fP"
.br
.ti -1c
.RI "QLabel * \fBangDistLabel\fP"
.br
.ti -1c
.RI "QLabel * \fBtotalCaptureLabel\fP"
.br
.ti -1c
.RI "QSpinBox * \fBangDistSpin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBAddSegTestDialog\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AddSegTestDialog::AddSegTestDialog (QWidget * parent = \fC0\fP)"

.PP
Definition at line \fB9\fP of file \fBAddSegTestDialog\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void AddSegTestDialog::dataTypeChanged (int index)\fC [slot]\fP"

.PP
Definition at line \fB135\fP of file \fBAddSegTestDialog\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "QLabel* AddSegTestDialog::angDistLabel"

.PP
Definition at line \fB34\fP of file \fBAddSegTestDialog\&.h\fP\&.
.SS "QSpinBox* AddSegTestDialog::angDistSpin"

.PP
Definition at line \fB36\fP of file \fBAddSegTestDialog\&.h\fP\&.
.SS "QLineEdit* AddSegTestDialog::angleStepText"

.PP
Definition at line \fB28\fP of file \fBAddSegTestDialog\&.h\fP\&.
.SS "QComboBox* AddSegTestDialog::dataTypeCombo"

.PP
Definition at line \fB29\fP of file \fBAddSegTestDialog\&.h\fP\&.
.SS "QLineEdit* AddSegTestDialog::energyStepText"

.PP
Definition at line \fB25\fP of file \fBAddSegTestDialog\&.h\fP\&.
.SS "QSpinBox* AddSegTestDialog::entrancePairIndexSpin"

.PP
Definition at line \fB21\fP of file \fBAddSegTestDialog\&.h\fP\&.
.SS "QSpinBox* AddSegTestDialog::exitPairIndexSpin"

.PP
Definition at line \fB22\fP of file \fBAddSegTestDialog\&.h\fP\&.
.SS "QLineEdit* AddSegTestDialog::highAngleText"

.PP
Definition at line \fB27\fP of file \fBAddSegTestDialog\&.h\fP\&.
.SS "QLineEdit* AddSegTestDialog::highEnergyText"

.PP
Definition at line \fB24\fP of file \fBAddSegTestDialog\&.h\fP\&.
.SS "QLineEdit* AddSegTestDialog::lowAngleText"

.PP
Definition at line \fB26\fP of file \fBAddSegTestDialog\&.h\fP\&.
.SS "QLineEdit* AddSegTestDialog::lowEnergyText"

.PP
Definition at line \fB23\fP of file \fBAddSegTestDialog\&.h\fP\&.
.SS "QLabel* AddSegTestDialog::phaseJValueLabel"

.PP
Definition at line \fB32\fP of file \fBAddSegTestDialog\&.h\fP\&.
.SS "QLineEdit* AddSegTestDialog::phaseJValueText"

.PP
Definition at line \fB30\fP of file \fBAddSegTestDialog\&.h\fP\&.
.SS "QLabel* AddSegTestDialog::phaseLValueLabel"

.PP
Definition at line \fB33\fP of file \fBAddSegTestDialog\&.h\fP\&.
.SS "QLineEdit* AddSegTestDialog::phaseLValueText"

.PP
Definition at line \fB31\fP of file \fBAddSegTestDialog\&.h\fP\&.
.SS "QLabel* AddSegTestDialog::totalCaptureLabel"

.PP
Definition at line \fB35\fP of file \fBAddSegTestDialog\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
