.TH "AddSegDataDialog" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddSegDataDialog
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AddSegDataDialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetChooseFile\fP ()"
.br
.ti -1c
.RI "void \fBdataTypeChanged\fP (int)"
.br
.ti -1c
.RI "void \fBvaryNormChanged\fP (int)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddSegDataDialog\fP (QWidget *parent=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QSpinBox * \fBentrancePairIndexSpin\fP"
.br
.ti -1c
.RI "QSpinBox * \fBexitPairIndexSpin\fP"
.br
.ti -1c
.RI "QLineEdit * \fBlowEnergyText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBhighEnergyText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBlowAngleText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBhighAngleText\fP"
.br
.ti -1c
.RI "QComboBox * \fBdataTypeCombo\fP"
.br
.ti -1c
.RI "QLineEdit * \fBdataFileText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBdataNormText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBdataNormErrorText\fP"
.br
.ti -1c
.RI "QLabel * \fBdataNormErrorLabel\fP"
.br
.ti -1c
.RI "QCheckBox * \fBvaryNormCheck\fP"
.br
.ti -1c
.RI "QLineEdit * \fBphaseJValueText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBphaseLValueText\fP"
.br
.ti -1c
.RI "QLabel * \fBphaseLValueLabel\fP"
.br
.ti -1c
.RI "QLabel * \fBphaseJValueLabel\fP"
.br
.ti -1c
.RI "QLabel * \fBtotalCaptureLabel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBAddSegDataDialog\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AddSegDataDialog::AddSegDataDialog (QWidget * parent = \fC0\fP)"

.PP
Definition at line \fB8\fP of file \fBAddSegDataDialog\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void AddSegDataDialog::dataTypeChanged (int index)\fC [slot]\fP"

.PP
Definition at line \fB154\fP of file \fBAddSegDataDialog\&.cpp\fP\&.
.SS "void AddSegDataDialog::setChooseFile ()\fC [slot]\fP"

.PP
Definition at line \fB147\fP of file \fBAddSegDataDialog\&.cpp\fP\&.
.SS "void AddSegDataDialog::varyNormChanged (int state)\fC [slot]\fP"

.PP
Definition at line \fB184\fP of file \fBAddSegDataDialog\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "QLineEdit* AddSegDataDialog::dataFileText"

.PP
Definition at line \fB29\fP of file \fBAddSegDataDialog\&.h\fP\&.
.SS "QLabel* AddSegDataDialog::dataNormErrorLabel"

.PP
Definition at line \fB32\fP of file \fBAddSegDataDialog\&.h\fP\&.
.SS "QLineEdit* AddSegDataDialog::dataNormErrorText"

.PP
Definition at line \fB31\fP of file \fBAddSegDataDialog\&.h\fP\&.
.SS "QLineEdit* AddSegDataDialog::dataNormText"

.PP
Definition at line \fB30\fP of file \fBAddSegDataDialog\&.h\fP\&.
.SS "QComboBox* AddSegDataDialog::dataTypeCombo"

.PP
Definition at line \fB28\fP of file \fBAddSegDataDialog\&.h\fP\&.
.SS "QSpinBox* AddSegDataDialog::entrancePairIndexSpin"

.PP
Definition at line \fB22\fP of file \fBAddSegDataDialog\&.h\fP\&.
.SS "QSpinBox* AddSegDataDialog::exitPairIndexSpin"

.PP
Definition at line \fB23\fP of file \fBAddSegDataDialog\&.h\fP\&.
.SS "QLineEdit* AddSegDataDialog::highAngleText"

.PP
Definition at line \fB27\fP of file \fBAddSegDataDialog\&.h\fP\&.
.SS "QLineEdit* AddSegDataDialog::highEnergyText"

.PP
Definition at line \fB25\fP of file \fBAddSegDataDialog\&.h\fP\&.
.SS "QLineEdit* AddSegDataDialog::lowAngleText"

.PP
Definition at line \fB26\fP of file \fBAddSegDataDialog\&.h\fP\&.
.SS "QLineEdit* AddSegDataDialog::lowEnergyText"

.PP
Definition at line \fB24\fP of file \fBAddSegDataDialog\&.h\fP\&.
.SS "QLabel* AddSegDataDialog::phaseJValueLabel"

.PP
Definition at line \fB37\fP of file \fBAddSegDataDialog\&.h\fP\&.
.SS "QLineEdit* AddSegDataDialog::phaseJValueText"

.PP
Definition at line \fB34\fP of file \fBAddSegDataDialog\&.h\fP\&.
.SS "QLabel* AddSegDataDialog::phaseLValueLabel"

.PP
Definition at line \fB36\fP of file \fBAddSegDataDialog\&.h\fP\&.
.SS "QLineEdit* AddSegDataDialog::phaseLValueText"

.PP
Definition at line \fB35\fP of file \fBAddSegDataDialog\&.h\fP\&.
.SS "QLabel* AddSegDataDialog::totalCaptureLabel"

.PP
Definition at line \fB38\fP of file \fBAddSegDataDialog\&.h\fP\&.
.SS "QCheckBox* AddSegDataDialog::varyNormCheck"

.PP
Definition at line \fB33\fP of file \fBAddSegDataDialog\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
