.TH "AddTargetIntDialog" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddTargetIntDialog
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AddTargetIntDialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBconvolutionCheckChanged\fP (bool checked)"
.br
.ti -1c
.RI "void \fBtargetIntCheckChanged\fP (bool checked)"
.br
.ti -1c
.RI "void \fBparameterSpinChanged\fP (int newNumber)"
.br
.ti -1c
.RI "void \fBparameterChanged\fP (int row, int column)"
.br
.ti -1c
.RI "void \fBqCoefficientCheckChanged\fP (bool checked)"
.br
.ti -1c
.RI "void \fBqCoefficientSpinChanged\fP (int newNumber)"
.br
.ti -1c
.RI "void \fBqCoefficientChanged\fP (int row, int column)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddTargetIntDialog\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBcreateParameterItem\fP (int row, double value=0\&.0)"
.br
.ti -1c
.RI "void \fBcreateQCoefficientItem\fP (int row, double value=1\&.0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QCheckBox * \fBisConvolutionCheck\fP"
.br
.ti -1c
.RI "QCheckBox * \fBisTargetIntegrationCheck\fP"
.br
.ti -1c
.RI "QCheckBox * \fBisQCoefficientCheck\fP"
.br
.ti -1c
.RI "QLineEdit * \fBsigmaText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBsegmentsListText\fP"
.br
.ti -1c
.RI "QSpinBox * \fBnumPointsSpin\fP"
.br
.ti -1c
.RI "QSpinBox * \fBnumParametersSpin\fP"
.br
.ti -1c
.RI "QSpinBox * \fBnumQCoefficientSpin\fP"
.br
.ti -1c
.RI "QLineEdit * \fBdensityText\fP"
.br
.ti -1c
.RI "QLineEdit * \fBstoppingPowerEqText\fP"
.br
.ti -1c
.RI "QTableWidget * \fBparametersTable\fP"
.br
.ti -1c
.RI "QTableWidget * \fBqCoefficientTable\fP"
.br
.ti -1c
.RI "QList< double > \fBtempParameters\fP"
.br
.ti -1c
.RI "QList< double > \fBtempQCoefficients\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBAddTargetIntDialog\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AddTargetIntDialog::AddTargetIntDialog (QWidget * parent = \fC0\fP)"

.PP
Definition at line \fB14\fP of file \fBAddTargetIntDialog\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void AddTargetIntDialog::convolutionCheckChanged (bool checked)\fC [slot]\fP"

.PP
Definition at line \fB175\fP of file \fBAddTargetIntDialog\&.cpp\fP\&.
.SS "void AddTargetIntDialog::createParameterItem (int row, double value = \fC0\&.0\fP)"

.PP
Definition at line \fB153\fP of file \fBAddTargetIntDialog\&.cpp\fP\&.
.SS "void AddTargetIntDialog::createQCoefficientItem (int row, double value = \fC1\&.0\fP)"

.PP
Definition at line \fB164\fP of file \fBAddTargetIntDialog\&.cpp\fP\&.
.SS "void AddTargetIntDialog::parameterChanged (int row, int column)\fC [slot]\fP"

.PP
Definition at line \fB209\fP of file \fBAddTargetIntDialog\&.cpp\fP\&.
.SS "void AddTargetIntDialog::parameterSpinChanged (int newNumber)\fC [slot]\fP"

.PP
Definition at line \fB198\fP of file \fBAddTargetIntDialog\&.cpp\fP\&.
.SS "void AddTargetIntDialog::qCoefficientChanged (int row, int column)\fC [slot]\fP"

.PP
Definition at line \fB241\fP of file \fBAddTargetIntDialog\&.cpp\fP\&.
.SS "void AddTargetIntDialog::qCoefficientCheckChanged (bool checked)\fC [slot]\fP"

.PP
Definition at line \fB219\fP of file \fBAddTargetIntDialog\&.cpp\fP\&.
.SS "void AddTargetIntDialog::qCoefficientSpinChanged (int newNumber)\fC [slot]\fP"

.PP
Definition at line \fB230\fP of file \fBAddTargetIntDialog\&.cpp\fP\&.
.SS "void AddTargetIntDialog::targetIntCheckChanged (bool checked)\fC [slot]\fP"

.PP
Definition at line \fB185\fP of file \fBAddTargetIntDialog\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "QLineEdit* AddTargetIntDialog::densityText"

.PP
Definition at line \fB30\fP of file \fBAddTargetIntDialog\&.h\fP\&.
.SS "QCheckBox* AddTargetIntDialog::isConvolutionCheck"

.PP
Definition at line \fB22\fP of file \fBAddTargetIntDialog\&.h\fP\&.
.SS "QCheckBox* AddTargetIntDialog::isQCoefficientCheck"

.PP
Definition at line \fB24\fP of file \fBAddTargetIntDialog\&.h\fP\&.
.SS "QCheckBox* AddTargetIntDialog::isTargetIntegrationCheck"

.PP
Definition at line \fB23\fP of file \fBAddTargetIntDialog\&.h\fP\&.
.SS "QSpinBox* AddTargetIntDialog::numParametersSpin"

.PP
Definition at line \fB28\fP of file \fBAddTargetIntDialog\&.h\fP\&.
.SS "QSpinBox* AddTargetIntDialog::numPointsSpin"

.PP
Definition at line \fB27\fP of file \fBAddTargetIntDialog\&.h\fP\&.
.SS "QSpinBox* AddTargetIntDialog::numQCoefficientSpin"

.PP
Definition at line \fB29\fP of file \fBAddTargetIntDialog\&.h\fP\&.
.SS "QTableWidget* AddTargetIntDialog::parametersTable"

.PP
Definition at line \fB32\fP of file \fBAddTargetIntDialog\&.h\fP\&.
.SS "QTableWidget* AddTargetIntDialog::qCoefficientTable"

.PP
Definition at line \fB33\fP of file \fBAddTargetIntDialog\&.h\fP\&.
.SS "QLineEdit* AddTargetIntDialog::segmentsListText"

.PP
Definition at line \fB26\fP of file \fBAddTargetIntDialog\&.h\fP\&.
.SS "QLineEdit* AddTargetIntDialog::sigmaText"

.PP
Definition at line \fB25\fP of file \fBAddTargetIntDialog\&.h\fP\&.
.SS "QLineEdit* AddTargetIntDialog::stoppingPowerEqText"

.PP
Definition at line \fB31\fP of file \fBAddTargetIntDialog\&.h\fP\&.
.SS "QList<double> AddTargetIntDialog::tempParameters"

.PP
Definition at line \fB34\fP of file \fBAddTargetIntDialog\&.h\fP\&.
.SS "QList<double> AddTargetIntDialog::tempQCoefficients"

.PP
Definition at line \fB35\fP of file \fBAddTargetIntDialog\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
