.TH "/Users/kuba/Desktop/R-Matrix/AZURE2/src/AMatrixFunc.cpp" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kuba/Desktop/R-Matrix/AZURE2/src/AMatrixFunc.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'AMatrixFunc\&.h'\fP
.br
\fC#include 'CNuc\&.h'\fP
.br
\fC#include 'Config\&.h'\fP
.br
\fC#include 'EPoint\&.h'\fP
.br
\fC#include 'MatrixInv\&.h'\fP
.br
\fC#include <assert\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
