.TH "AngCoeff" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AngCoeff \- A container class for angular coupling coefficient functions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AngCoeff\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static double \fBClebGord\fP (double, double, double, double, double, double)"
.br
.ti -1c
.RI "static double \fBRacah\fP (double, double, double, double, double, double)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A container class for angular coupling coefficient functions\&. 

The \fBAngCoeff\fP class serves as a container class for the angular momentum coupling coefficients\&. 
.br
 
.PP
Definition at line \fB11\fP of file \fBAngCoeff\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "double AngCoeff::ClebGord (double j1, double j2, double j3, double m1, double m2, double m3)\fC [static]\fP"
Returns the Clebsh-Gordan coefficient for the given angular momentum quantum numbers\&. 
.PP
Definition at line \fB5\fP of file \fBAngCoeff\&.cpp\fP\&.
.SS "double AngCoeff::Racah (double j1, double j2, double l2, double l1, double j3, double l3)\fC [static]\fP"
Returns the Racah coefficient for the given angular momentum quantum numbers\&. 
.PP
Definition at line \fB19\fP of file \fBAngCoeff\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
