.TH "AZURESetup" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AZURESetup
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AZURESetup\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBSaveAndRun\fP ()"
.br
.ti -1c
.RI "void \fBDeleteThread\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAZURESetup\fP ()"
.br
.ti -1c
.RI "\fBConfig\fP & \fBGetConfig\fP ()"
.br
.ti -1c
.RI "void \fBopen\fP (QString filename)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB35\fP of file \fBAZURESetup\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AZURESetup::AZURESetup ()"

.PP
Definition at line \fB35\fP of file \fBAZURESetup\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void AZURESetup::DeleteThread ()\fC [slot]\fP"

.PP
Definition at line \fB962\fP of file \fBAZURESetup\&.cpp\fP\&.
.SS "\fBConfig\fP & AZURESetup::GetConfig ()"

.PP
Definition at line \fB80\fP of file \fBAZURESetup\&.cpp\fP\&.
.SS "void AZURESetup::open (QString filename)"

.PP
Definition at line \fB205\fP of file \fBAZURESetup\&.cpp\fP\&.
.SS "void AZURESetup::SaveAndRun ()\fC [slot]\fP"

.PP
Definition at line \fB783\fP of file \fBAZURESetup\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
