.TH "AZUREMainThread" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AZUREMainThread
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AZUREMainThread\&.h>\fP
.PP
Inherits QThread\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBstopAZURE\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBreadyToRun\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAZUREMainThread\fP (\fBRunTab\fP *tab, const \fBConfig\fP &\fBconfigure\fP)"
.br
.ti -1c
.RI "const \fBConfig\fP & \fBconfigure\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB32\fP of file \fBAZUREMainThread\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AZUREMainThread::AZUREMainThread (\fBRunTab\fP * tab, const \fBConfig\fP & configure)\fC [inline]\fP"

.PP
Definition at line \fB35\fP of file \fBAZUREMainThread\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "const \fBConfig\fP & AZUREMainThread::configure () const\fC [inline]\fP"

.PP
Definition at line \fB53\fP of file \fBAZUREMainThread\&.h\fP\&.
.SS "void AZUREMainThread::readyToRun ()\fC [signal]\fP"

.SS "void AZUREMainThread::run ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line \fB61\fP of file \fBAZUREMainThread\&.h\fP\&.
.SS "void AZUREMainThread::stopAZURE ()\fC [inline]\fP, \fC [slot]\fP"

.PP
Definition at line \fB57\fP of file \fBAZUREMainThread\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
