.TH "AZUREParams" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AZUREParams \- A container class to hold Minuit parameters in AZURE\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AZUREParams\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "ROOT::Minuit2::MnUserParameters & \fBGetMinuitParams\fP ()"
.br
.ti -1c
.RI "void \fBReadUserParameters\fP (const \fBConfig\fP &)"
.br
.ti -1c
.RI "void \fBWriteUserParameters\fP (const \fBConfig\fP &, bool)"
.br
.ti -1c
.RI "void \fBWriteParameterErrors\fP (const std::vector< std::pair< double, double > > &, const \fBConfig\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A container class to hold Minuit parameters in AZURE\&. 

The \fBAZUREParams\fP class holds the Minuit parameters determined in the fit\&. The class also has member functions corresponding to reading and writing of the parameters and their errors\&. 
.PP
Definition at line \fB20\fP of file \fBAZUREParams\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "ROOT::Minuit2::MnUserParameters & AZUREParams::GetMinuitParams ()"
This function returns the MnUserParameters object used by Minuit to store the fit parameters\&. 
.PP
Definition at line \fB9\fP of file \fBAZUREParams\&.cpp\fP\&.
.SS "void AZUREParams::ReadUserParameters (const \fBConfig\fP & configure)"
This function reads the user specified parameters from a given file\&. 
.br
 These parameters are formal R-matrix parameters, and overwrite any initial parameters determined from the nuclear input file\&. 
.PP
Definition at line \fB19\fP of file \fBAZUREParams\&.cpp\fP\&.
.SS "void AZUREParams::WriteParameterErrors (const std::vector< std::pair< double, double > > & errors, const \fBConfig\fP & configure)"
This function writes the parameter errors to a file if Minos has been invoked\&. 
.PP
Definition at line \fB88\fP of file \fBAZUREParams\&.cpp\fP\&.
.SS "void AZUREParams::WriteUserParameters (const \fBConfig\fP & configure, bool fitParameters)"
This function writes the formal R-matrix parameters to a file\&. 
.PP
Definition at line \fB66\fP of file \fBAZUREParams\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
