.TH "/Users/kuba/Desktop/R-Matrix/AZURE2/include/AZUREMain.h" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kuba/Desktop/R-Matrix/AZURE2/include/AZUREMain.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CNuc\&.h'\fP
.br
\fC#include 'EData\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAZUREMain\fP"
.br
.RI "The top-level AZURE function class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
