.TH "/Users/kuba/Desktop/R-Matrix/AZURE2/gui/src/AZURESetup.cpp" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kuba/Desktop/R-Matrix/AZURE2/gui/src/AZURESetup.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QTextEdit>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QScrollBar>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QMenu>\fP
.br
\fC#include <QMenuBar>\fP
.br
\fC#include <QRadioButton>\fP
.br
\fC#include <QAction>\fP
.br
\fC#include <QActionGroup>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QTextStream>\fP
.br
\fC#include <QDesktopServices>\fP
.br
\fC#include 'AZURESetup\&.h'\fP
.br
\fC#include 'EditChecksDialog\&.h'\fP
.br
\fC#include 'EditDirsDialog\&.h'\fP
.br
\fC#include 'RunTab\&.h'\fP
.br
\fC#include 'Config\&.h'\fP
.br
\fC#include 'EditOptionsDialog\&.h'\fP
.br
\fC#include 'AZUREMainThread\&.h'\fP
.br
\fC#include 'AboutAZURE2Dialog\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSegPairs\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBreadSegmentFile\fP (const \fBConfig\fP &configure, std::vector< \fBSegPairs\fP > &segPairs)"
.br
.ti -1c
.RI "bool \fBcheckExternalCapture\fP (\fBConfig\fP &configure, const std::vector< \fBSegPairs\fP > &segPairs)"
.br
.ti -1c
.RI "void \fBstartMessage\fP (const \fBConfig\fP &configure)"
.br
.ti -1c
.RI "void \fBexitMessage\fP (const \fBConfig\fP &configure)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool checkExternalCapture (\fBConfig\fP & configure, const std::vector< \fBSegPairs\fP > & segPairs)"
This function checks the external capture file against a vector of segment key pairs\&. Only if the calculation includes external capture segments is the user prompted for an integrals file\&. The appropriate configure flag is set here\&. 
.PP
Definition at line \fB438\fP of file \fBAZURE2\&.cpp\fP\&.
.SS "void exitMessage (const \fBConfig\fP & configure)"
This function prints a message upon successful termination of the program\&. 
.PP
Definition at line \fB56\fP of file \fBAZURE2\&.cpp\fP\&.
.SS "bool readSegmentFile (const \fBConfig\fP & configure, std::vector< \fBSegPairs\fP > & segPairs)"
This function reads the segment file, and stores the active entrance and exit pair keys for cross reference with the External capture file\&. Only if an active external capture segment is required is the user prompted for an external integrals file\&. 
.PP
Definition at line \fB247\fP of file \fBAZURE2\&.cpp\fP\&.
.SS "void startMessage (const \fBConfig\fP & configure)"
This function prints a brief start message describing the type of calculation that will be performed\&. 
.PP
Definition at line \fB539\fP of file \fBAZURE2\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
