.TH "AZUREFBuffer" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AZUREFBuffer \- A container class for a pointer to a file buffer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AZUREFBuffer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAZUREFBuffer\fP (int entranceKey, int exitKey, std::string outputdir, bool isExtrap, bool isAngDist)"
.br
.ti -1c
.RI "\fB~AZUREFBuffer\fP ()"
.br
.ti -1c
.RI "bool \fBIsAngDist\fP () const"
.br
.ti -1c
.RI "int \fBGetEntranceKey\fP () const"
.br
.ti -1c
.RI "int \fBGetExitKey\fP () const"
.br
.ti -1c
.RI "std::filebuf * \fBGetFBuffer\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A container class for a pointer to a file buffer\&. 

The \fBAZUREFBuffer\fP class contains a pointer to an acutal file buffer, as well as the entrance and exit pair keys to which the file buffer corresponds\&. 
.br
 
.PP
Definition at line \fB15\fP of file \fBAZUREFBuffer\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AZUREFBuffer::AZUREFBuffer (int entranceKey, int exitKey, std::string outputdir, bool isExtrap, bool isAngDist)\fC [inline]\fP"
The \fBAZUREFBuffer\fP object is created with an entrance and exit pair key, as well as an output directory\&. The filename is determined, and a file buffer is created with that filename\&. 
.PP
Definition at line \fB21\fP of file \fBAZUREFBuffer\&.h\fP\&.
.SS "AZUREFBuffer::~AZUREFBuffer ()\fC [inline]\fP"
The file buffer is closed and destroyed with the instance of \fBAZUREFBuffer\fP\&. 
.PP
Definition at line \fB43\fP of file \fBAZUREFBuffer\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int AZUREFBuffer::GetEntranceKey () const\fC [inline]\fP"
Returns the entrance pair key of the object\&. 
.PP
Definition at line \fB54\fP of file \fBAZUREFBuffer\&.h\fP\&.
.SS "int AZUREFBuffer::GetExitKey () const\fC [inline]\fP"
Returns the exit pair key of the object\&. 
.PP
Definition at line \fB58\fP of file \fBAZUREFBuffer\&.h\fP\&.
.SS "std::filebuf * AZUREFBuffer::GetFBuffer ()\fC [inline]\fP"
Returns a pointer to the corresponding file buffer\&. 
.PP
Definition at line \fB62\fP of file \fBAZUREFBuffer\&.h\fP\&.
.SS "bool AZUREFBuffer::IsAngDist () const\fC [inline]\fP"
Returns true if the buffer is for angular distribution, otherwise returns false\&. 
.PP
Definition at line \fB50\fP of file \fBAZUREFBuffer\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
