.TH "AZUREZoomer" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AZUREZoomer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AZUREPlot\&.h>\fP
.PP
Inherits QwtPlotZoomer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAZUREZoomer\fP (QWidget *canvas)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "QwtText \fBtrackerTextF\fP (const QPointF &pos) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB24\fP of file \fBAZUREPlot\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AZUREZoomer::AZUREZoomer (QWidget * canvas)\fC [inline]\fP"

.PP
Definition at line \fB26\fP of file \fBAZUREPlot\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "QwtText AZUREZoomer::trackerTextF (const QPointF & pos) const\fC [protected]\fP"

.PP
Definition at line \fB23\fP of file \fBAZUREPlot\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
