.TH "AZUREPlot" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AZUREPlot
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AZUREPlot\&.h>\fP
.PP
Inherits QwtPlot\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBdraw\fP (QList< \fBPlotEntry\fP * > newEntries)"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.ti -1c
.RI "void \fBexportPlot\fP ()"
.br
.ti -1c
.RI "void \fBprint\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAZUREPlot\fP (\fBPlotTab\fP *plotTab, QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetXAxisLog\fP (bool set)"
.br
.ti -1c
.RI "void \fBsetYAxisLog\fP (bool set)"
.br
.ti -1c
.RI "void \fBsetXAxisType\fP (unsigned int type)"
.br
.ti -1c
.RI "void \fBsetYAxisType\fP (unsigned int type)"
.br
.ti -1c
.RI "void \fBclearEntries\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB59\fP of file \fBAZUREPlot\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AZUREPlot::AZUREPlot (\fBPlotTab\fP * plotTab, QWidget * parent = \fC0\fP)"

.PP
Definition at line \fB229\fP of file \fBAZUREPlot\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void AZUREPlot::clearEntries ()"

.PP
Definition at line \fB383\fP of file \fBAZUREPlot\&.cpp\fP\&.
.SS "void AZUREPlot::draw (QList< \fBPlotEntry\fP * > newEntries)\fC [slot]\fP"

.PP
Definition at line \fB285\fP of file \fBAZUREPlot\&.cpp\fP\&.
.SS "void AZUREPlot::exportPlot ()\fC [slot]\fP"

.PP
Definition at line \fB326\fP of file \fBAZUREPlot\&.cpp\fP\&.
.SS "void AZUREPlot::print ()\fC [slot]\fP"

.PP
Definition at line \fB367\fP of file \fBAZUREPlot\&.cpp\fP\&.
.SS "void AZUREPlot::setXAxisLog (bool set)"

.PP
Definition at line \fB248\fP of file \fBAZUREPlot\&.cpp\fP\&.
.SS "void AZUREPlot::setXAxisType (unsigned int type)"

.PP
Definition at line \fB267\fP of file \fBAZUREPlot\&.cpp\fP\&.
.SS "void AZUREPlot::setYAxisLog (bool set)"

.PP
Definition at line \fB256\fP of file \fBAZUREPlot\&.cpp\fP\&.
.SS "void AZUREPlot::setYAxisType (unsigned int type)"

.PP
Definition at line \fB278\fP of file \fBAZUREPlot\&.cpp\fP\&.
.SS "void AZUREPlot::update ()\fC [slot]\fP"

.PP
Definition at line \fB313\fP of file \fBAZUREPlot\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
