.TH "AZUREMainThreadWorker" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AZUREMainThreadWorker
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AZUREMainThread\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBdone\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAZUREMainThreadWorker\fP (const \fBConfig\fP &configure)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBAZUREMainThread\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AZUREMainThreadWorker::AZUREMainThreadWorker (const \fBConfig\fP & configure)\fC [inline]\fP"

.PP
Definition at line \fB19\fP of file \fBAZUREMainThread\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void AZUREMainThreadWorker::done ()\fC [signal]\fP"

.SS "void AZUREMainThreadWorker::run ()\fC [inline]\fP, \fC [slot]\fP"

.PP
Definition at line \fB24\fP of file \fBAZUREMainThread\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
