.TH "/Users/kuba/Desktop/R-Matrix/AZURE2/gui/include/AZUREMainThread.h" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kuba/Desktop/R-Matrix/AZURE2/gui/include/AZUREMainThread.h
.SH SYNOPSIS
.br
.PP
\fC#include <QThread>\fP
.br
\fC#include <QEventLoop>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include 'TextEditBuffer\&.h'\fP
.br
\fC#include 'FilteredTextEdit\&.h'\fP
.br
\fC#include 'RunTab\&.h'\fP
.br
\fC#include 'AZUREMain\&.h'\fP
.br
\fC#include 'Config\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAZUREMainThreadWorker\fP"
.br
.ti -1c
.RI "class \fBAZUREMainThread\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
