.TH "AZUREMain" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AZUREMain \- The top-level AZURE function class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AZUREMain\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAZUREMain\fP (const \fBConfig\fP &\fBconfigure\fP)"
.br
.ti -1c
.RI "\fB~AZUREMain\fP ()"
.br
.ti -1c
.RI "int \fBoperator()\fP ()"
.br
.ti -1c
.RI "const \fBConfig\fP & \fBconfigure\fP () const"
.br
.ti -1c
.RI "\fBCNuc\fP * \fBcompound\fP () const"
.br
.ti -1c
.RI "\fBEData\fP * \fBdata\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
The top-level AZURE function class\&. 

The \fBAZUREMain\fP function class is the top level function class in the AZURE package\&. It is called directly from them \fBmain()\fP using the configuration parameters read from the runtime file as well as from the command shell prompt\&. 
.PP
Definition at line \fB14\fP of file \fBAZUREMain\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AZUREMain::AZUREMain (const \fBConfig\fP & configure)\fC [inline]\fP"
The \fBAZUREMain\fP function class is created using a \fBConfig\fP structure\&. New \fBCNuc\fP and \fBEData\fP objects are created at initialization of an \fBAZUREMain\fP object\&. 
.PP
Definition at line \fB20\fP of file \fBAZUREMain\&.h\fP\&.
.SS "AZUREMain::~AZUREMain ()\fC [inline]\fP"
The \fBCNuc\fP and \fBEData\fP objects are destroyed with the \fBAZUREMain\fP instance\&. 
.PP
Definition at line \fB27\fP of file \fBAZUREMain\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCNuc\fP * AZUREMain::compound () const\fC [inline]\fP"
Returns a pointer to the \fBCNuc\fP object\&. 
.PP
Definition at line \fB43\fP of file \fBAZUREMain\&.h\fP\&.
.SS "const \fBConfig\fP & AZUREMain::configure () const\fC [inline]\fP"
Returns a reference to the \fBConfig\fP structure\&. 
.PP
Definition at line \fB39\fP of file \fBAZUREMain\&.h\fP\&.
.SS "\fBEData\fP * AZUREMain::data () const\fC [inline]\fP"
Returns a pointer to the \fBEData\fP object\&. 
.PP
Definition at line \fB47\fP of file \fBAZUREMain\&.h\fP\&.
.SS "int AZUREMain::operator() ()"
The parenthesis operator is defined so the instance of \fBAZUREMain\fP can be called as a function\&. This executes AZURE against the configuration parameters\&. 
.PP
Definition at line \fB12\fP of file \fBAZUREMain\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
