.TH "/Users/kuba/Desktop/R-Matrix/AZURE2/include/AZUREParams.h" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kuba/Desktop/R-Matrix/AZURE2/include/AZUREParams.h
.SH SYNOPSIS
.br
.PP
\fC#include <Minuit2/MnUserParameters\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include 'Constants\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAZUREParams\fP"
.br
.RI "A container class to hold Minuit parameters in AZURE\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
