.TH "AZURECalc" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AZURECalc \- A function class to perform the calculation of the chi-squared value\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AZURECalc\&.h>\fP
.PP
Inherits ROOT::Minuit2::FCNBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAZURECalc\fP (\fBEData\fP *\fBdata\fP, \fBCNuc\fP *\fBcompound\fP, const \fBConfig\fP &\fBconfigure\fP)"
.br
.ti -1c
.RI "\fB~AZURECalc\fP ()"
.br
.ti -1c
.RI "virtual double \fBUp\fP () const"
.br
.ti -1c
.RI "virtual double \fBoperator()\fP (const \fBvector_r\fP &) const"
.br
.ti -1c
.RI "const \fBConfig\fP & \fBconfigure\fP () const"
.br
.ti -1c
.RI "\fBEData\fP * \fBdata\fP () const"
.br
.ti -1c
.RI "\fBCNuc\fP * \fBcompound\fP () const"
.br
.ti -1c
.RI "void \fBSetErrorDef\fP (double def)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A function class to perform the calculation of the chi-squared value\&. 

The \fBAZURECalc\fP function class calculates the cross section based on a parameter set for all available data, and returns a chi-squared value\&. This function class is what Minuit calls repeatedly during the fitting process to perform the minimization\&. 
.PP
Definition at line \fB21\fP of file \fBAZURECalc\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AZURECalc::AZURECalc (\fBEData\fP * data, \fBCNuc\fP * compound, const \fBConfig\fP & configure)\fC [inline]\fP"
The \fBAZURECalc\fP object is created with reference to an \fBEData\fP and \fBCNuc\fP object\&. \&. The runtime configurations are also passed through a \fBConfig\fP structure\&. 
.PP
Definition at line \fB27\fP of file \fBAZURECalc\&.h\fP\&.
.SS "AZURECalc::~AZURECalc ()\fC [inline]\fP"

.PP
Definition at line \fB32\fP of file \fBAZURECalc\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCNuc\fP * AZURECalc::compound () const\fC [inline]\fP"
Returns a pointer to the \fBCNuc\fP object\&. 
.PP
Definition at line \fB55\fP of file \fBAZURECalc\&.h\fP\&.
.SS "const \fBConfig\fP & AZURECalc::configure () const\fC [inline]\fP"
Returns a reference to the \fBConfig\fP structure\&. 
.PP
Definition at line \fB47\fP of file \fBAZURECalc\&.h\fP\&.
.SS "\fBEData\fP * AZURECalc::data () const\fC [inline]\fP"
Returns a pointer to the \fBEData\fP object\&. 
.PP
Definition at line \fB51\fP of file \fBAZURECalc\&.h\fP\&.
.SS "double AZURECalc::operator() (const \fBvector_r\fP & p) const\fC [virtual]\fP"
Overloaded operator to make the class instance callable as a function\&. A Minuit parameter array is passed as the dependent variable\&. The function returns the total chi-squared value\&. 
.PP
Definition at line \fB8\fP of file \fBAZURECalc\&.cpp\fP\&.
.SS "void AZURECalc::SetErrorDef (double def)\fC [inline]\fP"
See Minuit2 documentation for an explanation of this function\&. 
.PP
Definition at line \fB60\fP of file \fBAZURECalc\&.h\fP\&.
.SS "virtual double AZURECalc::Up () const\fC [inline]\fP, \fC [virtual]\fP"
See Minuit2 documentation for an explanation of this function\&. 
.PP
Definition at line \fB36\fP of file \fBAZURECalc\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
