.TH "ChannelsData" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChannelsData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ChannelsModel\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBisFixed\fP"
.br
.ti -1c
.RI "int \fBlevelIndex\fP"
.br
.ti -1c
.RI "int \fBpairIndex\fP"
.br
.ti -1c
.RI "double \fBsValue\fP"
.br
.ti -1c
.RI "int \fBlValue\fP"
.br
.ti -1c
.RI "QChar \fBradType\fP"
.br
.ti -1c
.RI "double \fBreducedWidth\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBSIZE\fP = 7"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBChannelsModel\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ChannelsData::isFixed"

.PP
Definition at line \fB9\fP of file \fBChannelsModel\&.h\fP\&.
.SS "int ChannelsData::levelIndex"

.PP
Definition at line \fB10\fP of file \fBChannelsModel\&.h\fP\&.
.SS "int ChannelsData::lValue"

.PP
Definition at line \fB13\fP of file \fBChannelsModel\&.h\fP\&.
.SS "int ChannelsData::pairIndex"

.PP
Definition at line \fB11\fP of file \fBChannelsModel\&.h\fP\&.
.SS "QChar ChannelsData::radType"

.PP
Definition at line \fB14\fP of file \fBChannelsModel\&.h\fP\&.
.SS "double ChannelsData::reducedWidth"

.PP
Definition at line \fB15\fP of file \fBChannelsModel\&.h\fP\&.
.SS "const int ChannelsData::SIZE = 7\fC [static]\fP"

.PP
Definition at line \fB8\fP of file \fBChannelsModel\&.h\fP\&.
.SS "double ChannelsData::sValue"

.PP
Definition at line \fB12\fP of file \fBChannelsModel\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
