.TH "ChannelDetails" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChannelDetails
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ChannelDetails\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChannelDetails\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetNormParam\fP (int which)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QLineEdit * \fBreducedWidthText\fP"
.br
.ti -1c
.RI "QLabel * \fBdetails\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBChannelDetails\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ChannelDetails::ChannelDetails (QWidget * parent = \fC0\fP)"

.PP
Definition at line \fB8\fP of file \fBChannelDetails\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ChannelDetails::setNormParam (int which)"

.PP
Definition at line \fB31\fP of file \fBChannelDetails\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "QLabel* ChannelDetails::details"

.PP
Definition at line \fB20\fP of file \fBChannelDetails\&.h\fP\&.
.SS "QLineEdit* ChannelDetails::reducedWidthText"

.PP
Definition at line \fB19\fP of file \fBChannelDetails\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
