.TH "ChannelsModel" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChannelsModel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ChannelsModel\&.h>\fP
.PP
Inherits QAbstractTableModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChannelsModel\fP (QObject *parent=0)"
.br
.ti -1c
.RI "int \fBrowCount\fP (const QModelIndex &parent) const"
.br
.ti -1c
.RI "int \fBcolumnCount\fP (const QModelIndex &parent) const"
.br
.ti -1c
.RI "QVariant \fBdata\fP (const QModelIndex &index, int role) const"
.br
.ti -1c
.RI "QVariant \fBheaderData\fP (int section, Qt::Orientation orientation, int role) const"
.br
.ti -1c
.RI "QList< \fBChannelsData\fP > \fBgetChannels\fP () const"
.br
.ti -1c
.RI "bool \fBsetData\fP (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)"
.br
.ti -1c
.RI "bool \fBinsertRows\fP (int position, int rows, const QModelIndex &index=QModelIndex())"
.br
.ti -1c
.RI "bool \fBremoveRows\fP (int position, int rows, const QModelIndex &index=QModelIndex())"
.br
.ti -1c
.RI "Qt::ItemFlags \fBflags\fP (const QModelIndex &index) const"
.br
.ti -1c
.RI "bool \fBisChannel\fP (const \fBChannelsData\fP &channel) const"
.br
.ti -1c
.RI "QString \fBgetSpinLabel\fP (const \fBChannelsData\fP &channel) const"
.br
.ti -1c
.RI "void \fBsetPairsModel\fP (\fBPairsModel\fP *model)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB20\fP of file \fBChannelsModel\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ChannelsModel::ChannelsModel (QObject * parent = \fC0\fP)"

.PP
Definition at line \fB4\fP of file \fBChannelsModel\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int ChannelsModel::columnCount (const QModelIndex & parent) const"

.PP
Definition at line \fB12\fP of file \fBChannelsModel\&.cpp\fP\&.
.SS "QVariant ChannelsModel::data (const QModelIndex & index, int role) const"

.PP
Definition at line \fB17\fP of file \fBChannelsModel\&.cpp\fP\&.
.SS "Qt::ItemFlags ChannelsModel::flags (const QModelIndex & index) const"

.PP
Definition at line \fB156\fP of file \fBChannelsModel\&.cpp\fP\&.
.SS "QList< \fBChannelsData\fP > ChannelsModel::getChannels () const\fC [inline]\fP"

.PP
Definition at line \fB30\fP of file \fBChannelsModel\&.h\fP\&.
.SS "QString ChannelsModel::getSpinLabel (const \fBChannelsData\fP & channel) const"

.PP
Definition at line \fB179\fP of file \fBChannelsModel\&.cpp\fP\&.
.SS "QVariant ChannelsModel::headerData (int section, Qt::Orientation orientation, int role) const"

.PP
Definition at line \fB71\fP of file \fBChannelsModel\&.cpp\fP\&.
.SS "bool ChannelsModel::insertRows (int position, int rows, const QModelIndex & index = \fCQModelIndex()\fP)"

.PP
Definition at line \fB131\fP of file \fBChannelsModel\&.cpp\fP\&.
.SS "bool ChannelsModel::isChannel (const \fBChannelsData\fP & channel) const"

.PP
Definition at line \fB162\fP of file \fBChannelsModel\&.cpp\fP\&.
.SS "bool ChannelsModel::removeRows (int position, int rows, const QModelIndex & index = \fCQModelIndex()\fP)"

.PP
Definition at line \fB144\fP of file \fBChannelsModel\&.cpp\fP\&.
.SS "int ChannelsModel::rowCount (const QModelIndex & parent) const"

.PP
Definition at line \fB7\fP of file \fBChannelsModel\&.cpp\fP\&.
.SS "bool ChannelsModel::setData (const QModelIndex & index, const QVariant & value, int role = \fCQt::EditRole\fP)"

.PP
Definition at line \fB98\fP of file \fBChannelsModel\&.cpp\fP\&.
.SS "void ChannelsModel::setPairsModel (\fBPairsModel\fP * model)"

.PP
Definition at line \fB184\fP of file \fBChannelsModel\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
