.TH "ChooseFileButton" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChooseFileButton
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ChooseFileButton\&.h>\fP
.PP
Inherits QPushButton\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBclick\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBclicked\fP (QLineEdit *lineEdit)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChooseFileButton\fP (const QString &text, QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetLineEdit\fP (QLineEdit *lineEdit)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBChooseFileButton\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ChooseFileButton::ChooseFileButton (const QString & text, QWidget * parent = \fC0\fP)"

.PP
Definition at line \fB3\fP of file \fBChooseFileButton\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ChooseFileButton::click ()\fC [slot]\fP"

.PP
Definition at line \fB12\fP of file \fBChooseFileButton\&.cpp\fP\&.
.SS "void ChooseFileButton::clicked (QLineEdit * lineEdit)\fC [signal]\fP"

.SS "void ChooseFileButton::setLineEdit (QLineEdit * lineEdit)"

.PP
Definition at line \fB8\fP of file \fBChooseFileButton\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
