.TH "/Users/kuba/Desktop/R-Matrix/AZURE2/include/Constants.h" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kuba/Desktop/R-Matrix/AZURE2/include/Constants.h
.SH SYNOPSIS
.br
.PP
\fC#include <complex>\fP
.br
\fC#include <vector>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::complex< double > \fBcomplex\fP"
.br
.ti -1c
.RI "typedef std::vector< double > \fBvector_r\fP"
.br
.ti -1c
.RI "typedef std::vector< \fBstd::complex\fP< double > > \fBvector_c\fP"
.br
.ti -1c
.RI "typedef std::vector< std::vector< double > > \fBmatrix_r\fP"
.br
.ti -1c
.RI "typedef std::vector< std::vector< \fBstd::complex\fP< double > > > \fBmatrix_c\fP"
.br
.ti -1c
.RI "typedef std::vector< std::vector< std::vector< double > > > \fBvector_matrix_r\fP"
.br
.ti -1c
.RI "typedef std::vector< std::vector< std::vector< \fBstd::complex\fP< double > > > > \fBvector_matrix_c\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const double \fBpi\fP =3\&.141592650"
.br
.ti -1c
.RI "const double \fBhbarc\fP =197\&.32696310"
.br
.ti -1c
.RI "const double \fBuconv\fP =931\&.4940880"
.br
.ti -1c
.RI "const double \fBfstruc\fP =1\&.00/137\&.0359996790"
.br
.ti -1c
.RI "const double \fBboltzConst\fP =8\&.6171e\-2"
.br
.ti -1c
.RI "const double \fBlightSpeedInCmPerS\fP =29979245800\&."
.br
.ti -1c
.RI "const double \fBavagadroNum\fP =6\&.02214179e23"
.br
.ti -1c
.RI "const double \fBnuclearMagneton\fP =0\&.105155"
.br
.ti -1c
.RI "const unsigned char \fBisE1\fP = 1 << 0"
.br
.ti -1c
.RI "const unsigned char \fBisM1\fP = 1 << 1"
.br
.ti -1c
.RI "const unsigned char \fBisE2\fP = 1 << 2"
.br
.ti -1c
.RI "const int \fBmaxECMult\fP =2"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::complex<double> \fBcomplex\fP"

.PP
Definition at line \fB20\fP of file \fBConstants\&.h\fP\&.
.SS "typedef std::vector<std::vector<\fBstd::complex\fP<double> > > \fBmatrix_c\fP"

.PP
Definition at line \fB24\fP of file \fBConstants\&.h\fP\&.
.SS "typedef std::vector<std::vector<double> > \fBmatrix_r\fP"

.PP
Definition at line \fB23\fP of file \fBConstants\&.h\fP\&.
.SS "typedef std::vector<\fBstd::complex\fP<double> > \fBvector_c\fP"

.PP
Definition at line \fB22\fP of file \fBConstants\&.h\fP\&.
.SS "typedef std::vector<std::vector<std::vector<\fBstd::complex\fP<double> > > > \fBvector_matrix_c\fP"

.PP
Definition at line \fB26\fP of file \fBConstants\&.h\fP\&.
.SS "typedef std::vector<std::vector<std::vector<double> > > \fBvector_matrix_r\fP"

.PP
Definition at line \fB25\fP of file \fBConstants\&.h\fP\&.
.SS "typedef std::vector<double> \fBvector_r\fP"

.PP
Definition at line \fB21\fP of file \fBConstants\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "const double avagadroNum =6\&.02214179e23"

.PP
Definition at line \fB13\fP of file \fBConstants\&.h\fP\&.
.SS "const double boltzConst =8\&.6171e\-2"

.PP
Definition at line \fB11\fP of file \fBConstants\&.h\fP\&.
.SS "const double fstruc =1\&.00/137\&.0359996790"

.PP
Definition at line \fB10\fP of file \fBConstants\&.h\fP\&.
.SS "const double hbarc =197\&.32696310"

.PP
Definition at line \fB8\fP of file \fBConstants\&.h\fP\&.
.SS "const unsigned char isE1 = 1 << 0"

.PP
Definition at line \fB15\fP of file \fBConstants\&.h\fP\&.
.SS "const unsigned char isE2 = 1 << 2"

.PP
Definition at line \fB17\fP of file \fBConstants\&.h\fP\&.
.SS "const unsigned char isM1 = 1 << 1"

.PP
Definition at line \fB16\fP of file \fBConstants\&.h\fP\&.
.SS "const double lightSpeedInCmPerS =29979245800\&."

.PP
Definition at line \fB12\fP of file \fBConstants\&.h\fP\&.
.SS "const int maxECMult =2"

.PP
Definition at line \fB18\fP of file \fBConstants\&.h\fP\&.
.SS "const double nuclearMagneton =0\&.105155"

.PP
Definition at line \fB14\fP of file \fBConstants\&.h\fP\&.
.SS "const double pi =3\&.141592650"

.PP
Definition at line \fB7\fP of file \fBConstants\&.h\fP\&.
.SS "const double uconv =931\&.4940880"

.PP
Definition at line \fB9\fP of file \fBConstants\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
