.TH "CoulWaves" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoulWaves \- The return structure of the \fBCoulFunc\fP function class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CoulFunc\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBF\fP"
.br
.RI "Regular solution\&. "
.ti -1c
.RI "double \fBdF\fP"
.br
.RI "Derivative of regular solution with respect to $ \rho $\&. "
.ti -1c
.RI "double \fBG\fP"
.br
.RI "Irregular solution\&. "
.ti -1c
.RI "double \fBdG\fP"
.br
.RI "Derivative of irregular solution with respect to $ \rho $\&. "
.in -1c
.SH "Detailed Description"
.PP 
The return structure of the \fBCoulFunc\fP function class\&. 

The \fBCoulWaves\fP structure contains both the irregular and regular solutions to the Coulomb equation, as well as their derivatives with respect to $ \rho $\&. 
.PP
Definition at line \fB13\fP of file \fBCoulFunc\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double CoulWaves::dF"

.PP
Derivative of regular solution with respect to $ \rho $\&. 
.PP
Definition at line \fB17\fP of file \fBCoulFunc\&.h\fP\&.
.SS "double CoulWaves::dG"

.PP
Derivative of irregular solution with respect to $ \rho $\&. 
.PP
Definition at line \fB21\fP of file \fBCoulFunc\&.h\fP\&.
.SS "double CoulWaves::F"

.PP
Regular solution\&. 
.PP
Definition at line \fB15\fP of file \fBCoulFunc\&.h\fP\&.
.SS "double CoulWaves::G"

.PP
Irregular solution\&. 
.PP
Definition at line \fB19\fP of file \fBCoulFunc\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
