.TH "CoulFunc" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoulFunc \- A function class to calculate Coulomb functions for positive energy channels\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CoulFunc\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCoulFunc\fP (\fBPPair\fP *pPair, bool useGSLFunctions)"
.br
.ti -1c
.RI "int \fBz1\fP () const"
.br
.ti -1c
.RI "int \fBz2\fP () const"
.br
.ti -1c
.RI "double \fBredmass\fP () const"
.br
.ti -1c
.RI "int \fBlLast\fP () const"
.br
.ti -1c
.RI "double \fBradiusLast\fP () const"
.br
.ti -1c
.RI "double \fBenergyLast\fP () const"
.br
.ti -1c
.RI "struct \fBCoulWaves\fP \fBcoulLast\fP () const"
.br
.ti -1c
.RI "void \fBsetLast\fP (int, double, double, \fBCoulWaves\fP)"
.br
.ti -1c
.RI "\fBCoulWaves\fP \fBoperator()\fP (int, double, double)"
.br
.ti -1c
.RI "double \fBPenetrability\fP (int, double, double)"
.br
.ti -1c
.RI "double \fBPEShift\fP (int, double, double)"
.br
.ti -1c
.RI "double \fBPEShift_dE\fP (int, double, double)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A function class to calculate Coulomb functions for positive energy channels\&. 

The \fBCoulFunc\fP function class calculates the solutions to the Coulomb equation, as well as other useful quantities such as shift functions and their energy derivative and penetrabilities\&. 
.PP
Definition at line \fB32\fP of file \fBCoulFunc\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CoulFunc::CoulFunc (\fBPPair\fP * pPair, bool useGSLFunctions)"
The \fBCoulFunc\fP object is created with reference to a \fBPPair\fP object\&. 
.PP
Definition at line \fB12\fP of file \fBCoulFunc\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "struct \fBCoulWaves\fP CoulFunc::coulLast () const"
Returns the last Coulomb functions which were calculated\&. 
.PP
Definition at line \fB82\fP of file \fBCoulFunc\&.cpp\fP\&.
.SS "double CoulFunc::energyLast () const"
Returns the last energy value at which the Coulomb functions were calculated\&. 
.PP
Definition at line \fB74\fP of file \fBCoulFunc\&.cpp\fP\&.
.SS "int CoulFunc::lLast () const"
Returns the last orbital angular momentum value at which the Coulomb functions were calculated\&. 
.PP
Definition at line \fB56\fP of file \fBCoulFunc\&.cpp\fP\&.
.SS "\fBCoulWaves\fP CoulFunc::operator() (int l, double radius, double energy)"
The parenthesis operator is defined to make the class instance callable as a function\&. The orbital angular momentum, radius, and energy in the center of mass system are the dependent variables\&. The function returns the Coulomb waves\&. 
.PP
Definition at line \fB106\fP of file \fBCoulFunc\&.cpp\fP\&.
.SS "double CoulFunc::Penetrability (int l, double radius, double energy)"
Returns the penetrability as a function of orbital angular momentum, radius, and energy in the center of mass system\&. 
.PP
Definition at line \fB151\fP of file \fBCoulFunc\&.cpp\fP\&.
.SS "double CoulFunc::PEShift (int l, double radius, double energy)"
Returns the positive energy shift function a function of orbital angular momentum, radius, and energy in the center of mass system\&. 
.PP
Definition at line \fB162\fP of file \fBCoulFunc\&.cpp\fP\&.
.SS "double CoulFunc::PEShift_dE (int l, double radius, double energy)"
Returns the energy derivative of the shift function a function of orbital angular momentum, radius, and energy in the center of mass system\&. 
.PP
Definition at line \fB184\fP of file \fBCoulFunc\&.cpp\fP\&.
.SS "double CoulFunc::radiusLast () const"
Returns the last radius value at which the Coulomb functions were calculated\&. 
.PP
Definition at line \fB65\fP of file \fBCoulFunc\&.cpp\fP\&.
.SS "double CoulFunc::redmass () const"
Returns the reduced mass of the particle pair\&. 
.PP
Definition at line \fB47\fP of file \fBCoulFunc\&.cpp\fP\&.
.SS "void CoulFunc::setLast (int lLast, double rLast, double eLast, \fBCoulWaves\fP coulLast)"
Sets the last calculated Coulomb waves and the values for which they were calculated\&. 
.PP
Definition at line \fB90\fP of file \fBCoulFunc\&.cpp\fP\&.
.SS "int CoulFunc::z1 () const"
Returns the atomic number of the first particle in the pair\&. 
.PP
Definition at line \fB31\fP of file \fBCoulFunc\&.cpp\fP\&.
.SS "int CoulFunc::z2 () const"
Returns the atomic number of the second particle in the pair\&. 
.PP
Definition at line \fB39\fP of file \fBCoulFunc\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
