.TH "Coulomb_wave_functions" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coulomb_wave_functions
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cwfcomp\&.H>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCoulomb_wave_functions\fP (const bool is_it_normalized_c, const std::complex< double > &l_c, const std::complex< double > &eta_c)"
.br
.ti -1c
.RI "\fB~Coulomb_wave_functions\fP (void)"
.br
.ti -1c
.RI "void \fBF_dF_init\fP (const std::complex< double > &z, const std::complex< double > &F, const std::complex< double > &dF)"
.br
.ti -1c
.RI "void \fBF_dF\fP (const std::complex< double > &z, std::complex< double > &F, std::complex< double > &dF)"
.br
.ti -1c
.RI "void \fBG_dG\fP (const std::complex< double > &z, std::complex< double > &G, std::complex< double > &dG)"
.br
.ti -1c
.RI "void \fBH_dH\fP (const int omega, const std::complex< double > &z, std::complex< double > &H, std::complex< double > &dH)"
.br
.ti -1c
.RI "void \fBH_dH_scaled\fP (const int omega, const std::complex< double > &z, std::complex< double > &H, std::complex< double > &dH)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const std::complex< double > \fBl\fP"
.br
.ti -1c
.RI "const std::complex< double > \fBeta\fP"
.br
.ti -1c
.RI "const bool \fBis_it_normalized\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBcwfcomp\&.H\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Coulomb_wave_functions::Coulomb_wave_functions (const bool is_it_normalized_c, const std::complex< double > & l_c, const std::complex< double > & eta_c)\fC [inline]\fP"

.PP
Definition at line \fB25\fP of file \fBcwfcomp\&.H\fP\&.
.SS "Coulomb_wave_functions::~Coulomb_wave_functions (void)\fC [inline]\fP"

.PP
Definition at line \fB68\fP of file \fBcwfcomp\&.H\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Coulomb_wave_functions::F_dF (const std::complex< double > & z, std::complex< double > & F, std::complex< double > & dF)"

.PP
Definition at line \fB1162\fP of file \fBcwfcomp\&.cpp\fP\&.
.SS "void Coulomb_wave_functions::F_dF_init (const std::complex< double > & z, const std::complex< double > & F, const std::complex< double > & dF)"

.PP
Definition at line \fB1433\fP of file \fBcwfcomp\&.cpp\fP\&.
.SS "void Coulomb_wave_functions::G_dG (const std::complex< double > & z, std::complex< double > & G, std::complex< double > & dG)"

.PP
Definition at line \fB1233\fP of file \fBcwfcomp\&.cpp\fP\&.
.SS "void Coulomb_wave_functions::H_dH (const int omega, const std::complex< double > & z, std::complex< double > & H, std::complex< double > & dH)"

.PP
Definition at line \fB1304\fP of file \fBcwfcomp\&.cpp\fP\&.
.SS "void Coulomb_wave_functions::H_dH_scaled (const int omega, const std::complex< double > & z, std::complex< double > & H, std::complex< double > & dH)"

.PP
Definition at line \fB1384\fP of file \fBcwfcomp\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const std::complex<double> Coulomb_wave_functions::eta"

.PP
Definition at line \fB91\fP of file \fBcwfcomp\&.H\fP\&.
.SS "const bool Coulomb_wave_functions::is_it_normalized"

.PP
Definition at line \fB93\fP of file \fBcwfcomp\&.H\fP\&.
.SS "const std::complex<double> Coulomb_wave_functions::l"

.PP
Definition at line \fB91\fP of file \fBcwfcomp\&.H\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
