.TH "DataLine" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataLine \- A class to read and store a line from a data file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataLine\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataLine\fP (std::ifstream &stream)"
.br
.ti -1c
.RI "double \fBangle\fP () const"
.br
.ti -1c
.RI "double \fBenergy\fP () const"
.br
.ti -1c
.RI "double \fBcrossSection\fP () const"
.br
.ti -1c
.RI "double \fBerror\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class to read and store a line from a data file\&. 

The \fBDataLine\fP class reads and stores a formatted line from a data file\&. 
.PP
Definition at line \fB12\fP of file \fBDataLine\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DataLine::DataLine (std::ifstream & stream)\fC [inline]\fP"
Constructor fills the \fBDataLine\fP object from an input stream\&. 
.PP
Definition at line \fB17\fP of file \fBDataLine\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "double DataLine::angle () const\fC [inline]\fP"
Returns the angle for the read in data point\&. 
.PP
Definition at line \fB23\fP of file \fBDataLine\&.h\fP\&.
.SS "double DataLine::crossSection () const\fC [inline]\fP"
Returns the cross section for the read in data point\&. 
.PP
Definition at line \fB31\fP of file \fBDataLine\&.h\fP\&.
.SS "double DataLine::energy () const\fC [inline]\fP"
Returns the energy for the read in data point\&. 
.PP
Definition at line \fB27\fP of file \fBDataLine\&.h\fP\&.
.SS "double DataLine::error () const\fC [inline]\fP"
Returns the cross section error for the read in data point\&. 
.PP
Definition at line \fB35\fP of file \fBDataLine\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
