.TH "Decay" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Decay \- An AZURE decay pair\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Decay\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecay\fP (int)"
.br
.ti -1c
.RI "int \fBGetPairNum\fP () const"
.br
.ti -1c
.RI "int \fBNumKGroups\fP () const"
.br
.ti -1c
.RI "int \fBNumKLGroups\fP () const"
.br
.ti -1c
.RI "int \fBIsKGroup\fP (\fBKGroup\fP)"
.br
.ti -1c
.RI "int \fBIsKLGroup\fP (\fBKLGroup\fP)"
.br
.ti -1c
.RI "void \fBAddKGroup\fP (\fBKGroup\fP)"
.br
.ti -1c
.RI "void \fBAddKLGroup\fP (\fBKLGroup\fP)"
.br
.ti -1c
.RI "\fBKGroup\fP * \fBGetKGroup\fP (int)"
.br
.ti -1c
.RI "\fBKLGroup\fP * \fBGetKLGroup\fP (int)"
.br
.in -1c
.SH "Detailed Description"
.PP 
An AZURE decay pair\&. 

In AZURE, a \fBDecay\fP object represents a decay pair of the compound nucleus\&. The \fBDecay\fP object is keyed to a particle pair in the \fBPPair\fP vector, and serves as a container class for the \fBKGroup\fP and the \fBKLGroup\fP vectors and their subsequent reaction pathways\&. 
.br
 
.PP
Definition at line \fB14\fP of file \fBDecay\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Decay::Decay (int pairNum)"
The \fBDecay\fP object is created with a reference to a particle pair number, which represents a position in the \fBPPair\fP vector\&. 
.br
 
.PP
Definition at line \fB8\fP of file \fBDecay\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Decay::AddKGroup (\fBKGroup\fP kGroup)"
Adds a $ s,s' $ combination to the \fBKGroup\fP vector\&. 
.PP
Definition at line \fB75\fP of file \fBDecay\&.cpp\fP\&.
.SS "void Decay::AddKLGroup (\fBKLGroup\fP klGroup)"
Adds a $ k,L $ combination to the \fBKLGroup\fP vector\&. 
.PP
Definition at line \fB83\fP of file \fBDecay\&.cpp\fP\&.
.SS "\fBKGroup\fP * Decay::GetKGroup (int kGroupNum)"
Returns a pointer to a $ s,s' $ combination specified by a position in the \fBKGroup\fP vector\&. 
.PP
Definition at line \fB91\fP of file \fBDecay\&.cpp\fP\&.
.SS "\fBKLGroup\fP * Decay::GetKLGroup (int klGroupNum)"
Returns a pointer to a $ k,L $ combination specified by a position in the \fBKLGroup\fP vector\&. 
.PP
Definition at line \fB100\fP of file \fBDecay\&.cpp\fP\&.
.SS "int Decay::GetPairNum () const"
Returns the pair number of the decay\&. 
.PP
Definition at line \fB15\fP of file \fBDecay\&.cpp\fP\&.
.SS "int Decay::IsKGroup (\fBKGroup\fP a)"
Tests a specific $ s,s' $ combination to determine if it exists in the \fBKGroup\fP vector\&. If the combination exists, the position of the combination in the vector is returned\&. Otherwise, the function returns 0\&. 
.PP
Definition at line \fB40\fP of file \fBDecay\&.cpp\fP\&.
.SS "int Decay::IsKLGroup (\fBKLGroup\fP a)"
Tests a specific $ k,L $ combination to determine if it exists in the \fBKLGroup\fP vector\&. If the combination exists, the position of the combination in the vector is returned\&. Otherwise, the function returns 0\&. 
.PP
Definition at line \fB58\fP of file \fBDecay\&.cpp\fP\&.
.SS "int Decay::NumKGroups () const"
Returns the number of $ s,s' $ combinations in the \fBKGroup\fP vector\&. 
.PP
Definition at line \fB23\fP of file \fBDecay\&.cpp\fP\&.
.SS "int Decay::NumKLGroups () const"
Returns the number of $ k,L $ combinations in the \fBKLGroup\fP vector\&. 
.PP
Definition at line \fB31\fP of file \fBDecay\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
