.TH "ECIntegral" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ECIntegral \- A function class to calculate external capture integrals\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ECIntegral\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBECIntegral\fP (\fBPPair\fP *pPair, const \fBConfig\fP &configure)"
.br
.ti -1c
.RI "\fB~ECIntegral\fP ()"
.br
.ti -1c
.RI "\fBcomplex\fP \fBoperator()\fP (int, int, double, double, double, double, int, char, double, double, bool)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A function class to calculate external capture integrals\&. 

The \fBECIntegral\fP function class calculates external capture integrals for both positive and negative energy channels\&. The results are returned as an ECIntResult structure\&. 
.PP
Definition at line \fB18\fP of file \fBECIntegral\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ECIntegral::ECIntegral (\fBPPair\fP * pPair, const \fBConfig\fP & configure)\fC [inline]\fP"
The \fBECIntegral\fP object is created with reference to a \fBPPair\fP object\&. The \fBPPair\fP object is used to create new instances of the \fBCoulFunc\fP and \fBWhitFunc\fP objects\&. 
.br
 
.PP
Definition at line \fB25\fP of file \fBECIntegral\&.h\fP\&.
.SS "ECIntegral::~ECIntegral ()\fC [inline]\fP"
The \fBCoulFunc\fP and \fBWhitFunc\fP objects are destroyed with the object\&. 
.PP
Definition at line \fB34\fP of file \fBECIntegral\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBcomplex\fP ECIntegral::operator() (int theInitialLValue, int theFinalLValue, double theInitialSValue, double theFinalSValue, double theInitialJValue, double theFinalJValue, int theLMult, char radType, double inEnergy, double levelEnergy, bool isChannelCapture)"
Overloaded operator to make the class instance callable as a function\&. The intial and final orbital angular momentum, the gamma multipolarity, and the incoming energy and final state energy in the compound system are the dependent variables\&. The function returns an ECIntResult structure\&. 
.PP
Definition at line \fB102\fP of file \fBECIntegral\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
