.TH "ECMGroup" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ECMGroup \- An AZURE external reaction pathway\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ECMGroup\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBECMGroup\fP (char, int, int, double, int, int, int)"
.br
.ti -1c
.RI "\fBECMGroup\fP (char, int, int, double, int, int, int, int, int, int, int)"
.br
.ti -1c
.RI "bool \fBIsChannelCapture\fP () const"
.br
.ti -1c
.RI "char \fBGetRadType\fP () const"
.br
.ti -1c
.RI "int \fBGetMult\fP () const"
.br
.ti -1c
.RI "int \fBGetL\fP () const"
.br
.ti -1c
.RI "int \fBGetFinalChannel\fP () const"
.br
.ti -1c
.RI "int \fBGetJGroupNum\fP () const"
.br
.ti -1c
.RI "int \fBGetLevelNum\fP () const"
.br
.ti -1c
.RI "int \fBGetChanCapDecay\fP () const"
.br
.ti -1c
.RI "int \fBGetChanCapKGroup\fP () const"
.br
.ti -1c
.RI "int \fBGetChanCapMGroup\fP () const"
.br
.ti -1c
.RI "int \fBGetIntChannelNum\fP () const"
.br
.ti -1c
.RI "double \fBGetJ\fP () const"
.br
.ti -1c
.RI "double \fBGetStatSpinFactor\fP () const"
.br
.ti -1c
.RI "void \fBSetStatSpinFactor\fP (double)"
.br
.in -1c
.SH "Detailed Description"
.PP 
An AZURE external reaction pathway\&. 

An external reaction pathways in AZURE is one of two types: a hard sphere pathway or a resonant pathway\&. The hard sphere pathways refers to the portion of the initial incoming plus outgoing scattering wavefunction that is hard-shpere scattered and captured directly to a final state\&. The resonant pathways refer to the portion of the outgoing scattering wavefunction that is scattered/transformed by the R-Matrix\&. This type of pathway is linked to the internal resonant pathways, and can be thought of as first passing through a the resonant T-matrix before being captured directly to a final state\&. 
.PP
Definition at line \fB17\fP of file \fBECMGroup\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ECMGroup::ECMGroup (char radType, int multipolarity, int lInitial, double jInitial, int finalChannelNum, int ecJGroupNum, int ecLevelNum)"
This constructor is used to create hard sphere external reaction pathways\&. The type of radiation is specified, as well as the position of the final state in the ECLevel vector\&. The final channel number is also specified\&. 
.PP
Definition at line \fB8\fP of file \fBECMGroup\&.cpp\fP\&.
.SS "ECMGroup::ECMGroup (char radType, int multipolarity, int lInitial, double jInitial, int finalChannelNum, int ecJGroupNum, int ecLevelNum, int decayNum, int kGroupNum, int mGroupNum, int internalChannel)"
This constructor is used to create resonant external reaction pathways\&. The constructor is passed identical information as in the previous case, with the addition of references to the resonant reaction pathways through which the external pathways will pass\&. 
.PP
Definition at line \fB19\fP of file \fBECMGroup\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int ECMGroup::GetChanCapDecay () const"
Returns the position of the resonant exit pair in the \fBDecay\fP vector\&. Used only for resonant external pathways\&. 
.PP
Definition at line \fB84\fP of file \fBECMGroup\&.cpp\fP\&.
.SS "int ECMGroup::GetChanCapKGroup () const"
Returns the resonant \fBKGroup\fP number\&. Used only for resonant external pathways\&. 
.PP
Definition at line \fB92\fP of file \fBECMGroup\&.cpp\fP\&.
.SS "int ECMGroup::GetChanCapMGroup () const"
Returns the resonant \fBMGroup\fP number\&. Used only for resonant external pathways\&. 
.PP
Definition at line \fB100\fP of file \fBECMGroup\&.cpp\fP\&.
.SS "int ECMGroup::GetFinalChannel () const"
Returns the final channel number for the pathway\&. 
.PP
Definition at line \fB60\fP of file \fBECMGroup\&.cpp\fP\&.
.SS "int ECMGroup::GetIntChannelNum () const"
Returns the corresponding internal channel for an external channel pathway\&. 
.PP
Definition at line \fB108\fP of file \fBECMGroup\&.cpp\fP\&.
.SS "double ECMGroup::GetJ () const"
Returns the initial spin value for the pathway\&. 
.PP
Definition at line \fB116\fP of file \fBECMGroup\&.cpp\fP\&.
.SS "int ECMGroup::GetJGroupNum () const"
Returns the position of the final state jGroup in the \fBJGroup\fP vector\&. 
.PP
Definition at line \fB68\fP of file \fBECMGroup\&.cpp\fP\&.
.SS "int ECMGroup::GetL () const"
Returns the initial orbital momentum value for the reaction pathway\&. 
.PP
Definition at line \fB52\fP of file \fBECMGroup\&.cpp\fP\&.
.SS "int ECMGroup::GetLevelNum () const"
Returns the position of the final state in the \fBALevel\fP vector\&. 
.PP
Definition at line \fB76\fP of file \fBECMGroup\&.cpp\fP\&.
.SS "int ECMGroup::GetMult () const"
Returns the multipolarity of the capture gamma\&. 
.PP
Definition at line \fB44\fP of file \fBECMGroup\&.cpp\fP\&.
.SS "char ECMGroup::GetRadType () const"
Returns the radiation type for the capture gamma\&. 
.PP
Definition at line \fB36\fP of file \fBECMGroup\&.cpp\fP\&.
.SS "double ECMGroup::GetStatSpinFactor () const"
Returns the statistical spin factor, $ g_J $, for the pathway\&. 
.PP
Definition at line \fB124\fP of file \fBECMGroup\&.cpp\fP\&.
.SS "bool ECMGroup::IsChannelCapture () const"
Returns true if the pathways is a resonant external pathway, otherwise returns false\&. 
.PP
Definition at line \fB28\fP of file \fBECMGroup\&.cpp\fP\&.
.SS "void ECMGroup::SetStatSpinFactor (double a)"
Sets the statistical spin factor, $ g_J $, for the pathway\&. 
.PP
Definition at line \fB132\fP of file \fBECMGroup\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
