.TH "EDataIterator" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EDataIterator \- An iterator class for an \fBEData\fP object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EDataIterator\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEDataIterator\fP (std::vector< \fBESegment\fP > *)"
.br
.ti -1c
.RI "\fBEDataIterator\fP (const \fBEDataIterator\fP &it)"
.br
.ti -1c
.RI "\fBEDataIterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBEDataIterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBEDataIterator\fP &)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBEDataIterator\fP &)"
.br
.ti -1c
.RI "\fBEDataIterator\fP & \fBSetEnd\fP ()"
.br
.ti -1c
.RI "\fBESegmentIterator\fP & \fBsegment\fP ()"
.br
.ti -1c
.RI "\fBEPointIterator\fP & \fBpoint\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
An iterator class for an \fBEData\fP object\&. 

The \fBEDataIterator\fP class is used to loop through all data segments and points contained in an \fBEData\fP object\&. 
.PP
Definition at line \fB20\fP of file \fBEDataIterator\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EDataIterator::EDataIterator (std::vector< \fBESegment\fP > * segments)"
The \fBEDataIterator\fP object is created with reference to a vector of \fBESegment\fP objects\&. 
.PP
Definition at line \fB9\fP of file \fBEDataIterator\&.cpp\fP\&.
.SS "EDataIterator::EDataIterator (const \fBEDataIterator\fP & it)"
The copy constructor creates a new \fBEDataIterator\fP object with reference to an already existing object\&. 
.PP
Definition at line \fB20\fP of file \fBEDataIterator\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool EDataIterator::operator!= (const \fBEDataIterator\fP & rhs)"
This function defines the boolean not-equal operator\&. 
.PP
Definition at line \fB62\fP of file \fBEDataIterator\&.cpp\fP\&.
.SS "\fBEDataIterator\fP & EDataIterator::operator++ ()"
This function defines the prefix version of the iterating operator\&. 
.PP
Definition at line \fB28\fP of file \fBEDataIterator\&.cpp\fP\&.
.SS "\fBEDataIterator\fP EDataIterator::operator++ (int)"
This function defines the postfix version of the iterating operator\&. 
.PP
Definition at line \fB44\fP of file \fBEDataIterator\&.cpp\fP\&.
.SS "bool EDataIterator::operator== (const \fBEDataIterator\fP & rhs)"
This function defines the boolean equal operator\&. 
.PP
Definition at line \fB54\fP of file \fBEDataIterator\&.cpp\fP\&.
.SS "\fBEPointIterator\fP & EDataIterator::point ()"
Returns a reference to the contained std::vector<EPoint>::iterator object\&. 
.PP
Definition at line \fB89\fP of file \fBEDataIterator\&.cpp\fP\&.
.SS "\fBESegmentIterator\fP & EDataIterator::segment ()"
Returns a reference to the contained std::vector<ESegment>::iterator object\&. 
.PP
Definition at line \fB81\fP of file \fBEDataIterator\&.cpp\fP\&.
.SS "\fBEDataIterator\fP & EDataIterator::SetEnd ()"
Sets the contained std::vector<ESegment>::iterator object to the refer to the last segment, and the contained std::vector<EData>::iterator object to refer to the default end() position (one-past)\&. 
.PP
Definition at line \fB71\fP of file \fBEDataIterator\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
