.TH "/Users/kuba/Desktop/R-Matrix/AZURE2/include/EDataIterator.h" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kuba/Desktop/R-Matrix/AZURE2/include/EDataIterator.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEDataIterator\fP"
.br
.RI "An iterator class for an \fBEData\fP object\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< \fBEPoint\fP >::iterator \fBEPointIterator\fP"
.br
.ti -1c
.RI "typedef std::vector< \fBEPoint\fP * >::iterator \fBEPointMapIterator\fP"
.br
.ti -1c
.RI "typedef std::vector< \fBESegment\fP >::iterator \fBESegmentIterator\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::vector<\fBEPoint\fP>::iterator \fBEPointIterator\fP"

.PP
Definition at line \fB9\fP of file \fBEDataIterator\&.h\fP\&.
.SS "typedef std::vector<\fBEPoint\fP*>::iterator \fBEPointMapIterator\fP"

.PP
Definition at line \fB10\fP of file \fBEDataIterator\&.h\fP\&.
.SS "typedef std::vector<\fBESegment\fP>::iterator \fBESegmentIterator\fP"

.PP
Definition at line \fB11\fP of file \fBEDataIterator\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
