.TH "/Users/kuba/Desktop/R-Matrix/AZURE2/gui/src/EditDirsDialog.cpp" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kuba/Desktop/R-Matrix/AZURE2/gui/src/EditDirsDialog.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QGroupBox>\fP
.br
\fC#include <QGridLayout>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <QHBoxLayout>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include 'EditDirsDialog\&.h'\fP
.br
\fC#include 'ChooseFileButton\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
