.TH "EditChecksDialog" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EditChecksDialog
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EditChecksDialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEditChecksDialog\fP (QWidget *parent=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QComboBox * \fBcompoundCheckCombo\fP"
.br
.ti -1c
.RI "QComboBox * \fBboundaryCheckCombo\fP"
.br
.ti -1c
.RI "QComboBox * \fBdataCheckCombo\fP"
.br
.ti -1c
.RI "QComboBox * \fBlMatrixCheckCombo\fP"
.br
.ti -1c
.RI "QComboBox * \fBlegendreCheckCombo\fP"
.br
.ti -1c
.RI "QComboBox * \fBcoulAmpCheckCombo\fP"
.br
.ti -1c
.RI "QComboBox * \fBpathwaysCheckCombo\fP"
.br
.ti -1c
.RI "QComboBox * \fBangDistsCheckCombo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBEditChecksDialog\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EditChecksDialog::EditChecksDialog (QWidget * parent = \fC0\fP)"

.PP
Definition at line \fB8\fP of file \fBEditChecksDialog\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "QComboBox* EditChecksDialog::angDistsCheckCombo"

.PP
Definition at line \fB27\fP of file \fBEditChecksDialog\&.h\fP\&.
.SS "QComboBox* EditChecksDialog::boundaryCheckCombo"

.PP
Definition at line \fB21\fP of file \fBEditChecksDialog\&.h\fP\&.
.SS "QComboBox* EditChecksDialog::compoundCheckCombo"

.PP
Definition at line \fB20\fP of file \fBEditChecksDialog\&.h\fP\&.
.SS "QComboBox* EditChecksDialog::coulAmpCheckCombo"

.PP
Definition at line \fB25\fP of file \fBEditChecksDialog\&.h\fP\&.
.SS "QComboBox* EditChecksDialog::dataCheckCombo"

.PP
Definition at line \fB22\fP of file \fBEditChecksDialog\&.h\fP\&.
.SS "QComboBox* EditChecksDialog::legendreCheckCombo"

.PP
Definition at line \fB24\fP of file \fBEditChecksDialog\&.h\fP\&.
.SS "QComboBox* EditChecksDialog::lMatrixCheckCombo"

.PP
Definition at line \fB23\fP of file \fBEditChecksDialog\&.h\fP\&.
.SS "QComboBox* EditChecksDialog::pathwaysCheckCombo"

.PP
Definition at line \fB26\fP of file \fBEditChecksDialog\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
