.TH "EditOptionsDialog" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EditOptionsDialog
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EditOptionsDialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEditOptionsDialog\fP (QWidget *parent=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QCheckBox * \fBuseBruneCheck\fP"
.br
.ti -1c
.RI "QCheckBox * \fBuseGSLCoulCheck\fP"
.br
.ti -1c
.RI "QCheckBox * \fBignoreExternalsCheck\fP"
.br
.ti -1c
.RI "QCheckBox * \fBuseRMCCheck\fP"
.br
.ti -1c
.RI "QCheckBox * \fBnoTransformCheck\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBEditOptionsDialog\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EditOptionsDialog::EditOptionsDialog (QWidget * parent = \fC0\fP)"

.PP
Definition at line \fB8\fP of file \fBEditOptionsDialog\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "QCheckBox* EditOptionsDialog::ignoreExternalsCheck"

.PP
Definition at line \fB25\fP of file \fBEditOptionsDialog\&.h\fP\&.
.SS "QCheckBox* EditOptionsDialog::noTransformCheck"

.PP
Definition at line \fB27\fP of file \fBEditOptionsDialog\&.h\fP\&.
.SS "QCheckBox* EditOptionsDialog::useBruneCheck"

.PP
Definition at line \fB23\fP of file \fBEditOptionsDialog\&.h\fP\&.
.SS "QCheckBox* EditOptionsDialog::useGSLCoulCheck"

.PP
Definition at line \fB24\fP of file \fBEditOptionsDialog\&.h\fP\&.
.SS "QCheckBox* EditOptionsDialog::useRMCCheck"

.PP
Definition at line \fB26\fP of file \fBEditOptionsDialog\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
