.TH "EffectiveCharge" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EffectiveCharge \- A function class for calculating effective charge without long-wavelength approximation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EffectiveCharge\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEffectiveCharge\fP (\fBPPair\fP *, double, int)"
.br
.ti -1c
.RI "double \fBoperator()\fP (double)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A function class for calculating effective charge without long-wavelength approximation\&. 

The \fBEffectiveCharge\fP class calculates the effective charge needed for external capture without using the long wavelength approximation\&. The formalism is based on J\&.L\&. Friar and S\&. Fallieros, Phys\&. Rev\&. C 29, 1645 (1984)\&. 
.PP
Definition at line \fB14\fP of file \fBEffectiveCharge\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EffectiveCharge::EffectiveCharge (\fBPPair\fP * pair, double energy, int L)"
The constructor takes a \fBPPair\fP object, gamma energy, and multipolarity as arguments\&. 
.PP
Definition at line \fB13\fP of file \fBEffectiveCharge\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "double EffectiveCharge::operator() (double r)"
The operator() function takes the radius as an argument, carries out integration, and returns the rho-dependent effective charge\&. 
.PP
Definition at line \fB28\fP of file \fBEffectiveCharge\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
