.TH "EnergyMap" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnergyMap \- A container structure for a reference to a data point\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EPoint\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsegment\fP"
.br
.RI "The segment index for the map\&. "
.ti -1c
.RI "int \fBpoint\fP"
.br
.RI "The point index for the map\&. "
.in -1c
.SH "Detailed Description"
.PP 
A container structure for a reference to a data point\&. 

If a point is mapped back to another in the calculation, this structure hold the relevant indices of the map point\&. 
.PP
Definition at line \fB13\fP of file \fBEPoint\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int EnergyMap::point"

.PP
The point index for the map\&. 
.PP
Definition at line \fB17\fP of file \fBEPoint\&.h\fP\&.
.SS "int EnergyMap::segment"

.PP
The segment index for the map\&. 
.PP
Definition at line \fB15\fP of file \fBEPoint\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
