.TH "/Users/kuba/Desktop/R-Matrix/AZURE2/src/EPoint.cpp" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kuba/Desktop/R-Matrix/AZURE2/src/EPoint.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'AMatrixFunc\&.h'\fP
.br
\fC#include 'AngCoeff\&.h'\fP
.br
\fC#include 'CNuc\&.h'\fP
.br
\fC#include 'Config\&.h'\fP
.br
\fC#include 'CoulFunc\&.h'\fP
.br
\fC#include 'DataLine\&.h'\fP
.br
\fC#include 'ECIntegral\&.h'\fP
.br
\fC#include 'EData\&.h'\fP
.br
\fC#include 'ESegment\&.h'\fP
.br
\fC#include 'RMatrixFunc\&.h'\fP
.br
\fC#include 'ShftFunc\&.h'\fP
.br
\fC#include 'TargetEffect\&.h'\fP
.br
\fC#include 'IntegratedFermiFunc\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <assert\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
