.TH "/Users/kuba/Desktop/R-Matrix/AZURE2/src/ESegment.cpp" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kuba/Desktop/R-Matrix/AZURE2/src/ESegment.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'CNuc\&.h'\fP
.br
\fC#include 'DataLine\&.h'\fP
.br
\fC#include 'EData\&.h'\fP
.br
\fC#include 'ESegment\&.h'\fP
.br
\fC#include 'ExtrapLine\&.h'\fP
.br
\fC#include 'SegLine\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
