.TH "GenericFunction" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericFunction \- A wrapper class for function pointers used by \fBEquation\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Equation\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenericFunction\fP ()"
.br
.ti -1c
.RI "\fBGenericFunction\fP (double(*function)(double))"
.br
.ti -1c
.RI "double \fBEvaluate\fP (double value) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
A wrapper class for function pointers used by \fBEquation\fP class\&. 

The \fBGenericFunction\fP class is just a wrapper for a function pointer to a function of the form double function(double)\&. 
.PP
Definition at line \fB19\fP of file \fBEquation\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GenericFunction::GenericFunction ()\fC [inline]\fP"
The default constructor for the class\&. 
.PP
Definition at line \fB24\fP of file \fBEquation\&.h\fP\&.
.SS "GenericFunction::GenericFunction (double(*)(double) function)\fC [inline]\fP"
Constructs the object from a function pointer\&. 
.PP
Definition at line \fB28\fP of file \fBEquation\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "double GenericFunction::Evaluate (double value) const\fC [inline]\fP"
Evaluates the function object with a given double\&. 
.PP
Definition at line \fB33\fP of file \fBEquation\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
