.TH "GenMatrixFunc" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenMatrixFunc \- A generalized function class to calculate cross sections\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GenMatrixFunc\&.h>\fP
.PP
Inherited by \fBAMatrixFunc\fP, and \fBRMatrixFunc\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenMatrixFunc\fP ()"
.br
.ti -1c
.RI "virtual \fB~GenMatrixFunc\fP ()"
.br
.ti -1c
.RI "virtual void \fBClearMatrices\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBFillMatrices\fP (\fBEPoint\fP *)=0"
.br
.ti -1c
.RI "virtual void \fBInvertMatrices\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBCalculateTMatrix\fP (\fBEPoint\fP *)=0"
.br
.ti -1c
.RI "void \fBCalculateCrossSection\fP (\fBEPoint\fP *)"
.br
.ti -1c
.RI "void \fBNewTempTMatrix\fP (\fBTempTMatrix\fP)"
.br
.ti -1c
.RI "void \fBAddToTempTMatrix\fP (int, \fBcomplex\fP)"
.br
.ti -1c
.RI "void \fBClearTempTMatrices\fP ()"
.br
.ti -1c
.RI "void \fBAddTMatrixElement\fP (int, int, \fBcomplex\fP, int decayNum=1)"
.br
.ti -1c
.RI "void \fBAddECTMatrixElement\fP (int, int, \fBcomplex\fP)"
.br
.ti -1c
.RI "int \fBIsTempTMatrix\fP (double, int, int)"
.br
.ti -1c
.RI "int \fBNumTempTMatrices\fP () const"
.br
.ti -1c
.RI "\fBTempTMatrix\fP * \fBGetTempTMatrix\fP (int)"
.br
.ti -1c
.RI "\fBcomplex\fP \fBGetTMatrixElement\fP (int, int, int decayNum=1) const"
.br
.ti -1c
.RI "\fBcomplex\fP \fBGetECTMatrixElement\fP (int, int) const"
.br
.ti -1c
.RI "virtual \fBCNuc\fP * \fBcompound\fP () const =0"
.br
.ti -1c
.RI "virtual const \fBConfig\fP & \fBconfigure\fP () const =0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBmatrix_c\fP > \fBtmatrix_\fP"
.br
.RI "Vector of internal T-matrix elements accessable to child class\&. "
.ti -1c
.RI "\fBmatrix_c\fP \fBec_tmatrix_\fP"
.br
.RI "Vector of external T-matrix elements accessable to child class\&. "
.in -1c
.SH "Detailed Description"
.PP 
A generalized function class to calculate cross sections\&. 

The \fBGenMatrixFunc\fP function class is the general form of the function used to calculate cross section from R-Matrix parameters\&. It is the parent class of \fBAMatrixFunc\fP and \fBRMatrixFunc\fP\&. 
.PP
Definition at line \fB38\fP of file \fBGenMatrixFunc\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GenMatrixFunc::GenMatrixFunc ()\fC [inline]\fP"

.PP
Definition at line \fB40\fP of file \fBGenMatrixFunc\&.h\fP\&.
.SS "virtual GenMatrixFunc::~GenMatrixFunc ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB41\fP of file \fBGenMatrixFunc\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void GenMatrixFunc::AddECTMatrixElement (int kGroupNum, int mGroupNum, \fBcomplex\fP tMatrixElement)"
Adds an external T-Matrix element to the vector of external T-matrix elements corresponding to a specified external reaction pathway\&. 
.PP
Definition at line \fB249\fP of file \fBGenMatrixFunc\&.cpp\fP\&.
.SS "void GenMatrixFunc::AddTMatrixElement (int kGroupNum, int mGroupNum, \fBcomplex\fP tMatrixElement, int decayNum = \fC1\fP)"
Adds an internal T-Matrix element to the vector of internal T-matrix elements corresponding to a specified internal reaction pathway\&. 
.PP
Definition at line \fB234\fP of file \fBGenMatrixFunc\&.cpp\fP\&.
.SS "void GenMatrixFunc::AddToTempTMatrix (int tempTMatrixNum, \fBcomplex\fP tempValue)"
Adds a value to the temporary T-Matrix element specified by its position in the \fBTempTMatrix\fP vector\&. 
.PP
Definition at line \fB216\fP of file \fBGenMatrixFunc\&.cpp\fP\&.
.SS "void GenMatrixFunc::CalculateCrossSection (\fBEPoint\fP * point)"
The child classes \fBAMatrixFunc\fP or \fBRMatrixFunc\fP contain functions to calculate the T-Matrix from the fitted R-Matrix parameters\&. This function then calculates the cross section from the T-Matrix elements\&. 
.PP
Definition at line \fB12\fP of file \fBGenMatrixFunc\&.cpp\fP\&.
.SS "virtual void GenMatrixFunc::CalculateTMatrix (\fBEPoint\fP *)\fC [pure virtual]\fP"
This virtual function in implemented in the child class\&. 
.PP
Implemented in \fBAMatrixFunc\fP, and \fBRMatrixFunc\fP\&.
.SS "virtual void GenMatrixFunc::ClearMatrices ()\fC [pure virtual]\fP"
This virtual function in implemented in the child class\&. 
.PP
Implemented in \fBAMatrixFunc\fP, and \fBRMatrixFunc\fP\&.
.SS "void GenMatrixFunc::ClearTempTMatrices ()"
Clears the temporary T-Matrices\&. 
.PP
Definition at line \fB225\fP of file \fBGenMatrixFunc\&.cpp\fP\&.
.SS "virtual \fBCNuc\fP * GenMatrixFunc::compound () const\fC [pure virtual]\fP"
This virtual function in implemented in the child class\&. 
.PP
Implemented in \fBAMatrixFunc\fP, and \fBRMatrixFunc\fP\&.
.SS "virtual const \fBConfig\fP & GenMatrixFunc::configure () const\fC [pure virtual]\fP"
This virtual function in implemented in the child class\&. 
.PP
Implemented in \fBAMatrixFunc\fP, and \fBRMatrixFunc\fP\&.
.SS "virtual void GenMatrixFunc::FillMatrices (\fBEPoint\fP *)\fC [pure virtual]\fP"
This virtual function in implemented in the child class\&. 
.PP
Implemented in \fBAMatrixFunc\fP, and \fBRMatrixFunc\fP\&.
.SS "\fBcomplex\fP GenMatrixFunc::GetECTMatrixElement (int kGroupNum, int ecMGroupNum) const"
Returns the value of the external T-Matrix element specified by an external reaction pathway\&. 
.PP
Definition at line \fB303\fP of file \fBGenMatrixFunc\&.cpp\fP\&.
.SS "\fBTempTMatrix\fP * GenMatrixFunc::GetTempTMatrix (int tempTMatrixNum)"
Returns a pointer to the temporary T-Matrix element specified by a position in the \fBTempTMatrix\fP vector\&. 
.PP
Definition at line \fB286\fP of file \fBGenMatrixFunc\&.cpp\fP\&.
.SS "\fBcomplex\fP GenMatrixFunc::GetTMatrixElement (int kGroupNum, int mGroupNum, int decayNum = \fC1\fP) const"
Returns the value of the internal T-Matrix element specified by an internal reaction pathway\&. 
.PP
Definition at line \fB295\fP of file \fBGenMatrixFunc\&.cpp\fP\&.
.SS "virtual void GenMatrixFunc::InvertMatrices ()\fC [pure virtual]\fP"
This virtual function in implemented in the child class\&. 
.PP
Implemented in \fBAMatrixFunc\fP, and \fBRMatrixFunc\fP\&.
.SS "int GenMatrixFunc::IsTempTMatrix (double jValue, int lValue, int lPrimeValue)"
Tests if a temporary T-Matrix element already exists for a given $ J,l,l' $ combination\&. If the element exists, returns the position in the \fBTempTMatrix\fP vector, otherwise returns 0\&. 
.PP
Definition at line \fB261\fP of file \fBGenMatrixFunc\&.cpp\fP\&.
.SS "void GenMatrixFunc::NewTempTMatrix (\fBTempTMatrix\fP tempTMatrix)"
Creates a new temporary T-Matrix element\&. 
.PP
Definition at line \fB208\fP of file \fBGenMatrixFunc\&.cpp\fP\&.
.SS "int GenMatrixFunc::NumTempTMatrices () const"
Returns the number of temporary T-Matrix elements in the \fBTempTMatrix\fP vector\&. 
.PP
Definition at line \fB278\fP of file \fBGenMatrixFunc\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmatrix_c\fP GenMatrixFunc::ec_tmatrix_\fC [protected]\fP"

.PP
Vector of external T-matrix elements accessable to child class\&. 
.PP
Definition at line \fB82\fP of file \fBGenMatrixFunc\&.h\fP\&.
.SS "std::vector<\fBmatrix_c\fP> GenMatrixFunc::tmatrix_\fC [protected]\fP"

.PP
Vector of internal T-matrix elements accessable to child class\&. 
.PP
Definition at line \fB80\fP of file \fBGenMatrixFunc\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
