.TH "gsl_reactionrate_params" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gsl_reactionrate_params
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgsl_reactionrate_params\fP (const \fBConfig\fP &config)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBConfig\fP & \fBconfigure\fP"
.br
.ti -1c
.RI "double \fBtemperature\fP"
.br
.ti -1c
.RI "\fBCNuc\fP * \fBcompound\fP"
.br
.ti -1c
.RI "int \fBentranceKey\fP"
.br
.ti -1c
.RI "int \fBexitKey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBReactionRate\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gsl_reactionrate_params::gsl_reactionrate_params (const \fBConfig\fP & config)\fC [inline]\fP"

.PP
Definition at line \fB14\fP of file \fBReactionRate\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCNuc\fP* gsl_reactionrate_params::compound"

.PP
Definition at line \fB17\fP of file \fBReactionRate\&.cpp\fP\&.
.SS "const \fBConfig\fP& gsl_reactionrate_params::configure"

.PP
Definition at line \fB15\fP of file \fBReactionRate\&.cpp\fP\&.
.SS "int gsl_reactionrate_params::entranceKey"

.PP
Definition at line \fB18\fP of file \fBReactionRate\&.cpp\fP\&.
.SS "int gsl_reactionrate_params::exitKey"

.PP
Definition at line \fB19\fP of file \fBReactionRate\&.cpp\fP\&.
.SS "double gsl_reactionrate_params::temperature"

.PP
Definition at line \fB16\fP of file \fBReactionRate\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
