.TH "GSLException" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GSLException
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GSLException\&.h>\fP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGSLException\fP (std::string message, std::string line='', std::string file='')"
.br
.ti -1c
.RI "\fB~GSLException\fP ()  throw ()"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const  throw ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBGSLErrorHandler\fP (const char *, const char *, int, int)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBGSLException\fP class is an exception class thrown by the \fBCoulFunc\fP class\&. It should not be used directly\&. 
.PP
Definition at line \fB13\fP of file \fBGSLException\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GSLException::GSLException (std::string message, std::string line = \fC''\fP, std::string file = \fC''\fP)\fC [inline]\fP"

.PP
Definition at line \fB15\fP of file \fBGSLException\&.h\fP\&.
.SS "GSLException::~GSLException ()\fC [inline]\fP"

.PP
Definition at line \fB27\fP of file \fBGSLException\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void GSLException::GSLErrorHandler (const char * reason, const char * file, int line, int errorCode)\fC [static]\fP"

.PP
Definition at line \fB4\fP of file \fBGSLException\&.cpp\fP\&.
.SS "virtual const char * GSLException::what () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB29\fP of file \fBGSLException\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
