.TH "/Users/kuba/Desktop/R-Matrix/AZURE2/gui/src/InTabDocs.cpp" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kuba/Desktop/R-Matrix/AZURE2/gui/src/InTabDocs.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'PairsTab\&.h'\fP
.br
\fC#include 'LevelsTab\&.h'\fP
.br
\fC#include 'SegmentsTab\&.h'\fP
.br
\fC#include 'TargetIntTab\&.h'\fP
.br
\fC#include 'RunTab\&.h'\fP
.br
\fC#include 'PlotTab\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< QString > \fBsetInfoStrings\fP (QString infoString1='', QString infoString2='', QString infoString3='', QString infoString4='', QString infoString5='')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::vector< QString > setInfoStrings (QString infoString1 = \fC''\fP, QString infoString2 = \fC''\fP, QString infoString3 = \fC''\fP, QString infoString4 = \fC''\fP, QString infoString5 = \fC''\fP)"

.PP
Definition at line \fB8\fP of file \fBInTabDocs\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
