.TH "Interference" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interference \- An AZURE $ l_1,l_2,l_1',l_2',J_1,J_2 $ combination\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Interference\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInterference\fP (int, int, double, std::string)"
.br
.ti -1c
.RI "std::string \fBGetInterferenceType\fP () const"
.br
.ti -1c
.RI "int \fBGetM1\fP () const"
.br
.ti -1c
.RI "int \fBGetM2\fP () const"
.br
.ti -1c
.RI "double \fBGetZ1Z2\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
An AZURE $ l_1,l_2,l_1',l_2',J_1,J_2 $ combination\&. 

In the differential cross section formula of R-Matrix, nested inside the $ s,s',L $ sum is a sum over $ l_1,l_2,l_1',l_2',J_1,J_2 $\&. In the language of AZURE, these are equivalent to combinations of two reaction pathways\&. If the pathways are the same, the term represents the actual contribution from the pathway to the cross section\&. If they are different, the term represents the interference between the two\&. 
.PP
Definition at line \fB16\fP of file \fBInterference\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Interference::Interference (int mGroupNum1, int mGroupNum2, double z1z2Coeff, std::string interferenceType)"
The pathways combination is created specifically using references to two positions in the \fBMGroup\fP and \fBECMGroup\fP vectors under the corresponding \fBKGroup\fP object\&. Additionally, the $ Z_1 Z_2 $ coefficients are passed along with the interference type\&. The interference type is either RR, ER, RE,or EE, indicating which vector, the \fBMGroup\fP or \fBECMGroup\fP, the stored indices refer to\&. 
.PP
Definition at line \fB11\fP of file \fBInterference\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string Interference::GetInterferenceType () const"
Returns the interference type\&. 
.PP
Definition at line \fB18\fP of file \fBInterference\&.cpp\fP\&.
.SS "int Interference::GetM1 () const"
Returns the position in the \fBMGroup\fP or \fBECMGroup\fP vector of the first pathway\&. 
.PP
Definition at line \fB26\fP of file \fBInterference\&.cpp\fP\&.
.SS "int Interference::GetM2 () const"
Returns the position in the \fBMGroup\fP or \fBECMGroup\fP vector of the second pathway\&. 
.PP
Definition at line \fB34\fP of file \fBInterference\&.cpp\fP\&.
.SS "double Interference::GetZ1Z2 () const"
Returns the corresponding $ Z_1 Z_2 $ coefficient\&. 
.PP
Definition at line \fB42\fP of file \fBInterference\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
