.TH "/Users/kuba/Desktop/R-Matrix/AZURE2/include/IntegratedFermiFunc.h" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kuba/Desktop/R-Matrix/AZURE2/include/IntegratedFermiFunc.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIntegratedFermiFunc\fP"
.br
.RI "A function class to calculate the integrated Fermi function for beta decay\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
