.TH "IntegratedFermiFunc" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IntegratedFermiFunc \- A function class to calculate the integrated Fermi function for beta decay\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IntegratedFermiFunc\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntegratedFermiFunc\fP (int, double V0=0\&.)"
.br
.ti -1c
.RI "double \fBoperator()\fP (double, double, double)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A function class to calculate the integrated Fermi function for beta decay\&. 

This function class calculates the integrated Fermi function for beta decay channels\&. The integrand is taken directly from Konopinski and Rose\&. While screening potentials can be added, by default the screening potential is set to zero\&. This function class should be valid for either electron or positron emission\&. 
.br
 
.PP
Definition at line \fB13\fP of file \fBIntegratedFermiFunc\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IntegratedFermiFunc::IntegratedFermiFunc (int charge, double V0 = \fC0\&.\fP)"
The constructor for the function takes the charge of the Fermion as the first argument\&. This is expected to be either -1 or 1 for electrons and positrons, respectively\&. The second optional argument is the screening potential $V_0$, where the actual screening potential, $V$, will be calculated as $V = V_0 \alpha^2 Z^{4/3}$\&. 
.PP
Definition at line \fB19\fP of file \fBIntegratedFermiFunc\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "double IntegratedFermiFunc::operator() (double W0, double Z, double radius)"
The calling operator for the function class takes the end point energy (in units of $m_0c^2$), the charge of the daughter nucleus, and the nuclear radius parameter as arguments\&. The return value is the integrated Fermi function\&. 
.PP
Definition at line \fB29\fP of file \fBIntegratedFermiFunc\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
