.TH "KGroup" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KGroup \- An AZURE $ s,s' $ group\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <KGroup\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKGroup\fP (double, double)"
.br
.ti -1c
.RI "int \fBNumMGroups\fP () const"
.br
.ti -1c
.RI "int \fBNumECMGroups\fP () const"
.br
.ti -1c
.RI "int \fBIsMGroup\fP (\fBMGroup\fP)"
.br
.ti -1c
.RI "double \fBGetS\fP () const"
.br
.ti -1c
.RI "double \fBGetSp\fP () const"
.br
.ti -1c
.RI "void \fBAddMGroup\fP (\fBMGroup\fP)"
.br
.ti -1c
.RI "void \fBAddECMGroup\fP (\fBECMGroup\fP)"
.br
.ti -1c
.RI "\fBMGroup\fP * \fBGetMGroup\fP (int)"
.br
.ti -1c
.RI "\fBECMGroup\fP * \fBGetECMGroup\fP (int)"
.br
.in -1c
.SH "Detailed Description"
.PP 
An AZURE $ s,s' $ group\&. 

In R-Matrix formalism, the equations required to calculate the cross section usually nested inside sums over entrance and exit channel spins\&. For this reason AZURE groups reaction pathways according to their entrance and exit channel spins\&. Each \fBKGroup\fP object is a container for vectors of \fBMGroup\fP and \fBECMGroup\fP objects\&. 
.br
 
.PP
Definition at line \fB16\fP of file \fBKGroup\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "KGroup::KGroup (double s, double sPrime)"
The \fBKGroup\fP is created from a specific combination of entrance and exit channel spin values\&. 
.PP
Definition at line \fB7\fP of file \fBKGroup\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void KGroup::AddECMGroup (\fBECMGroup\fP ecMGroup)"
Adds a new external reaction pathway to the \fBECMGroup\fP vector\&. 
.PP
Definition at line \fB74\fP of file \fBKGroup\&.cpp\fP\&.
.SS "void KGroup::AddMGroup (\fBMGroup\fP mGroup)"
Adds a new internal reaction pathway to the \fBMGroup\fP vector\&. 
.PP
Definition at line \fB66\fP of file \fBKGroup\&.cpp\fP\&.
.SS "\fBECMGroup\fP * KGroup::GetECMGroup (int ecMGroupNum)"
Returns a pointer to the external reaction pathway specified by a position in the \fBECMGroup\fP vector\&. 
.PP
Definition at line \fB90\fP of file \fBKGroup\&.cpp\fP\&.
.SS "\fBMGroup\fP * KGroup::GetMGroup (int mGroupNum)"
Returns a pointer to the internal reaction pathway specified by a position in the \fBMGroup\fP vector\&. 
.PP
Definition at line \fB82\fP of file \fBKGroup\&.cpp\fP\&.
.SS "double KGroup::GetS () const"
Returns the value of the entrance channel spin\&. 
.PP
Definition at line \fB50\fP of file \fBKGroup\&.cpp\fP\&.
.SS "double KGroup::GetSp () const"
Returns the value of the exit channel spin\&. 
.PP
Definition at line \fB58\fP of file \fBKGroup\&.cpp\fP\&.
.SS "int KGroup::IsMGroup (\fBMGroup\fP mGroup)"
Tests a specific internal reaction pathway to see if it already exists in the \fBMGroup\fP vector\&. If the pathway exists, its position in the vector is returned\&. Otherwise, the function returns 0\&. 
.PP
Definition at line \fB32\fP of file \fBKGroup\&.cpp\fP\&.
.SS "int KGroup::NumECMGroups () const"
Returns the number of external reaction pathways in the \fBECMGroup\fP vector; 
.PP
Definition at line \fB22\fP of file \fBKGroup\&.cpp\fP\&.
.SS "int KGroup::NumMGroups () const"
Returns the number of internal reaction pathways in the \fBMGroup\fP vector\&. 
.PP
Definition at line \fB14\fP of file \fBKGroup\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
