.TH "/Users/kuba/Desktop/R-Matrix/AZURE2/gui/src/LevelsTab.cpp" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kuba/Desktop/R-Matrix/AZURE2/gui/src/LevelsTab.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QHeaderView>\fP
.br
\fC#include 'LevelsTab\&.h'\fP
.br
\fC#include 'LevelsHeaderView\&.h'\fP
.br
\fC#include 'AddLevelDialog\&.h'\fP
.br
\fC#include 'RichTextDelegate\&.h'\fP
.br
\fC#include 'InfoDialog\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
