.TH "LevelsTab" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LevelsTab
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LevelsTab\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBaddLevel\fP ()"
.br
.ti -1c
.RI "void \fBaddLevel\fP (\fBLevelsData\fP level, bool fromFile)"
.br
.ti -1c
.RI "void \fBremoveLevel\fP ()"
.br
.ti -1c
.RI "void \fBeditLevel\fP ()"
.br
.ti -1c
.RI "void \fBupdateButtons\fP (const QItemSelection &selection)"
.br
.ti -1c
.RI "void \fBupdateFilter\fP (const QItemSelection &selection)"
.br
.ti -1c
.RI "void \fBupdateChannelsPairAddedEdited\fP ()"
.br
.ti -1c
.RI "void \fBupdateChannelsPairRemoved\fP (int pairIndex)"
.br
.ti -1c
.RI "void \fBupdateDetails\fP (const QItemSelection &selection)"
.br
.ti -1c
.RI "void \fBupdateReducedWidth\fP (const QString &string)"
.br
.ti -1c
.RI "void \fBshowInfo\fP (int which=0, QString title='')"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBreadNewPair\fP (\fBPairsData\fP, int, bool)"
.br
.ti -1c
.RI "void \fBreadExistingPair\fP (\fBPairsData\fP, int, bool)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLevelsTab\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetPairsModel\fP (\fBPairsModel\fP *)"
.br
.ti -1c
.RI "void \fBupdateChannelsLevelAdded\fP (int levelIndex)"
.br
.ti -1c
.RI "void \fBupdateChannelsLevelDeleted\fP (int levelIndex)"
.br
.ti -1c
.RI "void \fBupdateChannelsLevelEdited\fP (int levelIndex)"
.br
.ti -1c
.RI "QList< \fBChannelsData\fP > \fBcalculateChannels\fP (int levelIndex)"
.br
.ti -1c
.RI "bool \fBwriteNuclearFile\fP (QTextStream &outStream)"
.br
.ti -1c
.RI "bool \fBreadNuclearFile\fP (QTextStream &inStream)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB20\fP of file \fBLevelsTab\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LevelsTab::LevelsTab (QWidget * parent = \fC0\fP)"

.PP
Definition at line \fB10\fP of file \fBLevelsTab\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void LevelsTab::addLevel ()\fC [slot]\fP"

.PP
Definition at line \fB185\fP of file \fBLevelsTab\&.cpp\fP\&.
.SS "void LevelsTab::addLevel (\fBLevelsData\fP level, bool fromFile)\fC [slot]\fP"

.PP
Definition at line \fB199\fP of file \fBLevelsTab\&.cpp\fP\&.
.SS "QList< \fBChannelsData\fP > LevelsTab::calculateChannels (int levelIndex)"

.PP
Definition at line \fB365\fP of file \fBLevelsTab\&.cpp\fP\&.
.SS "void LevelsTab::editLevel ()\fC [slot]\fP"

.PP
Definition at line \fB230\fP of file \fBLevelsTab\&.cpp\fP\&.
.SS "void LevelsTab::readExistingPair (\fBPairsData\fP, int, bool)\fC [signal]\fP"

.SS "void LevelsTab::readNewPair (\fBPairsData\fP, int, bool)\fC [signal]\fP"

.SS "bool LevelsTab::readNuclearFile (QTextStream & inStream)"

.PP
Definition at line \fB680\fP of file \fBLevelsTab\&.cpp\fP\&.
.SS "void LevelsTab::removeLevel ()\fC [slot]\fP"

.PP
Definition at line \fB220\fP of file \fBLevelsTab\&.cpp\fP\&.
.SS "void LevelsTab::reset ()"

.PP
Definition at line \fB818\fP of file \fBLevelsTab\&.cpp\fP\&.
.SS "void LevelsTab::setPairsModel (\fBPairsModel\fP * model)"

.PP
Definition at line \fB180\fP of file \fBLevelsTab\&.cpp\fP\&.
.SS "void LevelsTab::showInfo (int which = \fC0\fP, QString title = \fC''\fP)\fC [slot]\fP"

.PP
Definition at line \fB833\fP of file \fBLevelsTab\&.cpp\fP\&.
.SS "void LevelsTab::updateButtons (const QItemSelection & selection)\fC [slot]\fP"

.PP
Definition at line \fB274\fP of file \fBLevelsTab\&.cpp\fP\&.
.SS "void LevelsTab::updateChannelsLevelAdded (int levelIndex)"

.PP
Definition at line \fB284\fP of file \fBLevelsTab\&.cpp\fP\&.
.SS "void LevelsTab::updateChannelsLevelDeleted (int levelIndex)"

.PP
Definition at line \fB306\fP of file \fBLevelsTab\&.cpp\fP\&.
.SS "void LevelsTab::updateChannelsLevelEdited (int levelIndex)"

.PP
Definition at line \fB324\fP of file \fBLevelsTab\&.cpp\fP\&.
.SS "void LevelsTab::updateChannelsPairAddedEdited ()\fC [slot]\fP"

.PP
Definition at line \fB430\fP of file \fBLevelsTab\&.cpp\fP\&.
.SS "void LevelsTab::updateChannelsPairRemoved (int pairIndex)\fC [slot]\fP"

.PP
Definition at line \fB468\fP of file \fBLevelsTab\&.cpp\fP\&.
.SS "void LevelsTab::updateDetails (const QItemSelection & selection)\fC [slot]\fP"

.PP
Definition at line \fB487\fP of file \fBLevelsTab\&.cpp\fP\&.
.SS "void LevelsTab::updateFilter (const QItemSelection & selection)\fC [slot]\fP"

.PP
Definition at line \fB418\fP of file \fBLevelsTab\&.cpp\fP\&.
.SS "void LevelsTab::updateReducedWidth (const QString & string)\fC [slot]\fP"

.PP
Definition at line \fB573\fP of file \fBLevelsTab\&.cpp\fP\&.
.SS "bool LevelsTab::writeNuclearFile (QTextStream & outStream)"

.PP
Definition at line \fB584\fP of file \fBLevelsTab\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
