.TH "LevelsHeaderView" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LevelsHeaderView
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LevelsHeaderView\&.h>\fP
.PP
Inherits QHeaderView\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLevelsHeaderView\fP (Qt::Orientation orientation, QWidget *parent)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBmouseMoveEvent\fP (QMouseEvent *e)"
.br
.ti -1c
.RI "virtual void \fBmousePressEvent\fP (QMouseEvent *e)"
.br
.ti -1c
.RI "virtual void \fBmouseReleaseEvent\fP (QMouseEvent *e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBLevelsHeaderView\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LevelsHeaderView::LevelsHeaderView (Qt::Orientation orientation, QWidget * parent)\fC [inline]\fP"

.PP
Definition at line \fB9\fP of file \fBLevelsHeaderView\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void LevelsHeaderView::mouseMoveEvent (QMouseEvent * e)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB14\fP of file \fBLevelsHeaderView\&.h\fP\&.
.SS "virtual void LevelsHeaderView::mousePressEvent (QMouseEvent * e)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB19\fP of file \fBLevelsHeaderView\&.h\fP\&.
.SS "virtual void LevelsHeaderView::mouseReleaseEvent (QMouseEvent * e)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB24\fP of file \fBLevelsHeaderView\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
