.TH "LevelsModel" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LevelsModel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LevelsModel\&.h>\fP
.PP
Inherits QAbstractTableModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLevelsModel\fP (QObject *parent=0)"
.br
.ti -1c
.RI "int \fBrowCount\fP (const QModelIndex &parent) const"
.br
.ti -1c
.RI "int \fBcolumnCount\fP (const QModelIndex &parent) const"
.br
.ti -1c
.RI "QVariant \fBdata\fP (const QModelIndex &index, int role) const"
.br
.ti -1c
.RI "QVariant \fBheaderData\fP (int section, Qt::Orientation orientation, int role) const"
.br
.ti -1c
.RI "bool \fBsetData\fP (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)"
.br
.ti -1c
.RI "bool \fBinsertRows\fP (int position, int rows, const QModelIndex &index=QModelIndex())"
.br
.ti -1c
.RI "bool \fBremoveRows\fP (int position, int rows, const QModelIndex &index=QModelIndex())"
.br
.ti -1c
.RI "Qt::ItemFlags \fBflags\fP (const QModelIndex &index) const"
.br
.ti -1c
.RI "int \fBisLevel\fP (const \fBLevelsData\fP &level) const"
.br
.ti -1c
.RI "QList< \fBLevelsData\fP > \fBgetLevels\fP () const"
.br
.ti -1c
.RI "QString \fBgetSpinLabel\fP (const \fBLevelsData\fP &level) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBLevelsModel\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LevelsModel::LevelsModel (QObject * parent = \fC0\fP)"

.PP
Definition at line \fB3\fP of file \fBLevelsModel\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int LevelsModel::columnCount (const QModelIndex & parent) const"

.PP
Definition at line \fB11\fP of file \fBLevelsModel\&.cpp\fP\&.
.SS "QVariant LevelsModel::data (const QModelIndex & index, int role) const"

.PP
Definition at line \fB16\fP of file \fBLevelsModel\&.cpp\fP\&.
.SS "Qt::ItemFlags LevelsModel::flags (const QModelIndex & index) const"

.PP
Definition at line \fB127\fP of file \fBLevelsModel\&.cpp\fP\&.
.SS "QList< \fBLevelsData\fP > LevelsModel::getLevels () const\fC [inline]\fP"

.PP
Definition at line \fB31\fP of file \fBLevelsModel\&.h\fP\&.
.SS "QString LevelsModel::getSpinLabel (const \fBLevelsData\fP & level) const"

.PP
Definition at line \fB147\fP of file \fBLevelsModel\&.cpp\fP\&.
.SS "QVariant LevelsModel::headerData (int section, Qt::Orientation orientation, int role) const"

.PP
Definition at line \fB45\fP of file \fBLevelsModel\&.cpp\fP\&.
.SS "bool LevelsModel::insertRows (int position, int rows, const QModelIndex & index = \fCQModelIndex()\fP)"

.PP
Definition at line \fB102\fP of file \fBLevelsModel\&.cpp\fP\&.
.SS "int LevelsModel::isLevel (const \fBLevelsData\fP & level) const"

.PP
Definition at line \fB133\fP of file \fBLevelsModel\&.cpp\fP\&.
.SS "bool LevelsModel::removeRows (int position, int rows, const QModelIndex & index = \fCQModelIndex()\fP)"

.PP
Definition at line \fB115\fP of file \fBLevelsModel\&.cpp\fP\&.
.SS "int LevelsModel::rowCount (const QModelIndex & parent) const"

.PP
Definition at line \fB6\fP of file \fBLevelsModel\&.cpp\fP\&.
.SS "bool LevelsModel::setData (const QModelIndex & index, const QVariant & value, int role = \fCQt::EditRole\fP)"

.PP
Definition at line \fB68\fP of file \fBLevelsModel\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
