.TH "LevelsData" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LevelsData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LevelsModel\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBisActive\fP"
.br
.ti -1c
.RI "int \fBisFixed\fP"
.br
.ti -1c
.RI "double \fBjValue\fP"
.br
.ti -1c
.RI "int \fBpiValue\fP"
.br
.ti -1c
.RI "double \fBenergy\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBSIZE\fP = 5"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBLevelsModel\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double LevelsData::energy"

.PP
Definition at line \fB13\fP of file \fBLevelsModel\&.h\fP\&.
.SS "int LevelsData::isActive"

.PP
Definition at line \fB9\fP of file \fBLevelsModel\&.h\fP\&.
.SS "int LevelsData::isFixed"

.PP
Definition at line \fB10\fP of file \fBLevelsModel\&.h\fP\&.
.SS "double LevelsData::jValue"

.PP
Definition at line \fB11\fP of file \fBLevelsModel\&.h\fP\&.
.SS "int LevelsData::piValue"

.PP
Definition at line \fB12\fP of file \fBLevelsModel\&.h\fP\&.
.SS "const int LevelsData::SIZE = 5\fC [static]\fP"

.PP
Definition at line \fB8\fP of file \fBLevelsModel\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
