.TH "MatrixInv" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MatrixInv \- A Function class to perform matrix inversion\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MatrixInv\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatrixInv\fP (const \fBmatrix_c\fP &)"
.br
.ti -1c
.RI "const \fBmatrix_c\fP & \fBinverse\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
A Function class to perform matrix inversion\&. 

The \fBMatrixInv\fP class is a function class for matrix inversion using the GSL functions\&. 
.PP
Definition at line \fB12\fP of file \fBMatrixInv\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MatrixInv::MatrixInv (const \fBmatrix_c\fP & A)"
The \fBMatrixInv\fP constructor takes a complex matrix as an argument and stores the inverse in a private member variable accessable by the \fBMatrixInv::inverse()\fP function\&. 
.PP
Definition at line \fB11\fP of file \fBMatrixInv\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "const \fBmatrix_c\fP & MatrixInv::inverse () const\fC [inline]\fP"
The function returns the inverse as calculated by the constructor\&. 
.PP
Definition at line \fB18\fP of file \fBMatrixInv\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
