.TH "md__2_users_2kuba_2_desktop_2_r-_matrix_2_a_z_u_r_e2_2_r_e_a_d_m_e" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__2_users_2kuba_2_desktop_2_r-_matrix_2_a_z_u_r_e2_2_r_e_a_d_m_e \- AZURE2 
.PP
 \fC\fP \fC\fP \fC\fP \fC\fP
.PP
Thank you for choosing AZURE2 to for all your R-Matrix needs\&.
.PP
This file contains a brief description of how to compile the AZURE2 package\&. 
.br
.SH "Dependencies"
.PP
\fBCMake\fP
.PP
AZURE2 is compiled using the CMake package\&. Version 2\&.8 or higher of CMake is (probably) required to build AZURE2\&. CMake can be downloaded from http://www.cmake.org\&.
.PP
\fBGNU Scientific Library\fP
.PP
Additionally, much of the mathematics in AZURE2 uses the GSL routines\&. This library can be obtained from http://www.gnu.org/software/gsl/\&. 
.br
.PP
\fB\fBROOT\fP, MINUIT2, and OpenMP\fP
.PP
The minimization routines utilized by AZURE are from the Minuit2 package, distributed as part of the \fBROOT\fP distribution\&. If \fBROOT\fP is compiled from source, the --enable-minuit2 flag must be set when running the configure script\&. The libraries are available as a stand-alone package from http://seal.web.cern.ch/seal/snapshot/work-packages/mathlibs/minuit/release/download.html\&. It is important to note that the \fBROOT\fP library DOES NOT build Minuit2 with OpenMP support by default, while the stand-alone version does\&. On a multi-core machine the fit process will be much slower without OpenMP\&. To build \fBROOT\fP with OpenMP support for Minuit2, set the enviromnet variables USE_PARALLEL_MINUIT2 and USE_OPENMP prior to building\&. 
.br
.PP
\fBReadline Development Libraries\fP
.PP
If not already available on your system, you can obtain the readline development libraries via your package manager\&. For instance, on ubuntu you can run:
.PP
.PP
.nf
sudo apt\-get install libreadline\-dev
.fi
.PP
.PP
\fBQt4\&.X\fP
.PP
The final compile time dependency is Qt\&. Qt is a cross-platform interface API, and required to compile the graphical setup program\&. While AZURE2 can be compiled without the graphical setup program, this is not recommended\&. Qt is available from http://qt.nokia.com\&. Qt 4\&.4 or greater is required to build AZURE2\&.
.PP
Qt4 can also be obtained via package managers of some Linux distributions\&. For instance, on ubuntu you can simply run:
.PP
.PP
.nf
 bash
sudo apt\-get install qt4\-dev\-tools
.fi
.PP
.SH "Build"
.PP
.SS "Basic Building"
The following steps should be performed to build the AZURE2 package:
.PP
.IP "1." 4
Create a subdirectory of the AZURE2 root named build [mkdir build], and change to that directory [cd build]\&.
.IP "2." 4
Run CMake to generate Makefiles from AZURE2 root [cmake \&.\&.]\&. The reference to the parent directory tells CMake where the root of the source tree is located\&. 
.br

.IP "3." 4
Build the package [make && make install]\&. The resulting binary will be created in the current directory\&.
.PP
.PP
Alternatively, run the \fIbuild\&.sh\fP script\&.
.SS "Options"
Compiling options (i\&.e\&. switching compilers, etc\&.) are available with flags to CMake\&. See the CMake documentation for more details\&.
.PP
A few options are available to the user when building AZURE2\&. The can be passed to cmake using the -D[OPTION]=[VALUE] syntax\&. CMake also provides a utility to switch these options ON/OFF\&. After an initial configuration of the build directory (step 2 above), the command [ccmake \&.\&.] can be run to view and edit the configured options\&.
.PP
These are:
.PP
BUILD_GUI [ON/OFF] - Toggles whether the graphical setup utility is built and linked to AZURE2\&. This is ON by default, and it is not recommended to turn it OFF\&.
.PP
USE_QWT [ON/OFF] - Toggles whether the built-in plotting tab is added to AZURE2\&. This is OFF by default\&. The plotting features are recommended but require the additional QWT libraries to be installed on the build system\&. 
.br
.PP
USE_STAT [ON/OFF] - Toggles whether the stat() function should be used to test for properly set directories at start\&. This only applied when running AZURE2 in console (--no-gui) mode, and is ON by default\&. This function has been seen to not work properly for Windows, and it is recommended to select OFF if building on/for a Windows system\&.
.PP
MINUIT_PATH [dir] - If Minuit2 is in a non-standard path, this will add the directory to the search path\&.
.PP
GSL_PATH [dir] - If GSL is in a non-standard path, this will add the directory to the search path\&.
.PP
After changing options, execute [make clean] and then step 3 above to build/rebuild AZURE2\&. 
.br
.PP
\fBQt5\fP
.PP
Install libqwt-qt5-dev libqt5svg5-dev
.PP
Probably only some of the below are required\&.\&.\&.
.PP
Install qt5-default qtscript5-dev 
