.TH "MGroup" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MGroup \- An AZURE internal reaction pathway\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MGroup\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMGroup\fP (int, int, int)"
.br
.ti -1c
.RI "int \fBGetChNum\fP () const"
.br
.ti -1c
.RI "int \fBGetChpNum\fP () const"
.br
.ti -1c
.RI "int \fBGetJNum\fP () const"
.br
.ti -1c
.RI "double \fBGetStatSpinFactor\fP () const"
.br
.ti -1c
.RI "void \fBSetStatSpinFactor\fP (double)"
.br
.in -1c
.SH "Detailed Description"
.PP 
An AZURE internal reaction pathway\&. 

An \fBMGroup\fP in AZURE represents a given entrance and exit channel through a $ J^\pi $ group\&. These can be visualized as paths entering one row of the T-Matrix, and exiting through a column\&. 
.PP
Definition at line \fB13\fP of file \fBMGroup\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MGroup::MGroup (int jGroupNum, int channelNum, int channelPrimeNum)"
This constructor is used to create an \fBMGroup\fP object with reference to positions in the \fBJGroup\fP and subsequent \fBAChannel\fP vectors\&. 
.PP
Definition at line \fB7\fP of file \fBMGroup\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int MGroup::GetChNum () const"
Returns the position of the entrance channel in the \fBAChannel\fP vector below the corresponding \fBJGroup\fP object\&. 
.PP
Definition at line \fB15\fP of file \fBMGroup\&.cpp\fP\&.
.SS "int MGroup::GetChpNum () const"
Returns the position of the exit channel in the \fBAChannel\fP vector below the corresponding \fBJGroup\fP object\&. 
.PP
Definition at line \fB23\fP of file \fBMGroup\&.cpp\fP\&.
.SS "int MGroup::GetJNum () const"
Returns the position of the $ J^\pi $ group in the \fBJGroup\fP vector\&. 
.PP
Definition at line \fB31\fP of file \fBMGroup\&.cpp\fP\&.
.SS "double MGroup::GetStatSpinFactor () const"
Returns the statistical spin factor, $ g_J $, for the reaction pathway\&. 
.PP
Definition at line \fB39\fP of file \fBMGroup\&.cpp\fP\&.
.SS "void MGroup::SetStatSpinFactor (double spinFactor)"
Sets the statistical spin factor, $ g_J $, for the reaction pathway\&. 
.PP
Definition at line \fB47\fP of file \fBMGroup\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
