.TH "NFIntegral" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NFIntegral \- A function class to calculate the channel integrals in the denominator of the $ N_f^{1/2} $ term\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NFIntegral\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNFIntegral\fP (\fBPPair\fP *pPair)"
.br
.ti -1c
.RI "\fB~NFIntegral\fP ()"
.br
.ti -1c
.RI "double \fBoperator()\fP (int lFinal, double levelEnergy)"
.br
.ti -1c
.RI "double \fBchanRad\fP () const"
.br
.ti -1c
.RI "double \fBtotalSepE\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
A function class to calculate the channel integrals in the denominator of the $ N_f^{1/2} $ term\&. 

The \fBNFIntegral\fP class returns the channel integral given by $ \int_a^\infty \left[ \frac{W_c(kr)}{W_c{ka_c}} \right]^2 $\&. 
.PP
Definition at line \fB15\fP of file \fBNFIntegral\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NFIntegral::NFIntegral (\fBPPair\fP * pPair)\fC [inline]\fP"
The \fBNFIntegral\fP object is created with reference to a \fBPPair\fP object\&. A \fBWhitFunc\fP object is also created\&. 
.br
 
.PP
Definition at line \fB20\fP of file \fBNFIntegral\&.h\fP\&.
.SS "NFIntegral::~NFIntegral ()\fC [inline]\fP"
The \fBWhitFunc\fP object is destroyed with the \fBNFIntegral\fP object\&. 
.PP
Definition at line \fB28\fP of file \fBNFIntegral\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "double NFIntegral::chanRad () const\fC [inline]\fP"
Returns the channel radius of the particle pair\&. 
.PP
Definition at line \fB40\fP of file \fBNFIntegral\&.h\fP\&.
.SS "double NFIntegral::operator() (int lFinal, double levelEnergy)"
The parenthesis operator is defined so the instance can be callable as a function\&. The final channel orbital angular momentum and final state energy in the compound system are passed as dependent variables\&. 
.PP
Definition at line \fB15\fP of file \fBNFIntegral\&.cpp\fP\&.
.SS "double NFIntegral::totalSepE () const\fC [inline]\fP"
Returns the total seperation energy of the particle pair\&. 
.PP
Definition at line \fB44\fP of file \fBNFIntegral\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
