.TH "NucLine" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NucLine \- A class to read and store a line from a nuclear input file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NucLine\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNucLine\fP (std::istream &stream)"
.br
.ti -1c
.RI "double \fBlevelJ\fP () const"
.br
.ti -1c
.RI "int \fBlevelPi\fP () const"
.br
.ti -1c
.RI "double \fBlevelE\fP () const"
.br
.ti -1c
.RI "int \fBlevelFix\fP () const"
.br
.ti -1c
.RI "int \fBaa\fP () const"
.br
.ti -1c
.RI "int \fBir\fP () const"
.br
.ti -1c
.RI "double \fBs\fP () const"
.br
.ti -1c
.RI "int \fBl\fP () const"
.br
.ti -1c
.RI "int \fBlevelID\fP () const"
.br
.ti -1c
.RI "int \fBisActive\fP () const"
.br
.ti -1c
.RI "int \fBchannelFix\fP () const"
.br
.ti -1c
.RI "double \fBgamma\fP () const"
.br
.ti -1c
.RI "double \fBj1\fP () const"
.br
.ti -1c
.RI "int \fBpi1\fP () const"
.br
.ti -1c
.RI "double \fBj2\fP () const"
.br
.ti -1c
.RI "int \fBpi2\fP () const"
.br
.ti -1c
.RI "double \fBe2\fP () const"
.br
.ti -1c
.RI "double \fBm1\fP () const"
.br
.ti -1c
.RI "double \fBm2\fP () const"
.br
.ti -1c
.RI "int \fBz1\fP () const"
.br
.ti -1c
.RI "int \fBz2\fP () const"
.br
.ti -1c
.RI "double \fBentranceSepE\fP () const"
.br
.ti -1c
.RI "double \fBsepE\fP () const"
.br
.ti -1c
.RI "int \fBj3\fP () const"
.br
.ti -1c
.RI "int \fBpi3\fP () const"
.br
.ti -1c
.RI "double \fBe3\fP () const"
.br
.ti -1c
.RI "int \fBpType\fP () const"
.br
.ti -1c
.RI "double \fBchRad\fP () const"
.br
.ti -1c
.RI "double \fBg1\fP () const"
.br
.ti -1c
.RI "double \fBg2\fP () const"
.br
.ti -1c
.RI "double \fBecMultMask\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class to read and store a line from a nuclear input file\&. 

The \fBNucLine\fP class reads and stores a line from a formatted nuclear input file\&. 
.PP
Definition at line \fB13\fP of file \fBNucLine\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NucLine::NucLine (std::istream & stream)\fC [inline]\fP"
Constructor fills the \fBNucLine\fP object from an input stream\&. 
.PP
Definition at line \fB18\fP of file \fBNucLine\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int NucLine::aa () const\fC [inline]\fP"
Returns the entrance key of the corresponding particle pair for the channel line\&. 
.PP
Definition at line \fB49\fP of file \fBNucLine\&.h\fP\&.
.SS "int NucLine::channelFix () const\fC [inline]\fP"
Returns non-zero if the reduced width amplitude for the channel is not to be varied\&. 
.PP
Definition at line \fB76\fP of file \fBNucLine\&.h\fP\&.
.SS "double NucLine::chRad () const\fC [inline]\fP"
Returns the channel radius for the corresponding particle pair\&. 
.PP
Definition at line \fB146\fP of file \fBNucLine\&.h\fP\&.
.SS "double NucLine::e2 () const\fC [inline]\fP"
Returns the excitation energy of the heavy particle in the corresponding pair\&. 
.PP
Definition at line \fB101\fP of file \fBNucLine\&.h\fP\&.
.SS "double NucLine::e3 () const\fC [inline]\fP"
This function is depriciated and not used\&. 
.PP
Definition at line \fB137\fP of file \fBNucLine\&.h\fP\&.
.SS "double NucLine::ecMultMask () const\fC [inline]\fP"
Returns the external capture multiplicity mask for the corresponding pair\&. 
.PP
Definition at line \fB158\fP of file \fBNucLine\&.h\fP\&.
.SS "double NucLine::entranceSepE () const\fC [inline]\fP"
This function is depriciated and not used\&. 
.PP
Definition at line \fB121\fP of file \fBNucLine\&.h\fP\&.
.SS "double NucLine::g1 () const\fC [inline]\fP"
Returns the g-factor for the light particle in the corresponding pair\&. 
.PP
Definition at line \fB150\fP of file \fBNucLine\&.h\fP\&.
.SS "double NucLine::g2 () const\fC [inline]\fP"
Returns the g-factor for the heavy particle in the corresponding pair\&. 
.PP
Definition at line \fB154\fP of file \fBNucLine\&.h\fP\&.
.SS "double NucLine::gamma () const\fC [inline]\fP"
Returns the initial reduced width or physical amplitude for the channel\&. 
.PP
Definition at line \fB80\fP of file \fBNucLine\&.h\fP\&.
.SS "int NucLine::ir () const\fC [inline]\fP"
Returns the exit key of the corresponding particle pair for the channel line\&. 
.PP
Definition at line \fB54\fP of file \fBNucLine\&.h\fP\&.
.SS "int NucLine::isActive () const\fC [inline]\fP"
Returns non-zero if the corresponding level for the channel line is to be used in the calculation\&. 
.PP
Definition at line \fB71\fP of file \fBNucLine\&.h\fP\&.
.SS "double NucLine::j1 () const\fC [inline]\fP"
Returns the spin of the light particle in the corresponding pair\&. 
.PP
Definition at line \fB84\fP of file \fBNucLine\&.h\fP\&.
.SS "double NucLine::j2 () const\fC [inline]\fP"
Returns the spin of the heavy particle in the corresponding pair\&. 
.PP
Definition at line \fB92\fP of file \fBNucLine\&.h\fP\&.
.SS "int NucLine::j3 () const\fC [inline]\fP"
This function is depriciated and not used\&. 
.PP
Definition at line \fB129\fP of file \fBNucLine\&.h\fP\&.
.SS "int NucLine::l () const\fC [inline]\fP"
Returns the orbital angular momentum of the channel\&. 
.PP
Definition at line \fB62\fP of file \fBNucLine\&.h\fP\&.
.SS "double NucLine::levelE () const\fC [inline]\fP"
Returns the excitation energy of the corresponding level for the channel line\&. 
.PP
Definition at line \fB39\fP of file \fBNucLine\&.h\fP\&.
.SS "int NucLine::levelFix () const\fC [inline]\fP"
Returns non-zero if the corresponding level for the channel line is not to be varied in the fit\&. 
.PP
Definition at line \fB44\fP of file \fBNucLine\&.h\fP\&.
.SS "int NucLine::levelID () const\fC [inline]\fP"
Returns an indexing variable used by the graphical setup program\&. 
.PP
Definition at line \fB66\fP of file \fBNucLine\&.h\fP\&.
.SS "double NucLine::levelJ () const\fC [inline]\fP"
Returns the spin of the corresponding level for the channel line\&. 
.PP
Definition at line \fB30\fP of file \fBNucLine\&.h\fP\&.
.SS "int NucLine::levelPi () const\fC [inline]\fP"
Returns the parity of the corresponding level for the channel line\&. 
.PP
Definition at line \fB34\fP of file \fBNucLine\&.h\fP\&.
.SS "double NucLine::m1 () const\fC [inline]\fP"
Returns the mass of the light particle in the corresponding pair\&. 
.PP
Definition at line \fB105\fP of file \fBNucLine\&.h\fP\&.
.SS "double NucLine::m2 () const\fC [inline]\fP"
Returns the mass of the heavy particle in the corresponding pair\&. 
.PP
Definition at line \fB109\fP of file \fBNucLine\&.h\fP\&.
.SS "int NucLine::pi1 () const\fC [inline]\fP"
Returns the parity of the light particle in the corresponding pair\&. 
.PP
Definition at line \fB88\fP of file \fBNucLine\&.h\fP\&.
.SS "int NucLine::pi2 () const\fC [inline]\fP"
Returns the parity of the heavy particle in the corresponding pair\&. 
.PP
Definition at line \fB96\fP of file \fBNucLine\&.h\fP\&.
.SS "int NucLine::pi3 () const\fC [inline]\fP"
This function is depriciated and not used\&. 
.PP
Definition at line \fB133\fP of file \fBNucLine\&.h\fP\&.
.SS "int NucLine::pType () const\fC [inline]\fP"
Returns 0 for particle-particle and 10 for particle-gamma types in the corresponding pair\&. 
.PP
Definition at line \fB142\fP of file \fBNucLine\&.h\fP\&.
.SS "double NucLine::s () const\fC [inline]\fP"
Returns the channel spin of the channel\&. 
.PP
Definition at line \fB58\fP of file \fBNucLine\&.h\fP\&.
.SS "double NucLine::sepE () const\fC [inline]\fP"
Returns the separation energy for the corresponding particle pair\&. 
.PP
Definition at line \fB125\fP of file \fBNucLine\&.h\fP\&.
.SS "int NucLine::z1 () const\fC [inline]\fP"
Returns the charge of the light particle in the corresponding pair\&. 
.PP
Definition at line \fB113\fP of file \fBNucLine\&.h\fP\&.
.SS "int NucLine::z2 () const\fC [inline]\fP"
Returns the charge of the heavy particle in the corresponding pair\&. 
.PP
Definition at line \fB117\fP of file \fBNucLine\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
