.TH "ODE_integration" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ODE_integration
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ode_int\&.H>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBODE_integration\fP (const std::complex< double > &l_1, const std::complex< double > &two_eta_1)"
.br
.ti -1c
.RI "void \fBoperator()\fP (const std::complex< double > &r0, const std::complex< double > &u0, const std::complex< double > &du0, const std::complex< double > &r, std::complex< double > &u, std::complex< double > &du) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBode_int\&.H\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ODE_integration::ODE_integration (const std::complex< double > & l_1, const std::complex< double > & two_eta_1)\fC [inline]\fP"

.PP
Definition at line \fB15\fP of file \fBode_int\&.H\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ODE_integration::operator() (const std::complex< double > & r0, const std::complex< double > & u0, const std::complex< double > & du0, const std::complex< double > & r, std::complex< double > & u, std::complex< double > & du) const"

.PP
Definition at line \fB118\fP of file \fBode_int\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
