.TH "PairsModel" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PairsModel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PairsModel\&.h>\fP
.PP
Inherits QAbstractTableModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPairsModel\fP (QObject *parent=0)"
.br
.ti -1c
.RI "int \fBrowCount\fP (const QModelIndex &parent) const"
.br
.ti -1c
.RI "int \fBcolumnCount\fP (const QModelIndex &parent) const"
.br
.ti -1c
.RI "QVariant \fBdata\fP (const QModelIndex &index, int role) const"
.br
.ti -1c
.RI "QVariant \fBheaderData\fP (int section, Qt::Orientation orientation, int role) const"
.br
.ti -1c
.RI "bool \fBsetData\fP (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)"
.br
.ti -1c
.RI "bool \fBinsertRows\fP (int position, int rows, const QModelIndex &index=QModelIndex())"
.br
.ti -1c
.RI "bool \fBremoveRows\fP (int position, int rows, const QModelIndex &index=QModelIndex())"
.br
.ti -1c
.RI "int \fBisPair\fP (const \fBPairsData\fP &pair) const"
.br
.ti -1c
.RI "int \fBnumPairs\fP () const"
.br
.ti -1c
.RI "QList< \fBPairsData\fP > \fBgetPairs\fP () const"
.br
.ti -1c
.RI "QString \fBgetParticleLabel\fP (const \fBPairsData\fP &pair, int which=\-1) const"
.br
.ti -1c
.RI "QString \fBgetReactionLabel\fP (const \fBPairsData\fP &firstPair, const \fBPairsData\fP &secondPair)"
.br
.ti -1c
.RI "QString \fBgetReactionLabelTotalCapture\fP (const \fBPairsData\fP &firstPair)"
.br
.ti -1c
.RI "QString \fBgetSpinLabel\fP (const \fBPairsData\fP &pair, int which) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB26\fP of file \fBPairsModel\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PairsModel::PairsModel (QObject * parent = \fC0\fP)"

.PP
Definition at line \fB5\fP of file \fBPairsModel\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int PairsModel::columnCount (const QModelIndex & parent) const"

.PP
Definition at line \fB13\fP of file \fBPairsModel\&.cpp\fP\&.
.SS "QVariant PairsModel::data (const QModelIndex & index, int role) const"

.PP
Definition at line \fB18\fP of file \fBPairsModel\&.cpp\fP\&.
.SS "QList< \fBPairsData\fP > PairsModel::getPairs () const\fC [inline]\fP"

.PP
Definition at line \fB42\fP of file \fBPairsModel\&.h\fP\&.
.SS "QString PairsModel::getParticleLabel (const \fBPairsData\fP & pair, int which = \fC\-1\fP) const"

.PP
Definition at line \fB187\fP of file \fBPairsModel\&.cpp\fP\&.
.SS "QString PairsModel::getReactionLabel (const \fBPairsData\fP & firstPair, const \fBPairsData\fP & secondPair)"

.PP
Definition at line \fB240\fP of file \fBPairsModel\&.cpp\fP\&.
.SS "QString PairsModel::getReactionLabelTotalCapture (const \fBPairsData\fP & firstPair)"

.PP
Definition at line \fB287\fP of file \fBPairsModel\&.cpp\fP\&.
.SS "QString PairsModel::getSpinLabel (const \fBPairsData\fP & pair, int which) const"

.PP
Definition at line \fB330\fP of file \fBPairsModel\&.cpp\fP\&.
.SS "QVariant PairsModel::headerData (int section, Qt::Orientation orientation, int role) const"

.PP
Definition at line \fB65\fP of file \fBPairsModel\&.cpp\fP\&.
.SS "bool PairsModel::insertRows (int position, int rows, const QModelIndex & index = \fCQModelIndex()\fP)"

.PP
Definition at line \fB136\fP of file \fBPairsModel\&.cpp\fP\&.
.SS "int PairsModel::isPair (const \fBPairsData\fP & pair) const"

.PP
Definition at line \fB161\fP of file \fBPairsModel\&.cpp\fP\&.
.SS "int PairsModel::numPairs () const\fC [inline]\fP"

.PP
Definition at line \fB41\fP of file \fBPairsModel\&.h\fP\&.
.SS "bool PairsModel::removeRows (int position, int rows, const QModelIndex & index = \fCQModelIndex()\fP)"

.PP
Definition at line \fB149\fP of file \fBPairsModel\&.cpp\fP\&.
.SS "int PairsModel::rowCount (const QModelIndex & parent) const"

.PP
Definition at line \fB8\fP of file \fBPairsModel\&.cpp\fP\&.
.SS "bool PairsModel::setData (const QModelIndex & index, const QVariant & value, int role = \fCQt::EditRole\fP)"

.PP
Definition at line \fB108\fP of file \fBPairsModel\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
