.TH "PairsData" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PairsData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PairsModel\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBlightJ\fP"
.br
.ti -1c
.RI "int \fBlightPi\fP"
.br
.ti -1c
.RI "int \fBlightZ\fP"
.br
.ti -1c
.RI "double \fBlightM\fP"
.br
.ti -1c
.RI "double \fBlightG\fP"
.br
.ti -1c
.RI "double \fBheavyJ\fP"
.br
.ti -1c
.RI "int \fBheavyPi\fP"
.br
.ti -1c
.RI "int \fBheavyZ\fP"
.br
.ti -1c
.RI "double \fBheavyM\fP"
.br
.ti -1c
.RI "double \fBheavyG\fP"
.br
.ti -1c
.RI "double \fBexcitationEnergy\fP"
.br
.ti -1c
.RI "double \fBseperationEnergy\fP"
.br
.ti -1c
.RI "double \fBchannelRadius\fP"
.br
.ti -1c
.RI "int \fBpairType\fP"
.br
.ti -1c
.RI "int \fBecMultMask\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBSIZE\fP = 15"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBPairsModel\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double PairsData::channelRadius"

.PP
Definition at line \fB21\fP of file \fBPairsModel\&.h\fP\&.
.SS "int PairsData::ecMultMask"

.PP
Definition at line \fB23\fP of file \fBPairsModel\&.h\fP\&.
.SS "double PairsData::excitationEnergy"

.PP
Definition at line \fB19\fP of file \fBPairsModel\&.h\fP\&.
.SS "double PairsData::heavyG"

.PP
Definition at line \fB18\fP of file \fBPairsModel\&.h\fP\&.
.SS "double PairsData::heavyJ"

.PP
Definition at line \fB14\fP of file \fBPairsModel\&.h\fP\&.
.SS "double PairsData::heavyM"

.PP
Definition at line \fB17\fP of file \fBPairsModel\&.h\fP\&.
.SS "int PairsData::heavyPi"

.PP
Definition at line \fB15\fP of file \fBPairsModel\&.h\fP\&.
.SS "int PairsData::heavyZ"

.PP
Definition at line \fB16\fP of file \fBPairsModel\&.h\fP\&.
.SS "double PairsData::lightG"

.PP
Definition at line \fB13\fP of file \fBPairsModel\&.h\fP\&.
.SS "double PairsData::lightJ"

.PP
Definition at line \fB9\fP of file \fBPairsModel\&.h\fP\&.
.SS "double PairsData::lightM"

.PP
Definition at line \fB12\fP of file \fBPairsModel\&.h\fP\&.
.SS "int PairsData::lightPi"

.PP
Definition at line \fB10\fP of file \fBPairsModel\&.h\fP\&.
.SS "int PairsData::lightZ"

.PP
Definition at line \fB11\fP of file \fBPairsModel\&.h\fP\&.
.SS "int PairsData::pairType"

.PP
Definition at line \fB22\fP of file \fBPairsModel\&.h\fP\&.
.SS "double PairsData::seperationEnergy"

.PP
Definition at line \fB20\fP of file \fBPairsModel\&.h\fP\&.
.SS "const int PairsData::SIZE = 15\fC [static]\fP"

.PP
Definition at line \fB8\fP of file \fBPairsModel\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
