.TH "PairsTab" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PairsTab
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PairsTab\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBaddPair\fP ()"
.br
.ti -1c
.RI "void \fBaddPair\fP (\fBPairsData\fP pair, int pairIndex, bool fromFile)"
.br
.ti -1c
.RI "void \fBeditPair\fP ()"
.br
.ti -1c
.RI "void \fBeditPair\fP (\fBPairsData\fP pair, int pairIndex, bool fromFile)"
.br
.ti -1c
.RI "void \fBremovePair\fP ()"
.br
.ti -1c
.RI "void \fBupdateButtons\fP (const QItemSelection &selection)"
.br
.ti -1c
.RI "void \fBshowInfo\fP (int which=0, QString title='')"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBpairAdded\fP (int)"
.br
.ti -1c
.RI "void \fBpairRemoved\fP (int)"
.br
.ti -1c
.RI "void \fBpairEdited\fP (int)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPairsTab\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fBPairsModel\fP * \fBgetPairsModel\fP ()"
.br
.ti -1c
.RI "bool \fBparseOldECSection\fP (QTextStream &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBPairsTab\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PairsTab::PairsTab (QWidget * parent = \fC0\fP)"

.PP
Definition at line \fB14\fP of file \fBPairsTab\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PairsTab::addPair ()\fC [slot]\fP"

.PP
Definition at line \fB86\fP of file \fBPairsTab\&.cpp\fP\&.
.SS "void PairsTab::addPair (\fBPairsData\fP pair, int pairIndex, bool fromFile)\fC [slot]\fP"

.PP
Definition at line \fB122\fP of file \fBPairsTab\&.cpp\fP\&.
.SS "void PairsTab::editPair ()\fC [slot]\fP"

.PP
Definition at line \fB184\fP of file \fBPairsTab\&.cpp\fP\&.
.SS "void PairsTab::editPair (\fBPairsData\fP pair, int pairIndex, bool fromFile)\fC [slot]\fP"

.PP
Definition at line \fB297\fP of file \fBPairsTab\&.cpp\fP\&.
.SS "\fBPairsModel\fP * PairsTab::getPairsModel ()"

.PP
Definition at line \fB82\fP of file \fBPairsTab\&.cpp\fP\&.
.SS "void PairsTab::pairAdded (int)\fC [signal]\fP"

.SS "void PairsTab::pairEdited (int)\fC [signal]\fP"

.SS "void PairsTab::pairRemoved (int)\fC [signal]\fP"

.SS "bool PairsTab::parseOldECSection (QTextStream & inStream)"

.PP
Definition at line \fB357\fP of file \fBPairsTab\&.cpp\fP\&.
.SS "void PairsTab::removePair ()\fC [slot]\fP"

.PP
Definition at line \fB165\fP of file \fBPairsTab\&.cpp\fP\&.
.SS "void PairsTab::showInfo (int which = \fC0\fP, QString title = \fC''\fP)\fC [slot]\fP"

.PP
Definition at line \fB382\fP of file \fBPairsTab\&.cpp\fP\&.
.SS "void PairsTab::updateButtons (const QItemSelection & selection)\fC [slot]\fP"

.PP
Definition at line \fB347\fP of file \fBPairsTab\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
