.TH "PlotEntry" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlotEntry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AZUREPlot\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlotEntry\fP (int \fBtype\fP, int entranceKey, int exitKey, int index, QString filename)"
.br
.ti -1c
.RI "\fB~PlotEntry\fP ()"
.br
.ti -1c
.RI "int \fBtype\fP () const"
.br
.ti -1c
.RI "bool \fBreadData\fP ()"
.br
.ti -1c
.RI "void \fBattach\fP (QwtPlot *, int, int, QwtSymbol::Style)"
.br
.ti -1c
.RI "void \fBdetach\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAZUREPlot\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB32\fP of file \fBAZUREPlot\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlotEntry::PlotEntry (int type, int entranceKey, int exitKey, int index, QString filename)"

.PP
Definition at line \fB40\fP of file \fBAZUREPlot\&.cpp\fP\&.
.SS "PlotEntry::~PlotEntry ()"

.PP
Definition at line \fB45\fP of file \fBAZUREPlot\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PlotEntry::attach (QwtPlot * plot, int xAxisType, int yAxisType, QwtSymbol::Style style)"

.PP
Definition at line \fB111\fP of file \fBAZUREPlot\&.cpp\fP\&.
.SS "void PlotEntry::detach ()"

.PP
Definition at line \fB223\fP of file \fBAZUREPlot\&.cpp\fP\&.
.SS "bool PlotEntry::readData ()"

.PP
Definition at line \fB51\fP of file \fBAZUREPlot\&.cpp\fP\&.
.SS "int PlotEntry::type () const\fC [inline]\fP"

.PP
Definition at line \fB37\fP of file \fBAZUREPlot\&.h\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class \fBAZUREPlot\fP\fC [friend]\fP"

.PP
Definition at line \fB44\fP of file \fBAZUREPlot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
