.TH "PlotTab" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlotTab
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PlotTab\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.ti -1c
.RI "void \fBxAxisTypeChanged\fP ()"
.br
.ti -1c
.RI "void \fByAxisTypeChanged\fP ()"
.br
.ti -1c
.RI "void \fBxAxisLogScaleChanged\fP (bool)"
.br
.ti -1c
.RI "void \fByAxisLogScaleChanged\fP (bool)"
.br
.ti -1c
.RI "void \fBshowInfo\fP (int which=0, QString title='')"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlotTab\fP (\fBConfig\fP &config, \fBSegmentsDataModel\fP *dataModel, \fBSegmentsTestModel\fP *testModel, QWidget *parent=0)"
.br
.ti -1c
.RI "QList< \fBPlotEntry\fP * > \fBgetDataSegments\fP ()"
.br
.ti -1c
.RI "QList< \fBPlotEntry\fP * > \fBgetTestSegments\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAZUREPlot\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB39\fP of file \fBPlotTab\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlotTab::PlotTab (\fBConfig\fP & config, \fBSegmentsDataModel\fP * dataModel, \fBSegmentsTestModel\fP * testModel, QWidget * parent = \fC0\fP)"

.PP
Definition at line \fB50\fP of file \fBPlotTab\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PlotTab::draw ()\fC [slot]\fP"

.PP
Definition at line \fB223\fP of file \fBPlotTab\&.cpp\fP\&.
.SS "QList< \fBPlotEntry\fP * > PlotTab::getDataSegments ()"

.PP
Definition at line \fB165\fP of file \fBPlotTab\&.cpp\fP\&.
.SS "QList< \fBPlotEntry\fP * > PlotTab::getTestSegments ()"

.PP
Definition at line \fB194\fP of file \fBPlotTab\&.cpp\fP\&.
.SS "void PlotTab::reset ()"

.PP
Definition at line \fB248\fP of file \fBPlotTab\&.cpp\fP\&.
.SS "void PlotTab::showInfo (int which = \fC0\fP, QString title = \fC''\fP)\fC [slot]\fP"

.PP
Definition at line \fB256\fP of file \fBPlotTab\&.cpp\fP\&.
.SS "void PlotTab::xAxisLogScaleChanged (bool checked)\fC [slot]\fP"

.PP
Definition at line \fB240\fP of file \fBPlotTab\&.cpp\fP\&.
.SS "void PlotTab::xAxisTypeChanged ()\fC [slot]\fP"

.PP
Definition at line \fB229\fP of file \fBPlotTab\&.cpp\fP\&.
.SS "void PlotTab::yAxisLogScaleChanged (bool checked)\fC [slot]\fP"

.PP
Definition at line \fB244\fP of file \fBPlotTab\&.cpp\fP\&.
.SS "void PlotTab::yAxisTypeChanged ()\fC [slot]\fP"

.PP
Definition at line \fB233\fP of file \fBPlotTab\&.cpp\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class \fBAZUREPlot\fP\fC [friend]\fP"

.PP
Definition at line \fB58\fP of file \fBPlotTab\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
