.TH "PlotPoint" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlotPoint
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AZUREPlot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBenergy\fP"
.br
.ti -1c
.RI "double \fBexcitationEnergy\fP"
.br
.ti -1c
.RI "double \fBangle\fP"
.br
.ti -1c
.RI "double \fBfitCrossSection\fP"
.br
.ti -1c
.RI "double \fBfitSFactor\fP"
.br
.ti -1c
.RI "double \fBdataCrossSection\fP"
.br
.ti -1c
.RI "double \fBdataErrorCrossSection\fP"
.br
.ti -1c
.RI "double \fBdataSFactor\fP"
.br
.ti -1c
.RI "double \fBdataErrorSFactor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBAZUREPlot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double PlotPoint::angle"

.PP
Definition at line \fB15\fP of file \fBAZUREPlot\&.h\fP\&.
.SS "double PlotPoint::dataCrossSection"

.PP
Definition at line \fB18\fP of file \fBAZUREPlot\&.h\fP\&.
.SS "double PlotPoint::dataErrorCrossSection"

.PP
Definition at line \fB19\fP of file \fBAZUREPlot\&.h\fP\&.
.SS "double PlotPoint::dataErrorSFactor"

.PP
Definition at line \fB21\fP of file \fBAZUREPlot\&.h\fP\&.
.SS "double PlotPoint::dataSFactor"

.PP
Definition at line \fB20\fP of file \fBAZUREPlot\&.h\fP\&.
.SS "double PlotPoint::energy"

.PP
Definition at line \fB13\fP of file \fBAZUREPlot\&.h\fP\&.
.SS "double PlotPoint::excitationEnergy"

.PP
Definition at line \fB14\fP of file \fBAZUREPlot\&.h\fP\&.
.SS "double PlotPoint::fitCrossSection"

.PP
Definition at line \fB16\fP of file \fBAZUREPlot\&.h\fP\&.
.SS "double PlotPoint::fitSFactor"

.PP
Definition at line \fB17\fP of file \fBAZUREPlot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
