.TH "RateParams" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RateParams \- A structure holding the reaction rate calculation configuration\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Config\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBuseFile\fP"
.br
.RI "False for looped temperatures, true for temperatures from file\&. "
.ti -1c
.RI "std::string \fBtemperatureFile\fP"
.br
.RI "String containing filename with temperatures to use\&. "
.ti -1c
.RI "int \fBentrancePair\fP"
.br
.RI "The entrance pair number for the rate calculation\&. "
.ti -1c
.RI "int \fBexitPair\fP"
.br
.RI "The exit pair number for the rate calculation\&. "
.ti -1c
.RI "double \fBminTemp\fP"
.br
.RI "The minimum temperature for the rate calculation\&. "
.ti -1c
.RI "double \fBmaxTemp\fP"
.br
.RI "The maximum temperature for the rate calculation\&. "
.ti -1c
.RI "double \fBtempStep\fP"
.br
.RI "The temperature step for the rate calculation\&. "
.in -1c
.SH "Detailed Description"
.PP 
A structure holding the reaction rate calculation configuration\&. 

The \fBRateParams\fP structure holds the configuration information for a reaction rate calculation\&. 
.PP
Definition at line \fB13\fP of file \fBConfig\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int RateParams::entrancePair"

.PP
The entrance pair number for the rate calculation\&. 
.PP
Definition at line \fB19\fP of file \fBConfig\&.h\fP\&.
.SS "int RateParams::exitPair"

.PP
The exit pair number for the rate calculation\&. 
.PP
Definition at line \fB21\fP of file \fBConfig\&.h\fP\&.
.SS "double RateParams::maxTemp"

.PP
The maximum temperature for the rate calculation\&. 
.PP
Definition at line \fB25\fP of file \fBConfig\&.h\fP\&.
.SS "double RateParams::minTemp"

.PP
The minimum temperature for the rate calculation\&. 
.PP
Definition at line \fB23\fP of file \fBConfig\&.h\fP\&.
.SS "std::string RateParams::temperatureFile"

.PP
String containing filename with temperatures to use\&. 
.PP
Definition at line \fB17\fP of file \fBConfig\&.h\fP\&.
.SS "double RateParams::tempStep"

.PP
The temperature step for the rate calculation\&. 
.PP
Definition at line \fB27\fP of file \fBConfig\&.h\fP\&.
.SS "bool RateParams::useFile"

.PP
False for looped temperatures, true for temperatures from file\&. 
.PP
Definition at line \fB15\fP of file \fBConfig\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
