.TH "/Users/kuba/Desktop/R-Matrix/AZURE2/include/ReactionRate.h" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kuba/Desktop/R-Matrix/AZURE2/include/ReactionRate.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Constants\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRateData\fP"
.br
.RI "A container structure for a reaction rate\&. "
.ti -1c
.RI "class \fBReactionRate\fP"
.br
.RI "A function class to calculate the reaction rate\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBgsl_reactionrate_integration\fP (double, \fBCNuc\fP *, const \fBConfig\fP &, int, int)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double gsl_reactionrate_integration (double temperature, \fBCNuc\fP * compound, const \fBConfig\fP & configure, int entranceKey, int exitKey)"

.PP
Definition at line \fB42\fP of file \fBReactionRate\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
