.TH "ReactionRate" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReactionRate \- A function class to calculate the reaction rate\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ReactionRate\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReactionRate\fP (\fBCNuc\fP *, const \fBvector_r\fP &, const \fBConfig\fP &, int, int)"
.br
.ti -1c
.RI "\fBCNuc\fP * \fBcompound\fP () const"
.br
.ti -1c
.RI "const \fBConfig\fP & \fBconfigure\fP () const"
.br
.ti -1c
.RI "int \fBentranceKey\fP () const"
.br
.ti -1c
.RI "int \fBexitKey\fP () const"
.br
.ti -1c
.RI "void \fBCalculateRates\fP ()"
.br
.ti -1c
.RI "void \fBCalculateFileRates\fP ()"
.br
.ti -1c
.RI "void \fBWriteRates\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A function class to calculate the reaction rate\&. 

The \fBReactionRate\fP function class is used to calculate the reaction rate based on a set of R-Matrix parameters over a range of stellar temperatures\&. 
.PP
Definition at line \fB38\fP of file \fBReactionRate\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ReactionRate::ReactionRate (\fBCNuc\fP * compound, const \fBvector_r\fP & params, const \fBConfig\fP & configure, int entranceKey, int exitKey)"
The \fBReactionRate\fP object is created with reference to a \fBCNuc\fP object, a vector of Minuit parameters, a \fBConfig\fP structure, and a set of entrance and exit pair keys\&. 
.PP
Definition at line \fB71\fP of file \fBReactionRate\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ReactionRate::CalculateFileRates ()"
Calculates the astrophysical reaction rates at temperatures from file\&. 
.PP
Definition at line \fB123\fP of file \fBReactionRate\&.cpp\fP\&.
.SS "void ReactionRate::CalculateRates ()"
Calculates the astrophysical reaction rates over a range of stellar temperatures\&. 
.br
 
.PP
Definition at line \fB84\fP of file \fBReactionRate\&.cpp\fP\&.
.SS "\fBCNuc\fP * ReactionRate::compound () const\fC [inline]\fP"
Returns a pointer to the \fBCNuc\fP object\&. 
.PP
Definition at line \fB48\fP of file \fBReactionRate\&.h\fP\&.
.SS "const \fBConfig\fP & ReactionRate::configure () const\fC [inline]\fP"
Returns a reference to the \fBConfig\fP structure\&. 
.PP
Definition at line \fB52\fP of file \fBReactionRate\&.h\fP\&.
.SS "int ReactionRate::entranceKey () const\fC [inline]\fP"
Returns the entrance pair key\&. 
.PP
Definition at line \fB56\fP of file \fBReactionRate\&.h\fP\&.
.SS "int ReactionRate::exitKey () const\fC [inline]\fP"
Returns the exit pair key\&. 
.PP
Definition at line \fB60\fP of file \fBReactionRate\&.h\fP\&.
.SS "void ReactionRate::WriteRates ()"
Writes the rates to an output file\&. 
.PP
Definition at line \fB170\fP of file \fBReactionRate\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
