.TH "RunTab" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RunTab
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RunTab\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBshowInfo\fP (int which=0, QString title='')"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRunTab\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAZURESetup\fP"
.br
.ti -1c
.RI "class \fBAZUREMainThread\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBRunTab\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RunTab::RunTab (QWidget * parent = \fC0\fP)"

.PP
Definition at line \fB15\fP of file \fBRunTab\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void RunTab::reset ()"

.PP
Definition at line \fB225\fP of file \fBRunTab\&.cpp\fP\&.
.SS "void RunTab::showInfo (int which = \fC0\fP, QString title = \fC''\fP)\fC [slot]\fP"

.PP
Definition at line \fB241\fP of file \fBRunTab\&.cpp\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class \fBAZUREMainThread\fP\fC [friend]\fP"

.PP
Definition at line \fB29\fP of file \fBRunTab\&.h\fP\&.
.SS "friend class \fBAZURESetup\fP\fC [friend]\fP"

.PP
Definition at line \fB28\fP of file \fBRunTab\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
