.TH "/Users/kuba/Desktop/R-Matrix/AZURE2/gui/src/RunTab.cpp" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kuba/Desktop/R-Matrix/AZURE2/gui/src/RunTab.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QTextEdit>\fP
.br
\fC#include <QComboBox>\fP
.br
\fC#include <QGridLayout>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <QSpacerItem>\fP
.br
\fC#include <QRadioButton>\fP
.br
\fC#include <QGroupBox>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include 'RunTab\&.h'\fP
.br
\fC#include 'ChooseFileButton\&.h'\fP
.br
\fC#include 'FilteredTextEdit\&.h'\fP
.br
\fC#include 'InfoDialog\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
