.TH "SegLine" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SegLine \- A class to read and store a line from the data segments input file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SegLine\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSegLine\fP (std::istream &stream)"
.br
.ti -1c
.RI "int \fBisActive\fP () const"
.br
.ti -1c
.RI "int \fBentranceKey\fP () const"
.br
.ti -1c
.RI "int \fBexitKey\fP () const"
.br
.ti -1c
.RI "double \fBminE\fP () const"
.br
.ti -1c
.RI "double \fBmaxE\fP () const"
.br
.ti -1c
.RI "double \fBminA\fP () const"
.br
.ti -1c
.RI "double \fBmaxA\fP () const"
.br
.ti -1c
.RI "int \fBisDiff\fP () const"
.br
.ti -1c
.RI "std::string \fBdataFile\fP () const"
.br
.ti -1c
.RI "double \fBdataNorm\fP () const"
.br
.ti -1c
.RI "double \fBdataNormError\fP () const"
.br
.ti -1c
.RI "int \fBvaryNorm\fP () const"
.br
.ti -1c
.RI "double \fBphaseJ\fP () const"
.br
.ti -1c
.RI "int \fBphaseL\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class to read and store a line from the data segments input file\&. 

The \fBSegLine\fP class reads and stores a line from the data segments input file\&. 
.PP
Definition at line \fB13\fP of file \fBSegLine\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SegLine::SegLine (std::istream & stream)\fC [inline]\fP"
Constructor fill the \fBSegLine\fP object from an input stream\&. 
.PP
Definition at line \fB18\fP of file \fBSegLine\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string SegLine::dataFile () const\fC [inline]\fP"
Returns the path of the data file for the segment\&. 
.PP
Definition at line \fB69\fP of file \fBSegLine\&.h\fP\&.
.SS "double SegLine::dataNorm () const\fC [inline]\fP"
Returns the data normalization for the segment\&. 
.PP
Definition at line \fB73\fP of file \fBSegLine\&.h\fP\&.
.SS "double SegLine::dataNormError () const\fC [inline]\fP"
Returns the data normalization error for the segment\&. 
.PP
Definition at line \fB77\fP of file \fBSegLine\&.h\fP\&.
.SS "int SegLine::entranceKey () const\fC [inline]\fP"
Returns the particle pair key corresponding to the entrance channel for the data segment\&. 
.PP
Definition at line \fB39\fP of file \fBSegLine\&.h\fP\&.
.SS "int SegLine::exitKey () const\fC [inline]\fP"
Returns the particle pair key corresponding to the exit channel for the data segment\&. 
.PP
Definition at line \fB44\fP of file \fBSegLine\&.h\fP\&.
.SS "int SegLine::isActive () const\fC [inline]\fP"
Returns non-zero if the line is to be included in the calculation\&. 
.PP
Definition at line \fB34\fP of file \fBSegLine\&.h\fP\&.
.SS "int SegLine::isDiff () const\fC [inline]\fP"
Return 0 if the segment is angle-integrated cross section, 1 for differential cross section, and 2 for phase shift\&. 
.PP
Definition at line \fB65\fP of file \fBSegLine\&.h\fP\&.
.SS "double SegLine::maxA () const\fC [inline]\fP"
Returns the maximum angle to be included in the segment from the data\&. 
.PP
Definition at line \fB60\fP of file \fBSegLine\&.h\fP\&.
.SS "double SegLine::maxE () const\fC [inline]\fP"
Returns the maximum energy to be included in the segment from the data\&. 
.PP
Definition at line \fB52\fP of file \fBSegLine\&.h\fP\&.
.SS "double SegLine::minA () const\fC [inline]\fP"
Returns the minimum angle to be included in the segment from the data\&. 
.PP
Definition at line \fB56\fP of file \fBSegLine\&.h\fP\&.
.SS "double SegLine::minE () const\fC [inline]\fP"
Returns the minimum energy to be included in the segment from the data\&. 
.PP
Definition at line \fB48\fP of file \fBSegLine\&.h\fP\&.
.SS "double SegLine::phaseJ () const\fC [inline]\fP"
Returns the spin value for the segment if the segment contains phase shift\&. 
.PP
Definition at line \fB85\fP of file \fBSegLine\&.h\fP\&.
.SS "int SegLine::phaseL () const\fC [inline]\fP"
Returns the orbital angular momentum value for the segment if the segment contains phase shift\&. 
.PP
Definition at line \fB90\fP of file \fBSegLine\&.h\fP\&.
.SS "int SegLine::varyNorm () const\fC [inline]\fP"
Returns non-zero of the normalization is to be fit\&. 
.PP
Definition at line \fB81\fP of file \fBSegLine\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
