.TH "SegmentsDataData" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SegmentsDataData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SegmentsDataModel\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBisActive\fP"
.br
.ti -1c
.RI "int \fBentrancePairIndex\fP"
.br
.ti -1c
.RI "int \fBexitPairIndex\fP"
.br
.ti -1c
.RI "double \fBlowEnergy\fP"
.br
.ti -1c
.RI "double \fBhighEnergy\fP"
.br
.ti -1c
.RI "double \fBlowAngle\fP"
.br
.ti -1c
.RI "double \fBhighAngle\fP"
.br
.ti -1c
.RI "int \fBdataType\fP"
.br
.ti -1c
.RI "QString \fBdataFile\fP"
.br
.ti -1c
.RI "double \fBdataNorm\fP"
.br
.ti -1c
.RI "double \fBdataNormError\fP"
.br
.ti -1c
.RI "int \fBvaryNorm\fP"
.br
.ti -1c
.RI "double \fBphaseJ\fP"
.br
.ti -1c
.RI "int \fBphaseL\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBSIZE\fP = 14"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBSegmentsDataModel\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "QString SegmentsDataData::dataFile"

.PP
Definition at line \fB19\fP of file \fBSegmentsDataModel\&.h\fP\&.
.SS "double SegmentsDataData::dataNorm"

.PP
Definition at line \fB20\fP of file \fBSegmentsDataModel\&.h\fP\&.
.SS "double SegmentsDataData::dataNormError"

.PP
Definition at line \fB21\fP of file \fBSegmentsDataModel\&.h\fP\&.
.SS "int SegmentsDataData::dataType"

.PP
Definition at line \fB18\fP of file \fBSegmentsDataModel\&.h\fP\&.
.SS "int SegmentsDataData::entrancePairIndex"

.PP
Definition at line \fB12\fP of file \fBSegmentsDataModel\&.h\fP\&.
.SS "int SegmentsDataData::exitPairIndex"

.PP
Definition at line \fB13\fP of file \fBSegmentsDataModel\&.h\fP\&.
.SS "double SegmentsDataData::highAngle"

.PP
Definition at line \fB17\fP of file \fBSegmentsDataModel\&.h\fP\&.
.SS "double SegmentsDataData::highEnergy"

.PP
Definition at line \fB15\fP of file \fBSegmentsDataModel\&.h\fP\&.
.SS "int SegmentsDataData::isActive"

.PP
Definition at line \fB11\fP of file \fBSegmentsDataModel\&.h\fP\&.
.SS "double SegmentsDataData::lowAngle"

.PP
Definition at line \fB16\fP of file \fBSegmentsDataModel\&.h\fP\&.
.SS "double SegmentsDataData::lowEnergy"

.PP
Definition at line \fB14\fP of file \fBSegmentsDataModel\&.h\fP\&.
.SS "double SegmentsDataData::phaseJ"

.PP
Definition at line \fB23\fP of file \fBSegmentsDataModel\&.h\fP\&.
.SS "int SegmentsDataData::phaseL"

.PP
Definition at line \fB24\fP of file \fBSegmentsDataModel\&.h\fP\&.
.SS "const int SegmentsDataData::SIZE = 14\fC [static]\fP"

.PP
Definition at line \fB10\fP of file \fBSegmentsDataModel\&.h\fP\&.
.SS "int SegmentsDataData::varyNorm"

.PP
Definition at line \fB22\fP of file \fBSegmentsDataModel\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
