.TH "SegmentsTestData" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SegmentsTestData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SegmentsTestModel\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBisActive\fP"
.br
.ti -1c
.RI "int \fBentrancePairIndex\fP"
.br
.ti -1c
.RI "int \fBexitPairIndex\fP"
.br
.ti -1c
.RI "double \fBlowEnergy\fP"
.br
.ti -1c
.RI "double \fBhighEnergy\fP"
.br
.ti -1c
.RI "double \fBenergyStep\fP"
.br
.ti -1c
.RI "double \fBlowAngle\fP"
.br
.ti -1c
.RI "double \fBhighAngle\fP"
.br
.ti -1c
.RI "double \fBangleStep\fP"
.br
.ti -1c
.RI "int \fBdataType\fP"
.br
.ti -1c
.RI "double \fBphaseJ\fP"
.br
.ti -1c
.RI "int \fBphaseL\fP"
.br
.ti -1c
.RI "int \fBmaxAngDistOrder\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBSIZE\fP = 13"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBSegmentsTestModel\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double SegmentsTestData::angleStep"

.PP
Definition at line \fB19\fP of file \fBSegmentsTestModel\&.h\fP\&.
.SS "int SegmentsTestData::dataType"

.PP
Definition at line \fB20\fP of file \fBSegmentsTestModel\&.h\fP\&.
.SS "double SegmentsTestData::energyStep"

.PP
Definition at line \fB16\fP of file \fBSegmentsTestModel\&.h\fP\&.
.SS "int SegmentsTestData::entrancePairIndex"

.PP
Definition at line \fB12\fP of file \fBSegmentsTestModel\&.h\fP\&.
.SS "int SegmentsTestData::exitPairIndex"

.PP
Definition at line \fB13\fP of file \fBSegmentsTestModel\&.h\fP\&.
.SS "double SegmentsTestData::highAngle"

.PP
Definition at line \fB18\fP of file \fBSegmentsTestModel\&.h\fP\&.
.SS "double SegmentsTestData::highEnergy"

.PP
Definition at line \fB15\fP of file \fBSegmentsTestModel\&.h\fP\&.
.SS "int SegmentsTestData::isActive"

.PP
Definition at line \fB11\fP of file \fBSegmentsTestModel\&.h\fP\&.
.SS "double SegmentsTestData::lowAngle"

.PP
Definition at line \fB17\fP of file \fBSegmentsTestModel\&.h\fP\&.
.SS "double SegmentsTestData::lowEnergy"

.PP
Definition at line \fB14\fP of file \fBSegmentsTestModel\&.h\fP\&.
.SS "int SegmentsTestData::maxAngDistOrder"

.PP
Definition at line \fB23\fP of file \fBSegmentsTestModel\&.h\fP\&.
.SS "double SegmentsTestData::phaseJ"

.PP
Definition at line \fB21\fP of file \fBSegmentsTestModel\&.h\fP\&.
.SS "int SegmentsTestData::phaseL"

.PP
Definition at line \fB22\fP of file \fBSegmentsTestModel\&.h\fP\&.
.SS "const int SegmentsTestData::SIZE = 13\fC [static]\fP"

.PP
Definition at line \fB10\fP of file \fBSegmentsTestModel\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
