.TH "SegmentsTestModel" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SegmentsTestModel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SegmentsTestModel\&.h>\fP
.PP
Inherits QAbstractTableModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSegmentsTestModel\fP (QObject *parent=0)"
.br
.ti -1c
.RI "int \fBrowCount\fP (const QModelIndex &parent) const"
.br
.ti -1c
.RI "int \fBcolumnCount\fP (const QModelIndex &parent) const"
.br
.ti -1c
.RI "QVariant \fBdata\fP (const QModelIndex &index, int role) const"
.br
.ti -1c
.RI "QVariant \fBheaderData\fP (int section, Qt::Orientation orientation, int role) const"
.br
.ti -1c
.RI "bool \fBsetData\fP (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)"
.br
.ti -1c
.RI "bool \fBinsertRows\fP (int position, int rows, const QModelIndex &index=QModelIndex())"
.br
.ti -1c
.RI "bool \fBremoveRows\fP (int position, int rows, const QModelIndex &index=QModelIndex())"
.br
.ti -1c
.RI "Qt::ItemFlags \fBflags\fP (const QModelIndex &index) const"
.br
.ti -1c
.RI "int \fBisSegTestLine\fP (const \fBSegmentsTestData\fP &line) const"
.br
.ti -1c
.RI "QList< \fBSegmentsTestData\fP > \fBgetLines\fP () const"
.br
.ti -1c
.RI "void \fBsetPairsModel\fP (\fBPairsModel\fP *model)"
.br
.ti -1c
.RI "QString \fBgetReactionLabel\fP (const QModelIndex &index)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB26\fP of file \fBSegmentsTestModel\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SegmentsTestModel::SegmentsTestModel (QObject * parent = \fC0\fP)"

.PP
Definition at line \fB4\fP of file \fBSegmentsTestModel\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int SegmentsTestModel::columnCount (const QModelIndex & parent) const"

.PP
Definition at line \fB12\fP of file \fBSegmentsTestModel\&.cpp\fP\&.
.SS "QVariant SegmentsTestModel::data (const QModelIndex & index, int role) const"

.PP
Definition at line \fB17\fP of file \fBSegmentsTestModel\&.cpp\fP\&.
.SS "Qt::ItemFlags SegmentsTestModel::flags (const QModelIndex & index) const"

.PP
Definition at line \fB215\fP of file \fBSegmentsTestModel\&.cpp\fP\&.
.SS "QList< \fBSegmentsTestData\fP > SegmentsTestModel::getLines () const\fC [inline]\fP"

.PP
Definition at line \fB41\fP of file \fBSegmentsTestModel\&.h\fP\&.
.SS "QString SegmentsTestModel::getReactionLabel (const QModelIndex & index)"

.PP
Definition at line \fB248\fP of file \fBSegmentsTestModel\&.cpp\fP\&.
.SS "QVariant SegmentsTestModel::headerData (int section, Qt::Orientation orientation, int role) const"

.PP
Definition at line \fB115\fP of file \fBSegmentsTestModel\&.cpp\fP\&.
.SS "bool SegmentsTestModel::insertRows (int position, int rows, const QModelIndex & index = \fCQModelIndex()\fP)"

.PP
Definition at line \fB190\fP of file \fBSegmentsTestModel\&.cpp\fP\&.
.SS "int SegmentsTestModel::isSegTestLine (const \fBSegmentsTestData\fP & line) const"

.PP
Definition at line \fB221\fP of file \fBSegmentsTestModel\&.cpp\fP\&.
.SS "bool SegmentsTestModel::removeRows (int position, int rows, const QModelIndex & index = \fCQModelIndex()\fP)"

.PP
Definition at line \fB203\fP of file \fBSegmentsTestModel\&.cpp\fP\&.
.SS "int SegmentsTestModel::rowCount (const QModelIndex & parent) const"

.PP
Definition at line \fB7\fP of file \fBSegmentsTestModel\&.cpp\fP\&.
.SS "bool SegmentsTestModel::setData (const QModelIndex & index, const QVariant & value, int role = \fCQt::EditRole\fP)"

.PP
Definition at line \fB154\fP of file \fBSegmentsTestModel\&.cpp\fP\&.
.SS "void SegmentsTestModel::setPairsModel (\fBPairsModel\fP * model)"

.PP
Definition at line \fB244\fP of file \fBSegmentsTestModel\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
