.TH "SegmentsTab" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SegmentsTab
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SegmentsTab\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBaddSegDataLine\fP ()"
.br
.ti -1c
.RI "void \fBaddSegDataLine\fP (\fBSegmentsDataData\fP line)"
.br
.ti -1c
.RI "void \fBaddSegTestLine\fP ()"
.br
.ti -1c
.RI "void \fBaddSegTestLine\fP (\fBSegmentsTestData\fP line)"
.br
.ti -1c
.RI "void \fBeditSegDataLine\fP ()"
.br
.ti -1c
.RI "void \fBeditSegTestLine\fP ()"
.br
.ti -1c
.RI "void \fBdeleteSegDataLine\fP ()"
.br
.ti -1c
.RI "void \fBdeleteSegTestLine\fP ()"
.br
.ti -1c
.RI "void \fBmoveSegDataLineUp\fP ()"
.br
.ti -1c
.RI "void \fBmoveSegDataLineDown\fP ()"
.br
.ti -1c
.RI "void \fBmoveSegTestLineUp\fP ()"
.br
.ti -1c
.RI "void \fBmoveSegTestLineDown\fP ()"
.br
.ti -1c
.RI "void \fBupdateSegDataButtons\fP (const QItemSelection &selection)"
.br
.ti -1c
.RI "void \fBupdateSegTestButtons\fP (const QItemSelection &selection)"
.br
.ti -1c
.RI "bool \fBreadSegDataFile\fP (QTextStream &inStream)"
.br
.ti -1c
.RI "bool \fBwriteSegDataFile\fP (QTextStream &outStream)"
.br
.ti -1c
.RI "bool \fBreadSegTestFile\fP (QTextStream &inStream)"
.br
.ti -1c
.RI "bool \fBwriteSegTestFile\fP (QTextStream &outStream)"
.br
.ti -1c
.RI "void \fBsetPairsModel\fP (\fBPairsModel\fP *model)"
.br
.ti -1c
.RI "void \fBshowInfo\fP (int which=0, QString title='')"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSegmentsTab\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fBSegmentsTestModel\fP * \fBgetSegmentsTestModel\fP ()"
.br
.ti -1c
.RI "\fBSegmentsDataModel\fP * \fBgetSegmentsDataModel\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBSegmentsTab\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SegmentsTab::SegmentsTab (QWidget * parent = \fC0\fP)"

.PP
Definition at line \fB12\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SegmentsTab::addSegDataLine ()\fC [slot]\fP"

.PP
Definition at line \fB188\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "void SegmentsTab::addSegDataLine (\fBSegmentsDataData\fP line)\fC [slot]\fP"

.PP
Definition at line \fB213\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "void SegmentsTab::addSegTestLine ()\fC [slot]\fP"

.PP
Definition at line \fB252\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "void SegmentsTab::addSegTestLine (\fBSegmentsTestData\fP line)\fC [slot]\fP"

.PP
Definition at line \fB275\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "void SegmentsTab::deleteSegDataLine ()\fC [slot]\fP"

.PP
Definition at line \fB170\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "void SegmentsTab::deleteSegTestLine ()\fC [slot]\fP"

.PP
Definition at line \fB179\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "void SegmentsTab::editSegDataLine ()\fC [slot]\fP"

.PP
Definition at line \fB312\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "void SegmentsTab::editSegTestLine ()\fC [slot]\fP"

.PP
Definition at line \fB446\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "\fBSegmentsDataModel\fP * SegmentsTab::getSegmentsDataModel ()"

.PP
Definition at line \fB166\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "\fBSegmentsTestModel\fP * SegmentsTab::getSegmentsTestModel ()"

.PP
Definition at line \fB162\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "void SegmentsTab::moveSegDataLineDown ()\fC [slot]\fP"

.PP
Definition at line \fB573\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "void SegmentsTab::moveSegDataLineUp ()\fC [slot]\fP"

.PP
Definition at line \fB569\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "void SegmentsTab::moveSegTestLineDown ()\fC [slot]\fP"

.PP
Definition at line \fB627\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "void SegmentsTab::moveSegTestLineUp ()\fC [slot]\fP"

.PP
Definition at line \fB623\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "bool SegmentsTab::readSegDataFile (QTextStream & inStream)\fC [slot]\fP"

.PP
Definition at line \fB709\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "bool SegmentsTab::readSegTestFile (QTextStream & inStream)\fC [slot]\fP"

.PP
Definition at line \fB781\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "void SegmentsTab::reset ()"

.PP
Definition at line \fB856\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "void SegmentsTab::setPairsModel (\fBPairsModel\fP * model)\fC [inline]\fP, \fC [slot]\fP"

.PP
Definition at line \fB60\fP of file \fBSegmentsTab\&.h\fP\&.
.SS "void SegmentsTab::showInfo (int which = \fC0\fP, QString title = \fC''\fP)\fC [slot]\fP"

.PP
Definition at line \fB861\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "void SegmentsTab::updateSegDataButtons (const QItemSelection & selection)\fC [slot]\fP"

.PP
Definition at line \fB676\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "void SegmentsTab::updateSegTestButtons (const QItemSelection & selection)\fC [slot]\fP"

.PP
Definition at line \fB692\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "bool SegmentsTab::writeSegDataFile (QTextStream & outStream)\fC [slot]\fP"

.PP
Definition at line \fB757\fP of file \fBSegmentsTab\&.cpp\fP\&.
.SS "bool SegmentsTab::writeSegTestFile (QTextStream & outStream)\fC [slot]\fP"

.PP
Definition at line \fB826\fP of file \fBSegmentsTab\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
