.TH "SegmentsDataModel" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SegmentsDataModel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SegmentsDataModel\&.h>\fP
.PP
Inherits QAbstractTableModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSegmentsDataModel\fP (QObject *parent=0)"
.br
.ti -1c
.RI "int \fBrowCount\fP (const QModelIndex &parent) const"
.br
.ti -1c
.RI "int \fBcolumnCount\fP (const QModelIndex &parent) const"
.br
.ti -1c
.RI "QVariant \fBdata\fP (const QModelIndex &index, int role) const"
.br
.ti -1c
.RI "QVariant \fBheaderData\fP (int section, Qt::Orientation orientation, int role) const"
.br
.ti -1c
.RI "bool \fBsetData\fP (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)"
.br
.ti -1c
.RI "bool \fBinsertRows\fP (int position, int rows, const QModelIndex &index=QModelIndex())"
.br
.ti -1c
.RI "bool \fBremoveRows\fP (int position, int rows, const QModelIndex &index=QModelIndex())"
.br
.ti -1c
.RI "Qt::ItemFlags \fBflags\fP (const QModelIndex &index) const"
.br
.ti -1c
.RI "int \fBisSegDataLine\fP (const \fBSegmentsDataData\fP &line) const"
.br
.ti -1c
.RI "QList< \fBSegmentsDataData\fP > \fBgetLines\fP () const"
.br
.ti -1c
.RI "void \fBsetPairsModel\fP (\fBPairsModel\fP *model)"
.br
.ti -1c
.RI "QString \fBgetReactionLabel\fP (const QModelIndex &index)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB27\fP of file \fBSegmentsDataModel\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SegmentsDataModel::SegmentsDataModel (QObject * parent = \fC0\fP)"

.PP
Definition at line \fB5\fP of file \fBSegmentsDataModel\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int SegmentsDataModel::columnCount (const QModelIndex & parent) const"

.PP
Definition at line \fB13\fP of file \fBSegmentsDataModel\&.cpp\fP\&.
.SS "QVariant SegmentsDataModel::data (const QModelIndex & index, int role) const"

.PP
Definition at line \fB18\fP of file \fBSegmentsDataModel\&.cpp\fP\&.
.SS "Qt::ItemFlags SegmentsDataModel::flags (const QModelIndex & index) const"

.PP
Definition at line \fB226\fP of file \fBSegmentsDataModel\&.cpp\fP\&.
.SS "QList< \fBSegmentsDataData\fP > SegmentsDataModel::getLines () const\fC [inline]\fP"

.PP
Definition at line \fB42\fP of file \fBSegmentsDataModel\&.h\fP\&.
.SS "QString SegmentsDataModel::getReactionLabel (const QModelIndex & index)"

.PP
Definition at line \fB260\fP of file \fBSegmentsDataModel\&.cpp\fP\&.
.SS "QVariant SegmentsDataModel::headerData (int section, Qt::Orientation orientation, int role) const"

.PP
Definition at line \fB123\fP of file \fBSegmentsDataModel\&.cpp\fP\&.
.SS "bool SegmentsDataModel::insertRows (int position, int rows, const QModelIndex & index = \fCQModelIndex()\fP)"

.PP
Definition at line \fB201\fP of file \fBSegmentsDataModel\&.cpp\fP\&.
.SS "int SegmentsDataModel::isSegDataLine (const \fBSegmentsDataData\fP & line) const"

.PP
Definition at line \fB232\fP of file \fBSegmentsDataModel\&.cpp\fP\&.
.SS "bool SegmentsDataModel::removeRows (int position, int rows, const QModelIndex & index = \fCQModelIndex()\fP)"

.PP
Definition at line \fB214\fP of file \fBSegmentsDataModel\&.cpp\fP\&.
.SS "int SegmentsDataModel::rowCount (const QModelIndex & parent) const"

.PP
Definition at line \fB8\fP of file \fBSegmentsDataModel\&.cpp\fP\&.
.SS "bool SegmentsDataModel::setData (const QModelIndex & index, const QVariant & value, int role = \fCQt::EditRole\fP)"

.PP
Definition at line \fB164\fP of file \fBSegmentsDataModel\&.cpp\fP\&.
.SS "void SegmentsDataModel::setPairsModel (\fBPairsModel\fP * model)"

.PP
Definition at line \fB256\fP of file \fBSegmentsDataModel\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
