.TH "SegPairs" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SegPairs
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfirstPair\fP"
.br
.ti -1c
.RI "int \fBsecondPair\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB28\fP of file \fBAZURESetup\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int SegPairs::firstPair"

.PP
Definition at line \fB28\fP of file \fBAZURESetup\&.cpp\fP\&.
.SS "int SegPairs::secondPair"

.PP
Definition at line \fB28\fP of file \fBAZURESetup\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
