.TH "SegTestProxyModel" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SegTestProxyModel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PlotTab\&.h>\fP
.PP
Inherits QSortFilterProxyModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSegTestProxyModel\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "QVariant \fBdata\fP (const QModelIndex &index, int role=Qt::DisplayRole) const"
.br
.ti -1c
.RI "bool \fBfilterAcceptsRow\fP (int source_row, const QModelIndex &source_parent) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB26\fP of file \fBPlotTab\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SegTestProxyModel::SegTestProxyModel (QWidget * parent = \fC0\fP)\fC [inline]\fP"

.PP
Definition at line \fB28\fP of file \fBPlotTab\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "QVariant SegTestProxyModel::data (const QModelIndex & index, int role = \fCQt::DisplayRole\fP) const"

.PP
Definition at line \fB20\fP of file \fBPlotTab\&.cpp\fP\&.
.SS "bool SegTestProxyModel::filterAcceptsRow (int source_row, const QModelIndex & source_parent) const"

.PP
Definition at line \fB29\fP of file \fBPlotTab\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
