.TH "ShftFunc" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShftFunc \- A function class for negative energy shift functions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ShftFunc\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShftFunc\fP (\fBPPair\fP *pPair)"
.br
.ti -1c
.RI "\fB~ShftFunc\fP ()"
.br
.ti -1c
.RI "double \fBoperator()\fP (int l, double energy)"
.br
.ti -1c
.RI "double \fBEnergyDerivative\fP (int l, double energy)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A function class for negative energy shift functions\&. 

A shift function for negative energy channels is calculated as $ S=\rho \frac{W_c'(k\rho)}{W_c(k\rho)} $, where the prime indicates the derivative with respect to $ \rho $\&. The AZURE function class \fBShftFunc\fP uses the GSL package to calculates the numerical derivative\&. 
.PP
Definition at line \fB18\fP of file \fBShftFunc\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ShftFunc::ShftFunc (\fBPPair\fP * pPair)\fC [inline]\fP"
The \fBShftFunc\fP object is created with reference to a particle pair\&. 
.PP
Definition at line \fB23\fP of file \fBShftFunc\&.h\fP\&.
.SS "ShftFunc::~ShftFunc ()\fC [inline]\fP"

.PP
Definition at line \fB31\fP of file \fBShftFunc\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "double ShftFunc::EnergyDerivative (int l, double energy)"
Returns the energy derivative of the shift function at the specified orbital angular momentum and energy in the compound system\&. 
.PP
Definition at line \fB37\fP of file \fBShftFunc\&.cpp\fP\&.
.SS "double ShftFunc::operator() (int l, double energy)"
The parenthesis operator is defined to make the class instance callable as a function\&. The orbital angular momentum and energy in the compound system are the dependent variables\&. The function returns the value of the shift function\&. 
.PP
Definition at line \fB21\fP of file \fBShftFunc\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
