.TH "SyntaxError" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyntaxError \- An exception class thrown by the \fBEquation\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Equation\&.h>\fP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSyntaxError\fP (std::string equation, int type, int position=\-1)"
.br
.ti -1c
.RI "\fB~SyntaxError\fP ()  throw ()"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const  throw ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
An exception class thrown by the \fBEquation\fP class\&. 

The \fBSyntaxError\fP class is an exception class thrown by the \fBEquation\fP class\&. It should not be used directly\&. 
.PP
Definition at line \fB89\fP of file \fBEquation\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SyntaxError::SyntaxError (std::string equation, int type, int position = \fC\-1\fP)\fC [inline]\fP"
Constructs the \fBSyntaxError\fP with the message type, equation string, and position in the string\&. 
.PP
Definition at line \fB95\fP of file \fBEquation\&.h\fP\&.
.SS "SyntaxError::~SyntaxError ()\fC [inline]\fP"

.PP
Definition at line \fB105\fP of file \fBEquation\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual const char * SyntaxError::what () const\fC [inline]\fP, \fC [virtual]\fP"
Returns the message of the thrown \fBSyntaxError\fP\&. 
.PP
Definition at line \fB111\fP of file \fBEquation\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
