.TH "TargetIntData" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TargetIntData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TargetIntModel\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBisActive\fP"
.br
.ti -1c
.RI "QString \fBsegmentsList\fP"
.br
.ti -1c
.RI "int \fBnumPoints\fP"
.br
.ti -1c
.RI "bool \fBisConvolution\fP"
.br
.ti -1c
.RI "double \fBsigma\fP"
.br
.ti -1c
.RI "bool \fBisTargetIntegration\fP"
.br
.ti -1c
.RI "double \fBdensity\fP"
.br
.ti -1c
.RI "QString \fBstoppingPowerEq\fP"
.br
.ti -1c
.RI "int \fBnumParameters\fP"
.br
.ti -1c
.RI "QList< double > \fBparameters\fP"
.br
.ti -1c
.RI "bool \fBisQCoefficients\fP"
.br
.ti -1c
.RI "QList< double > \fBqCoefficients\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBSIZE\fP = 12"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBTargetIntModel\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double TargetIntData::density"

.PP
Definition at line \fB17\fP of file \fBTargetIntModel\&.h\fP\&.
.SS "int TargetIntData::isActive"

.PP
Definition at line \fB11\fP of file \fBTargetIntModel\&.h\fP\&.
.SS "bool TargetIntData::isConvolution"

.PP
Definition at line \fB14\fP of file \fBTargetIntModel\&.h\fP\&.
.SS "bool TargetIntData::isQCoefficients"

.PP
Definition at line \fB21\fP of file \fBTargetIntModel\&.h\fP\&.
.SS "bool TargetIntData::isTargetIntegration"

.PP
Definition at line \fB16\fP of file \fBTargetIntModel\&.h\fP\&.
.SS "int TargetIntData::numParameters"

.PP
Definition at line \fB19\fP of file \fBTargetIntModel\&.h\fP\&.
.SS "int TargetIntData::numPoints"

.PP
Definition at line \fB13\fP of file \fBTargetIntModel\&.h\fP\&.
.SS "QList<double> TargetIntData::parameters"

.PP
Definition at line \fB20\fP of file \fBTargetIntModel\&.h\fP\&.
.SS "QList<double> TargetIntData::qCoefficients"

.PP
Definition at line \fB22\fP of file \fBTargetIntModel\&.h\fP\&.
.SS "QString TargetIntData::segmentsList"

.PP
Definition at line \fB12\fP of file \fBTargetIntModel\&.h\fP\&.
.SS "double TargetIntData::sigma"

.PP
Definition at line \fB15\fP of file \fBTargetIntModel\&.h\fP\&.
.SS "const int TargetIntData::SIZE = 12\fC [static]\fP"

.PP
Definition at line \fB10\fP of file \fBTargetIntModel\&.h\fP\&.
.SS "QString TargetIntData::stoppingPowerEq"

.PP
Definition at line \fB18\fP of file \fBTargetIntModel\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
