.TH "TargetIntTab" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TargetIntTab
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TargetIntTab\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBaddLine\fP ()"
.br
.ti -1c
.RI "void \fBaddLine\fP (\fBTargetIntData\fP line)"
.br
.ti -1c
.RI "void \fBeditLine\fP ()"
.br
.ti -1c
.RI "void \fBdeleteLine\fP ()"
.br
.ti -1c
.RI "void \fBupdateButtons\fP (const QItemSelection &selection)"
.br
.ti -1c
.RI "void \fBshowInfo\fP (int which=0, QString title='')"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTargetIntTab\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fBTargetIntModel\fP * \fBgetTargetIntModel\fP ()"
.br
.ti -1c
.RI "bool \fBwriteFile\fP (QTextStream &outStream)"
.br
.ti -1c
.RI "bool \fBreadFile\fP (QTextStream &inStream)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB21\fP of file \fBTargetIntTab\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TargetIntTab::TargetIntTab (QWidget * parent = \fC0\fP)"

.PP
Definition at line \fB14\fP of file \fBTargetIntTab\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TargetIntTab::addLine ()\fC [slot]\fP"

.PP
Definition at line \fB74\fP of file \fBTargetIntTab\&.cpp\fP\&.
.SS "void TargetIntTab::addLine (\fBTargetIntData\fP line)\fC [slot]\fP"

.PP
Definition at line \fB100\fP of file \fBTargetIntTab\&.cpp\fP\&.
.SS "void TargetIntTab::deleteLine ()\fC [slot]\fP"

.PP
Definition at line \fB257\fP of file \fBTargetIntTab\&.cpp\fP\&.
.SS "void TargetIntTab::editLine ()\fC [slot]\fP"

.PP
Definition at line \fB131\fP of file \fBTargetIntTab\&.cpp\fP\&.
.SS "\fBTargetIntModel\fP * TargetIntTab::getTargetIntModel ()"

.PP
Definition at line \fB70\fP of file \fBTargetIntTab\&.cpp\fP\&.
.SS "bool TargetIntTab::readFile (QTextStream & inStream)"

.PP
Definition at line \fB304\fP of file \fBTargetIntTab\&.cpp\fP\&.
.SS "void TargetIntTab::reset ()"

.PP
Definition at line \fB369\fP of file \fBTargetIntTab\&.cpp\fP\&.
.SS "void TargetIntTab::showInfo (int which = \fC0\fP, QString title = \fC''\fP)\fC [slot]\fP"

.PP
Definition at line \fB373\fP of file \fBTargetIntTab\&.cpp\fP\&.
.SS "void TargetIntTab::updateButtons (const QItemSelection & selection)\fC [slot]\fP"

.PP
Definition at line \fB265\fP of file \fBTargetIntTab\&.cpp\fP\&.
.SS "bool TargetIntTab::writeFile (QTextStream & outStream)"

.PP
Definition at line \fB275\fP of file \fBTargetIntTab\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
