.TH "TargetEffect" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TargetEffect \- An AZURE target effect entry\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TargetEffect\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTargetEffect\fP (std::istream &, const \fBConfig\fP &)"
.br
.ti -1c
.RI "bool \fBIsActive\fP () const"
.br
.ti -1c
.RI "bool \fBIsConvolution\fP () const"
.br
.ti -1c
.RI "bool \fBIsTargetIntegration\fP () const"
.br
.ti -1c
.RI "bool \fBIsQCoefficients\fP () const"
.br
.ti -1c
.RI "int \fBNumSubPoints\fP () const"
.br
.ti -1c
.RI "int \fBNumQCoefficients\fP () const"
.br
.ti -1c
.RI "double \fBGetSigma\fP () const"
.br
.ti -1c
.RI "double \fBGetDensity\fP () const"
.br
.ti -1c
.RI "double \fBTargetThickness\fP (double, const \fBConfig\fP &)"
.br
.ti -1c
.RI "double \fBGetConvolutionFactor\fP (double, double) const"
.br
.ti -1c
.RI "double \fBGetQCoefficient\fP (int) const"
.br
.ti -1c
.RI "void \fBSetSigma\fP (double)"
.br
.ti -1c
.RI "void \fBSetNumSubPoints\fP (int)"
.br
.ti -1c
.RI "std::vector< int > \fBGetSegmentsList\fP () const"
.br
.ti -1c
.RI "\fBEquation\fP * \fBGetStoppingPowerEq\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr double \fBconvolutionRange\fP =3\&."
.br
.RI "The multiple of sigma above and below centroid energy to use as integration range\&. "
.in -1c
.SH "Detailed Description"
.PP 
An AZURE target effect entry\&. 

Experimential effects including gaussian beam convolution, target integration, and a combination of the two are grouped under the \fBTargetEffect\fP class\&. An object is created corresponding to each corresponding entry in AZURESetup2\&. 
.PP
Definition at line \fB19\fP of file \fBTargetEffect\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TargetEffect::TargetEffect (std::istream & stream, const \fBConfig\fP & configure)"
Constructor reads directly from an std::ifstream pointing to the target effect input file\&. If a valid target effect is read, a \fBTargetEffect\fP object is created\&. 
.PP
Definition at line \fB11\fP of file \fBTargetEffect\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "double TargetEffect::GetConvolutionFactor (double energy, double centroid) const"
Returns the multiplicative convolution factor for evaluation of the integrand of a target effect\&. 
.br
 
.PP
Definition at line \fB225\fP of file \fBTargetEffect\&.cpp\fP\&.
.SS "double TargetEffect::GetDensity () const"
Returns the density of the target in atoms/cm^2\&. Only needed for target integration, not Gaussian beam convolution\&. 
.PP
Definition at line \fB138\fP of file \fBTargetEffect\&.cpp\fP\&.
.SS "double TargetEffect::GetQCoefficient (int order) const"
Returns the attenuation coefficients for the given order specified in by the target effect\&. 
.PP
Definition at line \fB155\fP of file \fBTargetEffect\&.cpp\fP\&.
.SS "std::vector< int > TargetEffect::GetSegmentsList () const"
Parses and returns a vector of integers corresponding to the segment list specified as a string\&. The segments list contains the segments for which the target effect is applicable\&. 
.PP
Definition at line \fB181\fP of file \fBTargetEffect\&.cpp\fP\&.
.SS "double TargetEffect::GetSigma () const"
Returns the sigma of the Guassian for beam convolution\&. 
.PP
Definition at line \fB129\fP of file \fBTargetEffect\&.cpp\fP\&.
.SS "\fBEquation\fP * TargetEffect::GetStoppingPowerEq ()"
Returns the \fBEquation\fP object corresponding to the parametrized stopping cross section\&. 
.PP
Definition at line \fB214\fP of file \fBTargetEffect\&.cpp\fP\&.
.SS "bool TargetEffect::IsActive () const"
Returns true if the target effect was marked as active in the target effects input file, otherwise returns false\&. 
.PP
Definition at line \fB76\fP of file \fBTargetEffect\&.cpp\fP\&.
.SS "bool TargetEffect::IsConvolution () const"
Returns true if the target effect contains Gaussian beam convolution, otherwise returns false\&. 
.PP
Definition at line \fB85\fP of file \fBTargetEffect\&.cpp\fP\&.
.SS "bool TargetEffect::IsQCoefficients () const"
Returns true if the target effect contains attenuation coefficients, otherwise returns false\&. 
.PP
Definition at line \fB103\fP of file \fBTargetEffect\&.cpp\fP\&.
.SS "bool TargetEffect::IsTargetIntegration () const"
Returns true if the target effect contains target integration, otherwise returns false\&. 
.PP
Definition at line \fB94\fP of file \fBTargetEffect\&.cpp\fP\&.
.SS "int TargetEffect::NumQCoefficients () const"
Returns the number of attenuation coefficients for the target effect in the input file\&. 
.PP
Definition at line \fB121\fP of file \fBTargetEffect\&.cpp\fP\&.
.SS "int TargetEffect::NumSubPoints () const"
Returns the number of sub-points specified for the target effect in the input file\&. 
.PP
Definition at line \fB112\fP of file \fBTargetEffect\&.cpp\fP\&.
.SS "void TargetEffect::SetNumSubPoints (int numPoints)"
Sets the number of sub-points for the \fBTargetEffect\fP object\&. 
.PP
Definition at line \fB171\fP of file \fBTargetEffect\&.cpp\fP\&.
.SS "void TargetEffect::SetSigma (double sigma)"
Sets the convolution sigma to a new value\&. 
.PP
Definition at line \fB163\fP of file \fBTargetEffect\&.cpp\fP\&.
.SS "double TargetEffect::TargetThickness (double energy, const \fBConfig\fP & configure)"
Calculates the Target thickness from the stopping cross section and the target density as a function of energy\&. 
.PP
Definition at line \fB147\fP of file \fBTargetEffect\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "constexpr double TargetEffect::convolutionRange =3\&.\fC [static]\fP, \fC [constexpr]\fP"

.PP
The multiple of sigma above and below centroid energy to use as integration range\&. 
.PP
Definition at line \fB38\fP of file \fBTargetEffect\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
