.TH "/Users/kuba/Desktop/R-Matrix/AZURE2/gui/src/TargetIntModel.cpp" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kuba/Desktop/R-Matrix/AZURE2/gui/src/TargetIntModel.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QVariant>\fP
.br
\fC#include 'TargetIntModel\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
