.TH "TargetIntModel" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TargetIntModel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TargetIntModel\&.h>\fP
.PP
Inherits QAbstractTableModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTargetIntModel\fP (QObject *parent=0)"
.br
.ti -1c
.RI "int \fBrowCount\fP (const QModelIndex &parent) const"
.br
.ti -1c
.RI "int \fBcolumnCount\fP (const QModelIndex &parent) const"
.br
.ti -1c
.RI "QVariant \fBdata\fP (const QModelIndex &index, int role) const"
.br
.ti -1c
.RI "QVariant \fBheaderData\fP (int section, Qt::Orientation orientation, int role) const"
.br
.ti -1c
.RI "bool \fBsetData\fP (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)"
.br
.ti -1c
.RI "bool \fBinsertRows\fP (int position, int rows, const QModelIndex &index=QModelIndex())"
.br
.ti -1c
.RI "bool \fBremoveRows\fP (int position, int rows, const QModelIndex &index=QModelIndex())"
.br
.ti -1c
.RI "Qt::ItemFlags \fBflags\fP (const QModelIndex &index) const"
.br
.ti -1c
.RI "QList< \fBTargetIntData\fP > \fBgetLines\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB25\fP of file \fBTargetIntModel\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TargetIntModel::TargetIntModel (QObject * parent = \fC0\fP)"

.PP
Definition at line \fB5\fP of file \fBTargetIntModel\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int TargetIntModel::columnCount (const QModelIndex & parent) const"

.PP
Definition at line \fB13\fP of file \fBTargetIntModel\&.cpp\fP\&.
.SS "QVariant TargetIntModel::data (const QModelIndex & index, int role) const"

.PP
Definition at line \fB18\fP of file \fBTargetIntModel\&.cpp\fP\&.
.SS "Qt::ItemFlags TargetIntModel::flags (const QModelIndex & index) const"

.PP
Definition at line \fB158\fP of file \fBTargetIntModel\&.cpp\fP\&.
.SS "QList< \fBTargetIntData\fP > TargetIntModel::getLines () const\fC [inline]\fP"

.PP
Definition at line \fB38\fP of file \fBTargetIntModel\&.h\fP\&.
.SS "QVariant TargetIntModel::headerData (int section, Qt::Orientation orientation, int role) const"

.PP
Definition at line \fB64\fP of file \fBTargetIntModel\&.cpp\fP\&.
.SS "bool TargetIntModel::insertRows (int position, int rows, const QModelIndex & index = \fCQModelIndex()\fP)"

.PP
Definition at line \fB133\fP of file \fBTargetIntModel\&.cpp\fP\&.
.SS "bool TargetIntModel::removeRows (int position, int rows, const QModelIndex & index = \fCQModelIndex()\fP)"

.PP
Definition at line \fB146\fP of file \fBTargetIntModel\&.cpp\fP\&.
.SS "int TargetIntModel::rowCount (const QModelIndex & parent) const"

.PP
Definition at line \fB8\fP of file \fBTargetIntModel\&.cpp\fP\&.
.SS "bool TargetIntModel::setData (const QModelIndex & index, const QVariant & value, int role = \fCQt::EditRole\fP)"

.PP
Definition at line \fB99\fP of file \fBTargetIntModel\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
