.TH "TempTMatrix" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TempTMatrix \- A temporaray T-Matrix structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GenMatrixFunc\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBjValue\fP"
.br
.RI "Total spin value of temporary matrix element\&. "
.ti -1c
.RI "int \fBlValue\fP"
.br
.RI "Entrance orbital angular momentum for temporary matrix element\&. "
.ti -1c
.RI "int \fBlpValue\fP"
.br
.RI "Exit orbital angular momentum for temporary matrix element\&. "
.ti -1c
.RI "\fBcomplex\fP \fBTMatrix\fP"
.br
.RI "Value of temporary matrix element\&. "
.in -1c
.SH "Detailed Description"
.PP 
A temporaray T-Matrix structure\&. 

The \fBTempTMatrix\fP structure is used to coherently add T-matrix elements from pathways with like $ J,l,l' $ values for the calculation of angle integrated cross section\&. This is primarly used to facilitate the interference between internal and external pathways\&. 
.PP
Definition at line \fB18\fP of file \fBGenMatrixFunc\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double TempTMatrix::jValue"

.PP
Total spin value of temporary matrix element\&. 
.PP
Definition at line \fB20\fP of file \fBGenMatrixFunc\&.h\fP\&.
.SS "int TempTMatrix::lpValue"

.PP
Exit orbital angular momentum for temporary matrix element\&. 
.PP
Definition at line \fB24\fP of file \fBGenMatrixFunc\&.h\fP\&.
.SS "int TempTMatrix::lValue"

.PP
Entrance orbital angular momentum for temporary matrix element\&. 
.PP
Definition at line \fB22\fP of file \fBGenMatrixFunc\&.h\fP\&.
.SS "\fBcomplex\fP TempTMatrix::TMatrix"

.PP
Value of temporary matrix element\&. 
.PP
Definition at line \fB26\fP of file \fBGenMatrixFunc\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
