.TH "/Users/kuba/Desktop/R-Matrix/AZURE2/include/WhitFunc.h" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/kuba/Desktop/R-Matrix/AZURE2/include/WhitFunc.h
.SH SYNOPSIS
.br
.PP
\fC#include 'PPair\&.h'\fP
.br
\fC#include <gsl/gsl_sf_hyperg\&.h>\fP
.br
\fC#include 'Constants\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWhitFunc\fP"
.br
.RI "A function class to calculate Whittaker functions for negative energy channels\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBgsl_whit_function\fP (int, double, double, double, int, int)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double gsl_whit_function (int, double, double, double, int, int)"

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
