.TH "WhitFunc" 3AZURE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WhitFunc \- A function class to calculate Whittaker functions for negative energy channels\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WhitFunc\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWhitFunc\fP (\fBPPair\fP *pPair)"
.br
.ti -1c
.RI "int \fBz1\fP () const"
.br
.ti -1c
.RI "int \fBz2\fP () const"
.br
.ti -1c
.RI "double \fBredmass\fP () const"
.br
.ti -1c
.RI "double \fBoperator()\fP (int l, double radius, double energy) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
A function class to calculate Whittaker functions for negative energy channels\&. 

The function class \fBWhitFunc\fP uses the GSL package to calculate Whittaker functions for negative energy channels from the GSL confluent hypergeometric functions\&. 
.br
 
.PP
Definition at line \fB16\fP of file \fBWhitFunc\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WhitFunc::WhitFunc (\fBPPair\fP * pPair)\fC [inline]\fP"
The \fBWhitFunc\fP object is created with reference to a \fBPPair\fP object\&. 
.PP
Definition at line \fB21\fP of file \fBWhitFunc\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "double WhitFunc::operator() (int l, double radius, double energy) const\fC [inline]\fP"
The parenthesis operator is defined to make the class instance callable as a function\&. The orbital angular momentum, binding energy, and radius are the dependent variables\&. The function returns the value of the Whittaker function\&. 
.PP
Definition at line \fB49\fP of file \fBWhitFunc\&.h\fP\&.
.SS "double WhitFunc::redmass () const\fC [inline]\fP"
Returns the reduced mass of the particle pair\&. 
.PP
Definition at line \fB41\fP of file \fBWhitFunc\&.h\fP\&.
.SS "int WhitFunc::z1 () const\fC [inline]\fP"
Returns the atomic number of the first particle in the pair\&. 
.PP
Definition at line \fB29\fP of file \fBWhitFunc\&.h\fP\&.
.SS "int WhitFunc::z2 () const\fC [inline]\fP"
Returns the atomic number of the second particle in the pair\&. 
.PP
Definition at line \fB35\fP of file \fBWhitFunc\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AZURE2 from the source code\&.
